import type HskList from "~/types/HskList";

const lesson1: HskList = {
  id: "hmcs97kF5",
  level: 1,
  words: [
    {
      simplified: "我",
      traditional: "我",
      pinyin: "wǒ",
      english: "I, me",
    },
    {
      simplified: "我们",
      traditional: "我們",
      pinyin: "wǒmen",
      english: "We, us",
    },
    {
      simplified: "你",
      traditional: "你",
      pinyin: "nǐ",
      english: "You",
    },
    {
      simplified: "你们",
      traditional: "你們",
      pinyin: "nǐmen",
      english: "You (pl.)",
    },
    {
      simplified: "他",
      traditional: "他",
      pinyin: "tā",
      english: "He, him",
    },
    {
      simplified: "她",
      traditional: "她",
      pinyin: "tā",
      english: "She, her",
    },
    {
      simplified: "他们",
      traditional: "他們",
      pinyin: "tāmen",
      english: "They (male+female)",
    },
    {
      simplified: "她们",
      traditional: "她們",
      pinyin: "tāmen",
      english: "They (females)",
    },
    {
      simplified: "这",
      traditional: "這",
      pinyin: "zhè",
      english: "Here, this",
    },
    {
      simplified: "那",
      traditional: "那",
      pinyin: "nà",
      english: "There, that",
    },
    {
      simplified: "哪",
      traditional: "哪",
      pinyin: "nǎ",
      english: "Where",
    },
    {
      simplified: "谁",
      traditional: "誰",
      pinyin: "shéi",
      english: "Who",
    },
    {
      simplified: "什么",
      traditional: "什麼",
      pinyin: "shénme",
      english: "What, why",
    },
    {
      simplified: "多少",
      traditional: "多少",
      pinyin: "duōshǎo",
      english: "How many, how much",
    },
    {
      simplified: "几",
      traditional: "幾",
      pinyin: "jǐ",
      english: "A few, how many",
    },
    {
      simplified: "怎么",
      traditional: "怎麼",
      pinyin: "zěnme",
      english: "How",
    },
    {
      simplified: "怎么样",
      traditional: "怎麼樣",
      pinyin: "zěnmeyàng",
      english: "How about",
    },
    {
      simplified: "它",
      traditional: "它",
      pinyin: "tā",
      english: "It",
    },
    {
      simplified: "大家",
      traditional: "大家",
      pinyin: "dàjiā",
      english: "Everyone",
    },
    {
      simplified: "每",
      traditional: "每",
      pinyin: "měi",
      english: "Every",
    },
    {
      simplified: "为什么",
      traditional: "為什麼",
      pinyin: "wèishénme",
      english: "Why",
    },
    {
      simplified: "一",
      traditional: "一",
      pinyin: "yī",
      english: "One",
    },
    {
      simplified: "二",
      traditional: "二",
      pinyin: "èr",
      english: "Two",
    },
    {
      simplified: "三",
      traditional: "三",
      pinyin: "sān",
      english: "Three",
    },
    {
      simplified: "四",
      traditional: "四",
      pinyin: "sì",
      english: "Four",
    },
    {
      simplified: "五",
      traditional: "五",
      pinyin: "wǔ",
      english: "Five",
    },
    {
      simplified: "六",
      traditional: "六",
      pinyin: "liù",
      english: "Six",
    },
    {
      simplified: "七",
      traditional: "七",
      pinyin: "qī",
      english: "Seven",
    },
    {
      simplified: "八",
      traditional: "八",
      pinyin: "bā",
      english: "Eight",
    },
    {
      simplified: "九",
      traditional: "九",
      pinyin: "jiǔ",
      english: "Nine",
    },
    {
      simplified: "十",
      traditional: "十",
      pinyin: "shí",
      english: "Ten",
    },
    {
      simplified: "零",
      traditional: "零",
      pinyin: "líng",
      english: "Zero",
    },
    {
      simplified: "两",
      traditional: "兩",
      pinyin: "liǎng",
      english: "Two (alt.)",
    },
    {
      simplified: "百",
      traditional: "百",
      pinyin: "bǎi",
      english: "Hundred",
    },
    {
      simplified: "千",
      traditional: "千",
      pinyin: "qiān",
      english: "Thousand",
    },
    {
      simplified: "第一",
      traditional: "第一",
      pinyin: "dìyī",
      english: "First",
    },
    {
      simplified: "个",
      traditional: "個",
      pinyin: "gè",
      english: "One, a, an",
    },
    {
      simplified: "岁",
      traditional: "歲",
      pinyin: "suì",
      english: "Year",
    },
    {
      simplified: "本",
      traditional: "本",
      pinyin: "běn",
      english: "Volume",
    },
    {
      simplified: "些",
      traditional: "些",
      pinyin: "xiē",
      english: "Some",
    },
    {
      simplified: "块",
      traditional: "塊",
      pinyin: "kuài",
      english: "Piece, block, bit",
    },
    {
      simplified: "次",
      traditional: "次",
      pinyin: "cì",
      english: "Number",
    },
    {
      simplified: "公斤",
      traditional: "公斤",
      pinyin: "gōngjīn",
      english: "Kilogram",
    },
    {
      simplified: "元",
      traditional: "元",
      pinyin: "yuán",
      english: "Yuan",
    },
    {
      simplified: "件",
      traditional: "事",
      pinyin: "jiàn",
      english: "Piece, thing, fact, matter",
    },
    {
      simplified: "张",
      traditional: "張",
      pinyin: "zhāng",
      english: "Sheet",
    },
    {
      simplified: "不",
      traditional: "不",
      pinyin: "bù",
      english: "No, do not",
    },
    {
      simplified: "没",
      traditional: "沒",
      pinyin: "méi",
      english: "No, not",
    },
    {
      simplified: "很",
      traditional: "很",
      pinyin: "hěn",
      english: "Quite, very",
    },
    {
      simplified: "太",
      traditional: "太",
      pinyin: "tài",
      english: "Too",
    },
    {
      simplified: "都",
      traditional: "都",
      pinyin: "dōu",
      english: "All",
    },
    {
      simplified: "别",
      traditional: "別",
      pinyin: "bié",
      english: "Other",
    },
    {
      simplified: "非常",
      traditional: "非常",
      pinyin: "fēicháng",
      english: "Very",
    },
    {
      simplified: "也",
      traditional: "也",
      pinyin: "yě",
      english: "Likewise",
    },
    {
      simplified: "还",
      traditional: "還",
      pinyin: "hái",
      english: "Still",
    },
    {
      simplified: "最",
      traditional: "最",
      pinyin: "zuì",
      english: "Most",
    },
    {
      simplified: "真",
      traditional: "真",
      pinyin: "zhēn",
      english: "Real",
    },
    {
      simplified: "正在",
      traditional: "正在",
      pinyin: "zhèngzài",
      english: "Be being",
    },
    {
      simplified: "已经",
      traditional: "已經",
      pinyin: "yǐjīng",
      english: "Already",
    },
    {
      simplified: "一起",
      traditional: "一起",
      pinyin: "yìqǐ",
      english: "Together",
    },
    {
      simplified: "再",
      traditional: "再",
      pinyin: "zài",
      english: "Again",
    },
    {
      simplified: "就",
      traditional: "就",
      pinyin: "jiǜ",
      english: "At once",
    },
    {
      simplified: "您",
      traditional: "您",
      pinyin: "nín",
      english: "You",
    },
    {
      simplified: "和",
      traditional: "和",
      pinyin: "hé",
      english: "And",
    },
    {
      simplified: "因为",
      traditional: "因為",
      pinyin: "yīnwèi",
      english: "Because",
    },
    {
      simplified: "所以",
      traditional: "所以",
      pinyin: "suǒyǐ",
      english: "So",
    },
    {
      simplified: "但是",
      traditional: "但是",
      pinyin: "dànshì",
      english: "But",
    },
    {
      simplified: "在",
      traditional: "在",
      pinyin: "zài",
      english: "In, at",
    },
    {
      simplified: "从",
      traditional: "從",
      pinyin: "cóng",
      english: "From",
    },
    {
      simplified: "对",
      traditional: "對",
      pinyin: "duì",
      english: "Right",
    },
    {
      simplified: "此",
      traditional: "此",
      pinyin: "cǐ",
      english: "This",
    },
    {
      simplified: "向",
      traditional: "向",
      pinyin: "xiàng",
      english: "Towards",
    },
    {
      simplified: "离",
      traditional: "離",
      pinyin: "lí",
      english: "Leave",
    },
    {
      simplified: "喂",
      traditional: "餵",
      pinyin: "wèi",
      english: "Hello",
    },
    {
      simplified: "家",
      traditional: "家",
      pinyin: "jiā",
      english: "Home",
    },
    {
      simplified: "学校",
      traditional: "學校",
      pinyin: "xuéxiào",
      english: "School",
    },
    {
      simplified: "饭馆",
      traditional: "飯館",
      pinyin: "fàndiàn",
      english: "Restaunt",
    },
    {
      simplified: "商店",
      traditional: "商店",
      pinyin: "shāngdiàn",
      english: "Store",
    },
    {
      simplified: "医院",
      traditional: "醫院",
      pinyin: "yīyuàn",
      english: "Hospital",
    },
    {
      simplified: "火车站",
      traditional: "火車站",
      pinyin: "huǒchēzhàn",
      english: "Train station",
    },
    {
      simplified: "中国",
      traditional: "中國",
      pinyin: "Zhōngguó",
      english: "China",
    },
    {
      simplified: "机场",
      traditional: "機場",
      pinyin: "jīchǎng",
      english: "Airport",
    },
    {
      simplified: "教室",
      traditional: "教室",
      pinyin: "jiàoshì",
      english: "Classroom",
    },
    {
      simplified: "房间",
      traditional: "房間",
      pinyin: "fángjiān",
      english: "Room",
    },
    {
      simplified: "路",
      traditional: "路",
      pinyin: "lù",
      english: "Road",
    },
    {
      simplified: "北京",
      traditional: "北京",
      pinyin: "Běijīng",
      english: "Beijing",
    },
    {
      simplified: "上",
      traditional: "上",
      pinyin: "shàng",
      english: "Up",
    },
    {
      simplified: "下",
      traditional: "下",
      pinyin: "xià",
      english: "Below",
    },
    {
      simplified: "前面",
      traditional: "前面",
      pinyin: "qiánmiàn",
      english: "Front",
    },
    {
      simplified: "后面",
      traditional: "後面",
      pinyin: "hòumiàn",
      english: "Behind",
    },
    {
      simplified: "左边",
      traditional: "左邊",
      pinyin: "zuǒbiān",
      english: "Left",
    },
    {
      simplified: "右边",
      traditional: "右邊",
      pinyin: "yòubiān",
      english: "Right",
    },
    {
      simplified: "外",
      traditional: "外",
      pinyin: "wài",
      english: "Out",
    },
    {
      simplified: "旁边",
      traditional: "旁邊",
      pinyin: "pángbiān",
      english: "Side",
    },
    {
      simplified: "里",
      traditional: "裡",
      pinyin: "lǐ",
      english: "Inside",
    },
    {
      simplified: "今天",
      traditional: "今天",
      pinyin: "jīntiān",
      english: "Today",
    },
    {
      simplified: "明天",
      traditional: "明天",
      pinyin: "míngtiān",
      english: "Tomorrow",
    },
    {
      simplified: "昨天",
      traditional: "昨天",
      pinyin: "zuótiān",
      english: "Yesterday",
    },
    {
      simplified: "上午",
      traditional: "上午",
      pinyin: "shàngwǔ",
      english: "Morning",
    },
    {
      simplified: "中午",
      traditional: "中午",
      pinyin: "zhōngwǔ",
      english: "Noon",
    },
    {
      simplified: "下午",
      traditional: "下午",
      pinyin: "xiàwǔ",
      english: "Afternoon",
    },
    {
      simplified: "年",
      traditional: "年",
      pinyin: "nián",
      english: "Year",
    },
    {
      simplified: "月",
      traditional: "月",
      pinyin: "yuè",
      english: "Month",
    },
    {
      simplified: "日",
      traditional: "日",
      pinyin: "rì",
      english: "Day",
    },
    {
      simplified: "星期",
      traditional: "星期",
      pinyin: "xīngqī",
      english: "Week",
    },
    {
      simplified: "点",
      traditional: "點",
      pinyin: "diǎn",
      english: "Dot, spot",
    },
    {
      simplified: "分钟",
      traditional: "分鐘",
      pinyin: "fēnzhōng",
      english: "Minute",
    },
    {
      simplified: "现在",
      traditional: "現在",
      pinyin: "xiànzài",
      english: "Now",
    },
    {
      simplified: "时候",
      traditional: "時候",
      pinyin: "shíhou",
      english: "Time, moment",
    },
    {
      simplified: "早上",
      traditional: "早上",
      pinyin: "zǎoshàng",
      english: "Morning, morrow",
    },
    {
      simplified: "晚上",
      traditional: "晚上",
      pinyin: "wǎnshàng",
      english: "Night",
    },
    {
      simplified: "小时",
      traditional: "小時",
      pinyin: "xiǎoshí",
      english: "Hour",
    },
    {
      simplified: "时间",
      traditional: "時間",
      pinyin: "shíjiān",
      english: "Time, period",
    },
    {
      simplified: "去年",
      traditional: "去年",
      pinyin: "qùnián",
      english: "Last year",
    },
    {
      simplified: "号",
      traditional: "號",
      pinyin: "hào",
      english: "Number",
    },
    {
      simplified: "生日",
      traditional: "生日",
      pinyin: "shēngrì",
      english: "Birthday",
    },
    {
      simplified: "爸爸",
      traditional: "爸爸",
      pinyin: "bàba",
      english: "Father",
    },
    {
      simplified: "妈妈",
      traditional: "媽媽",
      pinyin: "māma",
      english: "Mother",
    },
    {
      simplified: "儿子",
      traditional: "兒子",
      pinyin: "érzi",
      english: "Son",
    },
    {
      simplified: "女儿",
      traditional: "女兒",
      pinyin: "nǚ'ér",
      english: "Daughter",
    },
    {
      simplified: "老师",
      traditional: "老師",
      pinyin: "lǎoshī",
      english: "Teacher",
    },
    {
      simplified: "学生",
      traditional: "學生",
      pinyin: "xuéshēng",
      english: "Student",
    },
    {
      simplified: "同学",
      traditional: "同學",
      pinyin: "tóngxué",
      english: "Shoolmate",
    },
    {
      simplified: "朋友",
      traditional: "朋友",
      pinyin: "péngyǒu",
      english: "Friend",
    },
    {
      simplified: "医生",
      traditional: "醫生",
      pinyin: "yīshēng",
      english: "Doctor",
    },
    {
      simplified: "先生",
      traditional: "先生",
      pinyin: "xiānsheng",
      english: "Sir",
    },
    {
      simplified: "小姐",
      traditional: "小姐",
      pinyin: "xiǎojiě",
      english: "Miss",
    },
    {
      simplified: "哥哥",
      traditional: "哥哥",
      pinyin: "gēge",
      english: "Older brother",
    },
    {
      simplified: "姐姐",
      traditional: "姐姐",
      pinyin: "jiějie",
      english: "Older sister",
    },
    {
      simplified: "弟弟",
      traditional: "弟弟",
      pinyin: "dìdi",
      english: "Younger brother",
    },
    {
      simplified: "妹妹",
      traditional: "妹妹",
      pinyin: "mèimei",
      english: "Younger sister",
    },
    {
      simplified: "丈夫",
      traditional: "丈夫",
      pinyin: "zhàngfu",
      english: "Husband",
    },
    {
      simplified: "妻子",
      traditional: "妻子",
      pinyin: "qīzi",
      english: "Wife",
    },
    {
      simplified: "孩子",
      traditional: "孩子",
      pinyin: "háizi",
      english: "Child",
    },
    {
      simplified: "男人",
      traditional: "男人",
      pinyin: "nánrén",
      english: "Man",
    },
    {
      simplified: "女人",
      traditional: "女人",
      pinyin: "nǚrén",
      english: "Woman",
    },
    {
      simplified: "服务员",
      traditional: "服務員",
      pinyin: "fúwùyuán",
      english: "Waiter",
    },
    {
      simplified: "衣服",
      traditional: "衣服",
      pinyin: "yīfu",
      english: "Cloth",
    },
    {
      simplified: "水",
      traditional: "水",
      pinyin: "shuǐ",
      english: "Water",
    },
    {
      simplified: "菜",
      traditional: "菜",
      pinyin: "cài",
      english: "Dish",
    },
    {
      simplified: "米饭",
      traditional: "米飯",
      pinyin: "mǐfàn",
      english: "Rice",
    },
    {
      simplified: "水果",
      traditional: "水果",
      pinyin: "shuǐguǒ",
      english: "Fruit",
    },
    {
      simplified: "苹果",
      traditional: "蘋果",
      pinyin: "píngguǒ",
      english: "Apple",
    },
    {
      simplified: "茶",
      traditional: "茶",
      pinyin: "chá",
      english: "Tea",
    },
    {
      simplified: "杯子",
      traditional: "杯子",
      pinyin: "bēizi",
      english: "Cup",
    },
    {
      simplified: "钱",
      traditional: "錢",
      pinyin: "qián",
      english: "Money",
    },
    {
      simplified: "飞机",
      traditional: "飛機",
      pinyin: "fēijī",
      english: "Airplane",
    },
    {
      simplified: "出租车",
      traditional: "出租車",
      pinyin: "chūzūchē",
      english: "Taxi",
    },
    {
      simplified: "电视",
      traditional: "電視",
      pinyin: "diànshì",
      english: "Television",
    },
    {
      simplified: "电脑",
      traditional: "電腦",
      pinyin: "diànnǎo",
      english: "Computer",
    },
    {
      simplified: "电影",
      traditional: "電影",
      pinyin: "diànyǐng",
      english: "Movie",
    },
    {
      simplified: "天气",
      traditional: "天氣",
      pinyin: "tiānqì",
      english: "Weather",
    },
    {
      simplified: "猫",
      traditional: "貓",
      pinyin: "māo",
      english: "Cat",
    },
    {
      simplified: "狗",
      traditional: "狗",
      pinyin: "gǒu",
      english: "Dog",
    },
    {
      simplified: "东西",
      traditional: "東西",
      pinyin: "dōngxi",
      english: "Thing",
    },
    {
      simplified: "鱼",
      traditional: "魚",
      pinyin: "yú",
      english: "Fish",
    },
    {
      simplified: "羊肉",
      traditional: "羊肉",
      pinyin: "yángròu",
      english: "Mutton",
    },
    {
      simplified: "牛奶",
      traditional: "牛奶",
      pinyin: "niúnǎi",
      english: "Milk",
    },
    {
      simplified: "鸡蛋",
      traditional: "雞蛋",
      pinyin: "jīdàn",
      english: "Egg",
    },
    {
      simplified: "西瓜",
      traditional: "西瓜",
      pinyin: "xīguā",
      english: "Watermelon",
    },
    {
      simplified: "咖啡",
      traditional: "咖啡",
      pinyin: "kāfēi",
      english: "Coffee",
    },
    {
      simplified: "自行车",
      traditional: "自行車",
      pinyin: "zìxíngchē",
      english: "Bike",
    },
    {
      simplified: "船",
      traditional: "船",
      pinyin: "chuán",
      english: "Boat",
    },
    {
      simplified: "雪",
      traditional: "雪",
      pinyin: "xuě",
      english: "Snow",
    },
    {
      simplified: "药",
      traditional: "藥",
      pinyin: "yào",
      english: "Medicine",
    },
    {
      simplified: "手机",
      traditional: "手機",
      pinyin: "shǒujī",
      english: "Cellphone",
    },
    {
      simplified: "手表",
      traditional: "手錶",
      pinyin: "shǒubiǎo",
      english: "Watch",
    },
    {
      simplified: "眼睛",
      traditional: "眼睛",
      pinyin: "yǎnjīng",
      english: "Eye",
    },
    {
      simplified: "身体",
      traditional: "身體",
      pinyin: "shēntǐ",
      english: "Body",
    },
    {
      simplified: "公共汽车",
      traditional: "公共汽車",
      pinyin: "gōnggòngqìchē",
      english: "Bus",
    },
  ],
};

export default lesson1;
