import type HskList from "~/types/HskList";

const lesson3: HskList = {
  id: "m1uti3kcG",
  level: 3,
  words: [
    {
      simplified: "阿姨",
      traditional: "阿姨",
      pinyin: "āyí",
      english: "Aunt",
    },
    {
      simplified: "啊",
      traditional: "啊",
      pinyin: "a",
      english: "Ah",
    },
    {
      simplified: "矮",
      traditional: "矮",
      pinyin: "ǎi",
      english: "Short",
    },
    {
      simplified: "爱好",
      traditional: "愛好",
      pinyin: "àihào",
      english: "Hobby",
    },
    {
      simplified: "安静",
      traditional: "安靜",
      pinyin: "ānjìng",
      english: "Be quiet",
    },
    {
      simplified: "把",
      traditional: "把",
      pinyin: "bǎ",
      english: "Hold",
    },
    {
      simplified: "班",
      traditional: "班",
      pinyin: "bān",
      english: "Class",
    },
    {
      simplified: "搬",
      traditional: "搬",
      pinyin: "bān",
      english: "Move",
    },
    {
      simplified: "半",
      traditional: "半",
      pinyin: "bàn",
      english: "Half",
    },
    {
      simplified: "办法",
      traditional: "辦法",
      pinyin: "bànfǎ",
      english: "Way",
    },
    {
      simplified: "办公室",
      traditional: "辦公室",
      pinyin: "bàngōngshì",
      english: "Office",
    },
    {
      simplified: "帮忙",
      traditional: "幫忙",
      pinyin: "bāngmáng",
      english: "Help",
    },
    {
      simplified: "包",
      traditional: "包",
      pinyin: "bāo",
      english: "Package",
    },
    {
      simplified: "饱",
      traditional: "飽",
      pinyin: "bǎo",
      english: "Full",
    },
    {
      simplified: "北方",
      traditional: "北方",
      pinyin: "běifāng",
      english: "North",
    },
    {
      simplified: "被",
      traditional: "被",
      pinyin: "bèi",
      english: "Cover",
    },
    {
      simplified: "鼻子",
      traditional: "鼻子",
      pinyin: "bízi",
      english: "Nose",
    },
    {
      simplified: "比",
      traditional: "比",
      pinyin: "bǐ",
      english: "Than",
    },
    {
      simplified: "比较",
      traditional: "比較",
      pinyin: "bǐjiào",
      english: "Compare",
    },
    {
      simplified: "比赛",
      traditional: "比賽",
      pinyin: "bǐsài",
      english: "Match",
    },
    {
      simplified: "必须",
      traditional: "必須",
      pinyin: "bìxū",
      english: "Must",
    },
    {
      simplified: "变化",
      traditional: "變化",
      pinyin: "biànhuà",
      english: "Change",
    },
    {
      simplified: "表示",
      traditional: "表示",
      pinyin: "biǎoshì",
      english: "Express",
    },
    {
      simplified: "表演",
      traditional: "表演",
      pinyin: "biǎoyǎn",
      english: "Perform",
    },
    {
      simplified: "别人",
      traditional: "別人",
      pinyin: "biéren",
      english: "Others",
    },
    {
      simplified: "宾馆",
      traditional: "賓館",
      pinyin: "bīnguǎn",
      english: "Hotel",
    },
    {
      simplified: "冰箱",
      traditional: "冰箱",
      pinyin: "bīngxiāng",
      english: "Refrigerator",
    },
    {
      simplified: "才",
      traditional: "才",
      pinyin: "cái",
      english: "Just",
    },
    {
      simplified: "菜单",
      traditional: "菜單",
      pinyin: "càidān",
      english: "Menu",
    },
    {
      simplified: "参加",
      traditional: "參加",
      pinyin: "cānjiā",
      english: "Participate in",
    },
    {
      simplified: "草",
      traditional: "草",
      pinyin: "cǎo",
      english: "Grass",
    },
    {
      simplified: "层",
      traditional: "層",
      pinyin: "céng",
      english: "Layer",
    },
    {
      simplified: "差",
      traditional: "差",
      pinyin: "chà",
      english: "Bad",
    },
    {
      simplified: "超市",
      traditional: "超市",
      pinyin: "chāoshì",
      english: "Supermarket",
    },
    {
      simplified: "衬衫",
      traditional: "襯衫",
      pinyin: "chènshān",
      english: "Shirt",
    },
    {
      simplified: "成绩",
      traditional: "成績",
      pinyin: "chéngjì",
      english: "Achievement",
    },
    {
      simplified: "城市",
      traditional: "城市",
      pinyin: "chéngshì",
      english: "City",
    },
    {
      simplified: "迟到",
      traditional: "遲到",
      pinyin: "chídào",
      english: "Late",
    },
    {
      simplified: "出现",
      traditional: "出現",
      pinyin: "chūxiàn",
      english: "Appear",
    },
    {
      simplified: "厨房",
      traditional: "廚房",
      pinyin: "chúfáng",
      english: "Kitchen",
    },
    {
      simplified: "除了",
      traditional: "除了",
      pinyin: "chúle",
      english: "Except, besides",
    },
    {
      simplified: "春",
      traditional: "春天",
      pinyin: "chūn",
      english: "Spring",
    },
    {
      simplified: "词语",
      traditional: "詞語",
      pinyin: "cíyǔ",
      english: "Terms, words",
    },
    {
      simplified: "聪明",
      traditional: "聰明",
      pinyin: "cōngming",
      english: "Clever",
    },
    {
      simplified: "打扫",
      traditional: "打掃",
      pinyin: "dǎsǎo",
      english: "Clean",
    },
    {
      simplified: "打算",
      traditional: "打算",
      pinyin: "dǎsuàn",
      english: "Plan",
    },
    {
      simplified: "带",
      traditional: "帶",
      pinyin: "dài",
      english: "Belt",
    },
    {
      simplified: "担心",
      traditional: "擔心",
      pinyin: "dānxīn",
      english: "Worry",
    },
    {
      simplified: "蛋糕",
      traditional: "蛋糕",
      pinyin: "dàngāo",
      english: "Cake",
    },
    {
      simplified: "当然",
      traditional: "當然",
      pinyin: "dāngrán",
      english: "Of course",
    },
    {
      simplified: "灯",
      traditional: "燈",
      pinyin: "dēng",
      english: "Lamp",
    },
    {
      simplified: "低",
      traditional: "低",
      pinyin: "dī",
      english: "Low",
    },
    {
      simplified: "地方",
      traditional: "地方",
      pinyin: "dìfang",
      english: "Local",
    },
    {
      simplified: "地铁",
      traditional: "地鐵",
      pinyin: "dìtiě",
      english: "Metro",
    },
    {
      simplified: "地图",
      traditional: "地圖",
      pinyin: "dìtú",
      english: "Map",
    },
    {
      simplified: "电梯",
      traditional: "電梯",
      pinyin: "diàntī",
      english: "Elevator",
    },
    {
      simplified: "电子邮件",
      traditional: "電子郵件",
      pinyin: "diànzǐyóujiàn",
      english: "E-mail",
    },
    {
      simplified: "东",
      traditional: "東",
      pinyin: "dōng",
      english: "East",
    },
    {
      simplified: "冬",
      traditional: "冬季",
      pinyin: "dōng",
      english: "Winter",
    },
    {
      simplified: "动物",
      traditional: "動物",
      pinyin: "dòngwù",
      english: "Animal",
    },
    {
      simplified: "短",
      traditional: "短",
      pinyin: "duǎn",
      english: "Short",
    },
    {
      simplified: "段",
      traditional: "段",
      pinyin: "duàn",
      english: "Paragraph",
    },
    {
      simplified: "锻炼",
      traditional: "鍛煉",
      pinyin: "duànliàn",
      english: "Physical exercise",
    },
    {
      simplified: "多么",
      traditional: "多麼",
      pinyin: "duōme",
      english: "Such",
    },
    {
      simplified: "饿",
      traditional: "餓",
      pinyin: "è",
      english: "Hungry",
    },
    {
      simplified: "而且",
      traditional: "而且",
      pinyin: "érqiě",
      english: "And",
    },
    {
      simplified: "耳朵",
      traditional: "耳朵",
      pinyin: "ěrduo",
      english: "Ears",
    },
    {
      simplified: "发烧",
      traditional: "發燒",
      pinyin: "fāshāo",
      english: "Have a fever",
    },
    {
      simplified: "发现",
      traditional: "發現",
      pinyin: "fāxiàn",
      english: "Find, discover",
    },
    {
      simplified: "方便",
      traditional: "方便",
      pinyin: "fāngbiàn",
      english: "Convenient",
    },
    {
      simplified: "放",
      traditional: "放",
      pinyin: "fàng",
      english: "Discharge",
    },
    {
      simplified: "放心",
      traditional: "放心",
      pinyin: "fàngxīn",
      english: "Don't worry",
    },
    {
      simplified: "分",
      traditional: "分",
      pinyin: "fēn",
      english: "Minute",
    },
    {
      simplified: "附近",
      traditional: "附近",
      pinyin: "fùjìn",
      english: "Nearby",
    },
    {
      simplified: "复习",
      traditional: "複習",
      pinyin: "fùxí",
      english: "Review",
    },
    {
      simplified: "干净",
      traditional: "乾淨",
      pinyin: "gānjìng",
      english: "Clean",
    },
    {
      simplified: "敢",
      traditional: "敢",
      pinyin: "gǎn",
      english: "Dare",
    },
    {
      simplified: "感冒",
      traditional: "感冒",
      pinyin: "gǎnmào",
      english: "Get a cold",
    },
    {
      simplified: "刚才",
      traditional: "剛才",
      pinyin: "gāngcái",
      english: "Just",
    },
    {
      simplified: "跟",
      traditional: "跟",
      pinyin: "gēn",
      english: "With",
    },
    {
      simplified: "根据",
      traditional: "根據",
      pinyin: "gēnjù",
      english: "According to",
    },
    {
      simplified: "更",
      traditional: "更",
      pinyin: "gèng",
      english: "More",
    },
    {
      simplified: "公司",
      traditional: "公司",
      pinyin: "gōngsī",
      english: "Company",
    },
    {
      simplified: "公园",
      traditional: "公園",
      pinyin: "gōngyuán",
      english: "Park",
    },
    {
      simplified: "故事",
      traditional: "故事",
      pinyin: "gùshi",
      english: "Story",
    },
    {
      simplified: "刮风",
      traditional: "刮風",
      pinyin: "guāfēng",
      english: "Windy",
    },
    {
      simplified: "关",
      traditional: "關",
      pinyin: "guān",
      english: "Shut",
    },
    {
      simplified: "关系",
      traditional: "關係",
      pinyin: "guānxì",
      english: "Relationship",
    },
    {
      simplified: "关心",
      traditional: "關心",
      pinyin: "guānxīn",
      english: "Care for",
    },
    {
      simplified: "关于",
      traditional: "關於",
      pinyin: "guānyú",
      english: "About",
    },
    {
      simplified: "国家",
      traditional: "國家",
      pinyin: "guójiā",
      english: "Country",
    },
    {
      simplified: "果汁",
      traditional: "果汁",
      pinyin: "guǒzhī",
      english: "Fruit juice",
    },
    {
      simplified: "过去",
      traditional: "過去",
      pinyin: "guòqù",
      english: "Past times",
    },
    {
      simplified: "过",
      traditional: "過",
      pinyin: "guo",
      english: "Too",
    },
    {
      simplified: "还是",
      traditional: "還是",
      pinyin: "háishì",
      english: "Still",
    },
    {
      simplified: "害怕",
      traditional: "害怕",
      pinyin: "hàipà",
      english: "Fear",
    },
    {
      simplified: "河",
      traditional: "河",
      pinyin: "hé",
      english: "River",
    },
    {
      simplified: "黑板",
      traditional: "黑板",
      pinyin: "hēibǎn",
      english: "Blackboard",
    },
    {
      simplified: "护照",
      traditional: "護照",
      pinyin: "hùzhào",
      english: "Passport",
    },
    {
      simplified: "花",
      traditional: "花",
      pinyin: "huā",
      english: "Spend (verb)",
    },
    {
      simplified: "花园",
      traditional: "花園",
      pinyin: "huāyuán",
      english: "Garden",
    },
    {
      simplified: "画",
      traditional: "畫",
      pinyin: "huà",
      english: "Painting",
    },
    {
      simplified: "坏",
      traditional: "壞",
      pinyin: "huài",
      english: "Bad",
    },
    {
      simplified: "环境",
      traditional: "環境",
      pinyin: "huánjìng",
      english: "Environment",
    },
    {
      simplified: "换",
      traditional: "換",
      pinyin: "huàn",
      english: "Change",
    },
    {
      simplified: "黄",
      traditional: "黃",
      pinyin: "huáng",
      english: "Yellow",
    },
    {
      simplified: "会议",
      traditional: "會議",
      pinyin: "huìyì",
      english: "Meeting",
    },
    {
      simplified: "或者",
      traditional: "或者",
      pinyin: "huòzhě",
      english: "Perhaps",
    },
    {
      simplified: "几乎",
      traditional: "幾乎",
      pinyin: "jīhū",
      english: "Almost",
    },
    {
      simplified: "机会",
      traditional: "機會",
      pinyin: "jīhuì",
      english: "Opportunity",
    },
    {
      simplified: "极",
      traditional: "極",
      pinyin: "jí",
      english: "Extremely",
    },
    {
      simplified: "记得",
      traditional: "記得",
      pinyin: "jìde",
      english: "Remember",
    },
    {
      simplified: "季节",
      traditional: "季節",
      pinyin: "jìjié",
      english: "Season",
    },
    {
      simplified: "检查",
      traditional: "檢查",
      pinyin: "jiǎnchá",
      english: "Inspect",
    },
    {
      simplified: "简单",
      traditional: "簡單",
      pinyin: "jiǎndān",
      english: "Simple",
    },
    {
      simplified: "健康",
      traditional: "健康",
      pinyin: "jiànkāng",
      english: "Healthy",
    },
    {
      simplified: "见面",
      traditional: "見面",
      pinyin: "jiànmiàn",
      english: "Meet",
    },
    {
      simplified: "讲",
      traditional: "講",
      pinyin: "jiǎng",
      english: "Speak",
    },
    {
      simplified: "教",
      traditional: "教",
      pinyin: "jiāo",
      english: "Teach",
    },
    {
      simplified: "角",
      traditional: "角",
      pinyin: "jiǎo",
      english: "Horn",
    },
    {
      simplified: "脚",
      traditional: "腳",
      pinyin: "jiǎo",
      english: "Foot",
    },
    {
      simplified: "接",
      traditional: "接",
      pinyin: "jiē",
      english: "Pick,get",
    },
    {
      simplified: "街道",
      traditional: "街道",
      pinyin: "jiēdào",
      english: "Street",
    },
    {
      simplified: "结婚",
      traditional: "結婚",
      pinyin: "jiéhūn",
      english: "Marry",
    },
    {
      simplified: "结束",
      traditional: "結束",
      pinyin: "jiéshù",
      english: "End",
    },
    {
      simplified: "节目",
      traditional: "節目",
      pinyin: "jiémù",
      english: "Program",
    },
    {
      simplified: "节日",
      traditional: "節日",
      pinyin: "jiérì",
      english: "Festival",
    },
    {
      simplified: "解决",
      traditional: "解決",
      pinyin: "jiějué",
      english: "Solve",
    },
    {
      simplified: "借",
      traditional: "借",
      pinyin: "jiè",
      english: "Borrow",
    },
    {
      simplified: "经常",
      traditional: "經常",
      pinyin: "jīngcháng",
      english: "Often",
    },
    {
      simplified: "经过",
      traditional: "經過",
      pinyin: "jīngguò",
      english: "After, through",
    },
    {
      simplified: "经理",
      traditional: "經理",
      pinyin: "jīnglǐ",
      english: "Manager",
    },
    {
      simplified: "久",
      traditional: "久",
      pinyin: "jiǔ",
      english: "Long",
    },
    {
      simplified: "旧",
      traditional: "舊",
      pinyin: "jiù",
      english: "Old,used",
    },
    {
      simplified: "举行",
      traditional: "舉行",
      pinyin: "jǔxíng",
      english: "Hold",
    },
    {
      simplified: "句子",
      traditional: "句子",
      pinyin: "jùzi",
      english: "Sentence",
    },
    {
      simplified: "决定",
      traditional: "決定",
      pinyin: "juédìng",
      english: "Decision",
    },
    {
      simplified: "渴",
      traditional: "渴",
      pinyin: "kě",
      english: "Thirsty",
    },
    {
      simplified: "可爱",
      traditional: "可愛",
      pinyin: "kě'ài",
      english: "Lovely",
    },
    {
      simplified: "刻",
      traditional: "刻",
      pinyin: "kè",
      english: "Moment",
    },
    {
      simplified: "客人",
      traditional: "客人",
      pinyin: "kèrén",
      english: "Guest",
    },
    {
      simplified: "空调",
      traditional: "空調",
      pinyin: "kōngtiáo",
      english: "Air conditioner",
    },
    {
      simplified: "口",
      traditional: "口",
      pinyin: "kǒu",
      english: "Mouth",
    },
    {
      simplified: "哭",
      traditional: "哭",
      pinyin: "kū",
      english: "Cry",
    },
    {
      simplified: "裤子",
      traditional: "褲子",
      pinyin: "kùzi",
      english: "Trousers",
    },
    {
      simplified: "筷子",
      traditional: "筷子",
      pinyin: "kuàizi",
      english: "Chopsticks",
    },
    {
      simplified: "蓝",
      traditional: "藍",
      pinyin: "lán",
      english: "Blue",
    },
    {
      simplified: "老",
      traditional: "老",
      pinyin: "lǎo",
      english: "Old",
    },
    {
      simplified: "离开",
      traditional: "離開",
      pinyin: "líkāi",
      english: "Leave",
    },
    {
      simplified: "礼物",
      traditional: "禮物",
      pinyin: "lǐwù",
      english: "Gift",
    },
    {
      simplified: "历史",
      traditional: "歷史",
      pinyin: "lìshǐ",
      english: "History",
    },
    {
      simplified: "脸",
      traditional: "臉",
      pinyin: "liǎn",
      english: "Face",
    },
    {
      simplified: "练习",
      traditional: "練習",
      pinyin: "liànxí",
      english: "Practice",
    },
    {
      simplified: "辆",
      traditional: "輛",
      pinyin: "liàng",
      english: "Car",
    },
    {
      simplified: "了解",
      traditional: "了解",
      pinyin: "liǎojiě",
      english: "Understand",
    },
    {
      simplified: "邻居",
      traditional: "鄰居",
      pinyin: "línjū",
      english: "Neighbor",
    },
    {
      simplified: "楼",
      traditional: "樓",
      pinyin: "lóu",
      english: "Floor",
    },
    {
      simplified: "绿",
      traditional: "綠",
      pinyin: "lǜ",
      english: "Green",
    },
    {
      simplified: "马",
      traditional: "馬",
      pinyin: "mǎ",
      english: "Horse",
    },
    {
      simplified: "马上",
      traditional: "馬上",
      pinyin: "mǎshàng",
      english: "Right off",
    },
    {
      simplified: "卖",
      traditional: "賣",
      pinyin: "mài",
      english: "Sell",
    },
    {
      simplified: "满意",
      traditional: "滿意",
      pinyin: "mǎnyì",
      english: "Satisfied",
    },
    {
      simplified: "帽子",
      traditional: "帽子",
      pinyin: "màozi",
      english: "Hat",
    },
    {
      simplified: "米",
      traditional: "米",
      pinyin: "mǐ",
      english: "Rice",
    },
    {
      simplified: "面包",
      traditional: "麵包",
      pinyin: "miànbāo",
      english: "Bread",
    },
    {
      simplified: "面条",
      traditional: "麵條",
      pinyin: "miàntiáo",
      english: "Noodle",
    },
    {
      simplified: "明白",
      traditional: "明白",
      pinyin: "míngbai",
      english: "Clear",
    },
    {
      simplified: "拿",
      traditional: "拿",
      pinyin: "ná",
      english: "Take",
    },
    {
      simplified: "奶奶",
      traditional: "奶奶",
      pinyin: "nǎinai",
      english: "Grandma",
    },
    {
      simplified: "南",
      traditional: "南",
      pinyin: "nán",
      english: "South",
    },
    {
      simplified: "难",
      traditional: "難",
      pinyin: "nán",
      english: "Difficult",
    },
    {
      simplified: "难过",
      traditional: "難過",
      pinyin: "nánguò",
      english: "Sad",
    },
    {
      simplified: "年级",
      traditional: "年級",
      pinyin: "niánjí",
      english: "Grade",
    },
    {
      simplified: "年轻",
      traditional: "年輕",
      pinyin: "niánqīng",
      english: "Young",
    },
    {
      simplified: "鸟",
      traditional: "鳥",
      pinyin: "niǎo",
      english: "Bird",
    },
    {
      simplified: "努力",
      traditional: "努力",
      pinyin: "nǔlì",
      english: "Strive",
    },
    {
      simplified: "爬山",
      traditional: "爬山",
      pinyin: "páshān",
      english: "Mountain climbing",
    },
    {
      simplified: "盘子",
      traditional: "盤子",
      pinyin: "pánzi",
      english: "Plate",
    },
    {
      simplified: "胖",
      traditional: "胖",
      pinyin: "pàng",
      english: "Fat",
    },
    {
      simplified: "啤酒",
      traditional: "啤酒",
      pinyin: "píjiǔ",
      english: "Beer",
    },
    {
      simplified: "葡萄",
      traditional: "葡萄",
      pinyin: "pútao",
      english: "Grape",
    },
    {
      simplified: "普通话",
      traditional: "普通話",
      pinyin: "pǔtōnghuà",
      english: "Mandarin",
    },
    {
      simplified: "其实",
      traditional: "其實",
      pinyin: "qíshí",
      english: "Actually",
    },
    {
      simplified: "其他",
      traditional: "其他",
      pinyin: "qítā",
      english: "Other",
    },
    {
      simplified: "骑",
      traditional: "騎",
      pinyin: "qí",
      english: "Ride",
    },
    {
      simplified: "奇怪",
      traditional: "奇怪",
      pinyin: "qíguài",
      english: "Strange",
    },
    {
      simplified: "铅笔",
      traditional: "鉛筆",
      pinyin: "qiānbǐ",
      english: "Pencil",
    },
    {
      simplified: "清楚",
      traditional: "清楚",
      pinyin: "qīngchu",
      english: "Clear",
    },
    {
      simplified: "秋",
      traditional: "秋",
      pinyin: "qiū",
      english: "Autumn",
    },
    {
      simplified: "裙子",
      traditional: "裙子",
      pinyin: "qúnzi",
      english: "Skirt",
    },
    {
      simplified: "然后",
      traditional: "然後",
      pinyin: "ránhòu",
      english: "Then",
    },
    {
      simplified: "热情",
      traditional: "熱情",
      pinyin: "rèqíng",
      english: "Enthusiasm",
    },
    {
      simplified: "认为",
      traditional: "認為",
      pinyin: "rènwéi",
      english: "Think",
    },
    {
      simplified: "认真",
      traditional: "認真",
      pinyin: "rènzhēn",
      english: "Earnest",
    },
    {
      simplified: "容易",
      traditional: "容易",
      pinyin: "róngyì",
      english: "Easily",
    },
    {
      simplified: "如果",
      traditional: "如果",
      pinyin: "rúguǒ",
      english: "If",
    },
    {
      simplified: "伞",
      traditional: "傘",
      pinyin: "sǎn",
      english: "Umbrella",
    },
    {
      simplified: "上网",
      traditional: "上網",
      pinyin: "shàngwǎng",
      english: "Surf the Internet",
    },
    {
      simplified: "生气",
      traditional: "生氣",
      pinyin: "shēngqì",
      english: "Get angry",
    },
    {
      simplified: "声音",
      traditional: "聲音",
      pinyin: "shēngyīn",
      english: "Voice",
    },
    {
      simplified: "使",
      traditional: "使",
      pinyin: "shǐ",
      english: "Make",
    },
    {
      simplified: "世界",
      traditional: "世界",
      pinyin: "shìjiè",
      english: "World",
    },
    {
      simplified: "瘦",
      traditional: "瘦",
      pinyin: "shòu",
      english: "Thin",
    },
    {
      simplified: "舒服",
      traditional: "舒服",
      pinyin: "shūfu",
      english: "Comfortable",
    },
    {
      simplified: "叔叔",
      traditional: "叔叔",
      pinyin: "shūshu",
      english: "Uncle",
    },
    {
      simplified: "树",
      traditional: "樹",
      pinyin: "shù",
      english: "Tree",
    },
    {
      simplified: "数学",
      traditional: "數學",
      pinyin: "shùxué",
      english: "Mathematics",
    },
    {
      simplified: "刷牙",
      traditional: "刷牙",
      pinyin: "shuāyá",
      english: "Brush one's teeth",
    },
    {
      simplified: "双",
      traditional: "雙",
      pinyin: "shuāng",
      english: "Double, pair",
    },
    {
      simplified: "水平",
      traditional: "水平",
      pinyin: "shuǐpíng",
      english: "Level",
    },
    {
      simplified: "司机",
      traditional: "司機",
      pinyin: "sījī",
      english: "Driver",
    },
    {
      simplified: "虽然",
      traditional: "雖然",
      pinyin: "suīrán",
      english: "Although",
    },
    {
      simplified: "太阳",
      traditional: "太陽",
      pinyin: "tàiyáng",
      english: "Sun",
    },
    {
      simplified: "糖",
      traditional: "糖",
      pinyin: "táng",
      english: "Sugar",
    },
    {
      simplified: "特别",
      traditional: "特別",
      pinyin: "tèbié",
      english: "Especially",
    },
    {
      simplified: "疼",
      traditional: "疼",
      pinyin: "téng",
      english: "Hurt",
    },
    {
      simplified: "提高",
      traditional: "提高",
      pinyin: "tígāo",
      english: "Increase",
    },
    {
      simplified: "体育",
      traditional: "體育",
      pinyin: "tǐyù",
      english: "Sports",
    },
    {
      simplified: "甜",
      traditional: "甜",
      pinyin: "tián",
      english: "Sweet",
    },
    {
      simplified: "条",
      traditional: "條",
      pinyin: "tiáo",
      english: "Strip",
    },
    {
      simplified: "同事",
      traditional: "同事",
      pinyin: "tóngshì",
      english: "Colleague",
    },
    {
      simplified: "同意",
      traditional: "同意",
      pinyin: "tóngyì",
      english: "Agree",
    },
    {
      simplified: "头发",
      traditional: "頭髮",
      pinyin: "tóufa",
      english: "Hair",
    },
    {
      simplified: "突然",
      traditional: "突然",
      pinyin: "tūrán",
      english: "Suddenly",
    },
    {
      simplified: "图书馆",
      traditional: "圖書館",
      pinyin: "túshūguǎn",
      english: "Library",
    },
    {
      simplified: "腿",
      traditional: "腿",
      pinyin: "tuǐ",
      english: "Leg",
    },
    {
      simplified: "完成",
      traditional: "完成",
      pinyin: "wánchéng",
      english: "Complete",
    },
    {
      simplified: "碗",
      traditional: "碗",
      pinyin: "wǎn",
      english: "Bowl",
    },
    {
      simplified: "万",
      traditional: "萬",
      pinyin: "wàn",
      english: "Ten thousand",
    },
    {
      simplified: "忘记",
      traditional: "忘記",
      pinyin: "wàngjì",
      english: "Forget",
    },
    {
      simplified: "为",
      traditional: "為",
      pinyin: "wèi",
      english: "For",
    },
    {
      simplified: "为了",
      traditional: "為了",
      pinyin: "wèile",
      english: "In order to",
    },
    {
      simplified: "位",
      traditional: "位",
      pinyin: "wèi",
      english: "Position",
    },
    {
      simplified: "文化",
      traditional: "文化",
      pinyin: "wénhuà",
      english: "Culture",
    },
    {
      simplified: "西",
      traditional: "西",
      pinyin: "xī",
      english: "West",
    },
    {
      simplified: "习惯",
      traditional: "習慣",
      pinyin: "xíguàn",
      english: "Habit",
    },
    {
      simplified: "洗手间",
      traditional: "洗手間",
      pinyin: "xǐshǒujiān",
      english: "Restroom",
    },
    {
      simplified: "洗澡",
      traditional: "洗澡",
      pinyin: "xǐzǎo",
      english: "Take a shower",
    },
    {
      simplified: "夏",
      traditional: "夏天",
      pinyin: "xià",
      english: "Summer",
    },
    {
      simplified: "先",
      traditional: "先",
      pinyin: "xiān",
      english: "First",
    },
    {
      simplified: "香蕉",
      traditional: "香蕉",
      pinyin: "xiāngjiāo",
      english: "Banana",
    },
    {
      simplified: "相同",
      traditional: "相同",
      pinyin: "xiāngtóng",
      english: "Identical",
    },
    {
      simplified: "相信",
      traditional: "相信",
      pinyin: "xiāngxìn",
      english: "Believe",
    },
    {
      simplified: "像",
      traditional: "像",
      pinyin: "xiàng",
      english: "Image",
    },
    {
      simplified: "小心",
      traditional: "小心",
      pinyin: "xiǎoxīn",
      english: "Watch out",
    },
    {
      simplified: "校长",
      traditional: "校長",
      pinyin: "xiàozhǎng",
      english: "Principal",
    },
    {
      simplified: "鞋",
      traditional: "鞋",
      pinyin: "xié",
      english: "Shoes",
    },
    {
      simplified: "新闻",
      traditional: "新聞",
      pinyin: "xīnwén",
      english: "News",
    },
    {
      simplified: "新鲜",
      traditional: "新鮮",
      pinyin: "xīnxiān",
      english: "Fresh",
    },
    {
      simplified: "信",
      traditional: "信",
      pinyin: "xìn",
      english: "Letter",
    },
    {
      simplified: "行李箱",
      traditional: "行李箱",
      pinyin: "xínglixiāng",
      english: "Trunk",
    },
    {
      simplified: "兴趣",
      traditional: "興趣",
      pinyin: "xìngqù",
      english: "Interest",
    },
    {
      simplified: "熊猫",
      traditional: "熊貓",
      pinyin: "xióngmāo",
      english: "Panda",
    },
    {
      simplified: "需要",
      traditional: "需要",
      pinyin: "xūyào",
      english: "Need",
    },
    {
      simplified: "选择",
      traditional: "選擇",
      pinyin: "xuǎnzé",
      english: "Choice",
    },
    {
      simplified: "眼镜",
      traditional: "眼鏡",
      pinyin: "yǎnjìng",
      english: "Glasses",
    },
    {
      simplified: "要求",
      traditional: "要求",
      pinyin: "yāoqiú",
      english: "Requirement",
    },
    {
      simplified: "爷爷",
      traditional: "爺爺",
      pinyin: "yéye",
      english: "Grandpa",
    },
    {
      simplified: "一定",
      traditional: "一定",
      pinyin: "yídìng",
      english: "Certain",
    },
    {
      simplified: "一共",
      traditional: "一共",
      pinyin: "yígòng",
      english: "Altogether",
    },
    {
      simplified: "一会儿",
      traditional: "一會兒",
      pinyin: "yíhuìr",
      english: "A while",
    },
    {
      simplified: "一样",
      traditional: "一樣",
      pinyin: "yíyàng",
      english: "Equally",
    },
    {
      simplified: "以后",
      traditional: "以後",
      pinyin: "yǐhòu",
      english: "In the future",
    },
    {
      simplified: "以前",
      traditional: "以前",
      pinyin: "yǐqián",
      english: "Before",
    },
    {
      simplified: "以为",
      traditional: "以為",
      pinyin: "yǐwéi",
      english: "Think",
    },
    {
      simplified: "一般",
      traditional: "一般",
      pinyin: "yìbān",
      english: "Commonly",
    },
    {
      simplified: "一边",
      traditional: "一邊",
      pinyin: "yìbiān",
      english: "One side",
    },
    {
      simplified: "一直",
      traditional: "一直",
      pinyin: "yìzhí",
      english: "Always",
    },
    {
      simplified: "音乐",
      traditional: "音樂",
      pinyin: "yīnyuè",
      english: "Music",
    },
    {
      simplified: "银行",
      traditional: "銀行",
      pinyin: "yínháng",
      english: "Bank",
    },
    {
      simplified: "应该",
      traditional: "應該",
      pinyin: "yīnggāi",
      english: "Should",
    },
    {
      simplified: "影响",
      traditional: "影響",
      pinyin: "yǐngxiǎng",
      english: "Influence",
    },
    {
      simplified: "用",
      traditional: "用",
      pinyin: "yòng",
      english: "Use",
    },
    {
      simplified: "游戏",
      traditional: "遊戲",
      pinyin: "yóuxì",
      english: "Game",
    },
    {
      simplified: "有名",
      traditional: "名譽",
      pinyin: "yǒumíng",
      english: "Famous",
    },
    {
      simplified: "又",
      traditional: "又",
      pinyin: "yòu",
      english: "Again",
    },
    {
      simplified: "遇到",
      traditional: "遇到",
      pinyin: "yùdào",
      english: "Encounter",
    },
    {
      simplified: "愿意",
      traditional: "願意",
      pinyin: "yuànyì",
      english: "Be willing",
    },
    {
      simplified: "月亮",
      traditional: "月亮",
      pinyin: "yuèliang",
      english: "Moon",
    },
    {
      simplified: "越",
      traditional: "越",
      pinyin: "yuè",
      english: "The more",
    },
    {
      simplified: "云",
      traditional: "雲",
      pinyin: "yún",
      english: "Cloud",
    },
    {
      simplified: "站",
      traditional: "站",
      pinyin: "zhàn",
      english: "Station",
    },
    {
      simplified: "着急",
      traditional: "著急",
      pinyin: "zháojí",
      english: "Worry",
    },
    {
      simplified: "照顾",
      traditional: "照顧",
      pinyin: "zhàogù",
      english: "Look after",
    },
    {
      simplified: "照片",
      traditional: "照片",
      pinyin: "zhàopiàn",
      english: "Photo",
    },
    {
      simplified: "照相机",
      traditional: "照相機",
      pinyin: "zhàoxiàngjī",
      english: "Camera",
    },
    {
      simplified: "只",
      traditional: "只",
      pinyin: "zhǐ",
      english: "Only",
    },
    {
      simplified: "中间",
      traditional: "中間",
      pinyin: "zhōngjiān",
      english: "Middle",
    },
    {
      simplified: "终于",
      traditional: "終於",
      pinyin: "zhōngyú",
      english: "Finally",
    },
    {
      simplified: "种",
      traditional: "種",
      pinyin: "zhǒng",
      english: "Species",
    },
    {
      simplified: "重要",
      traditional: "重要",
      pinyin: "zhòngyào",
      english: "Important",
    },
    {
      simplified: "周末",
      traditional: "週末",
      pinyin: "zhōumò",
      english: "Weekend",
    },
    {
      simplified: "主要",
      traditional: "主要",
      pinyin: "zhǔyào",
      english: "Main",
    },
    {
      simplified: "祝",
      traditional: "祝",
      pinyin: "zhù",
      english: "Wish",
    },
    {
      simplified: "注意",
      traditional: "注意",
      pinyin: "zhùyì",
      english: "Be careful",
    },
    {
      simplified: "字典",
      traditional: "字典",
      pinyin: "zìdiǎn",
      english: "Dictionaries",
    },
    {
      simplified: "自己",
      traditional: "自己",
      pinyin: "zìjǐ",
      english: "Own, self",
    },
    {
      simplified: "总是",
      traditional: "總是",
      pinyin: "zǒngshì",
      english: "Always",
    },
    {
      simplified: "最近",
      traditional: "最近",
      pinyin: "zuìjìn",
      english: "Lately",
    },
    {
      simplified: "作业",
      traditional: "作業",
      pinyin: "zuòyè",
      english: "Task",
    },
  ],
};

export default lesson3;
