import type HskList from "~/types/HskList";

const lesson1: HskList = {
  id: "hmcs97kF5",
  level: 1,
  words: [
    {
      english: "I, me",
      pinyin: "wǒ",
      simplified: "我",
      traditional: "我",
    },
    {
      english: "We, us",
      pinyin: "wǒmen",
      simplified: "我们",
      traditional: "我們",
    },
    {
      english: "You",
      pinyin: "nǐ",
      simplified: "你",
      traditional: "你",
    },
    {
      english: "You (pl.)",
      pinyin: "nǐmen",
      simplified: "你们",
      traditional: "你們",
    },
    {
      english: "He, him",
      pinyin: "tā",
      simplified: "他",
      traditional: "他",
    },
    {
      english: "She, her",
      pinyin: "tā",
      simplified: "她",
      traditional: "她",
    },
    {
      english: "They (male+female)",
      pinyin: "tāmen",
      simplified: "他们",
      traditional: "他們",
    },
    {
      english: "They (females)",
      pinyin: "tāmen",
      simplified: "她们",
      traditional: "她們",
    },
    {
      english: "Here, this",
      pinyin: "zhè",
      simplified: "这",
      traditional: "這",
    },
    {
      english: "There, that",
      pinyin: "nà",
      simplified: "那",
      traditional: "那",
    },
    {
      english: "Where",
      pinyin: "nǎ",
      simplified: "哪",
      traditional: "哪",
    },
    {
      english: "Who",
      pinyin: "shéi",
      simplified: "谁",
      traditional: "誰",
    },
    {
      english: "What, why",
      pinyin: "shénme",
      simplified: "什么",
      traditional: "什麼",
    },
    {
      english: "How many, how much",
      pinyin: "duōshǎo",
      simplified: "多少",
      traditional: "多少",
    },
    {
      english: "A few, how many",
      pinyin: "jǐ",
      simplified: "几",
      traditional: "幾",
    },
    {
      english: "How",
      pinyin: "zěnme",
      simplified: "怎么",
      traditional: "怎麼",
    },
    {
      english: "How about",
      pinyin: "zěnmeyàng",
      simplified: "怎么样",
      traditional: "怎麼樣",
    },
    {
      english: "It",
      pinyin: "tā",
      simplified: "它",
      traditional: "它",
    },
    {
      english: "Everyone",
      pinyin: "dàjiā",
      simplified: "大家",
      traditional: "大家",
    },
    {
      english: "Every",
      pinyin: "měi",
      simplified: "每",
      traditional: "每",
    },
    {
      english: "Why",
      pinyin: "wèishénme",
      simplified: "为什么",
      traditional: "為什麼",
    },
    {
      english: "One",
      pinyin: "yī",
      simplified: "一",
      traditional: "一",
    },
    {
      english: "Two",
      pinyin: "èr",
      simplified: "二",
      traditional: "二",
    },
    {
      english: "Three",
      pinyin: "sān",
      simplified: "三",
      traditional: "三",
    },
    {
      english: "Four",
      pinyin: "sì",
      simplified: "四",
      traditional: "四",
    },
    {
      english: "Five",
      pinyin: "wǔ",
      simplified: "五",
      traditional: "五",
    },
    {
      english: "Six",
      pinyin: "liù",
      simplified: "六",
      traditional: "六",
    },
    {
      english: "Seven",
      pinyin: "qī",
      simplified: "七",
      traditional: "七",
    },
    {
      english: "Eight",
      pinyin: "bā",
      simplified: "八",
      traditional: "八",
    },
    {
      english: "Nine",
      pinyin: "jiǔ",
      simplified: "九",
      traditional: "九",
    },
    {
      english: "Ten",
      pinyin: "shí",
      simplified: "十",
      traditional: "十",
    },
    {
      english: "Zero",
      pinyin: "líng",
      simplified: "零",
      traditional: "零",
    },
    {
      english: "Two (alt.)",
      pinyin: "liǎng",
      simplified: "两",
      traditional: "兩",
    },
    {
      english: "Hundred",
      pinyin: "bǎi",
      simplified: "百",
      traditional: "百",
    },
    {
      english: "Thousand",
      pinyin: "qiān",
      simplified: "千",
      traditional: "千",
    },
    {
      english: "First",
      pinyin: "dìyī",
      simplified: "第一",
      traditional: "第一",
    },
    {
      english: "One, a, an",
      pinyin: "gè",
      simplified: "个",
      traditional: "個",
    },
    {
      english: "Year",
      pinyin: "suì",
      simplified: "岁",
      traditional: "歲",
    },
    {
      english: "Volume",
      pinyin: "běn",
      simplified: "本",
      traditional: "本",
    },
    {
      english: "Some",
      pinyin: "xiē",
      simplified: "些",
      traditional: "些",
    },
    {
      english: "Piece, block, bit",
      pinyin: "kuài",
      simplified: "块",
      traditional: "塊",
    },
    {
      english: "Number",
      pinyin: "cì",
      simplified: "次",
      traditional: "次",
    },
    {
      english: "Kilogram",
      pinyin: "gōngjīn",
      simplified: "公斤",
      traditional: "公斤",
    },
    {
      english: "Yuan",
      pinyin: "yuán",
      simplified: "元",
      traditional: "元",
    },
    {
      english: "Piece, thing, fact, matter",
      pinyin: "jiàn",
      simplified: "件",
      traditional: "事",
    },
    {
      english: "Sheet",
      pinyin: "zhāng",
      simplified: "张",
      traditional: "張",
    },
    {
      english: "No, do not",
      pinyin: "bù",
      simplified: "不",
      traditional: "不",
    },
    {
      english: "No, not",
      pinyin: "méi",
      simplified: "没",
      traditional: "沒",
    },
    {
      english: "Quite, very",
      pinyin: "hěn",
      simplified: "很",
      traditional: "很",
    },
    {
      english: "Too",
      pinyin: "tài",
      simplified: "太",
      traditional: "太",
    },
    {
      english: "All",
      pinyin: "dōu",
      simplified: "都",
      traditional: "都",
    },
    {
      english: "Other",
      pinyin: "bié",
      simplified: "别",
      traditional: "別",
    },
    {
      english: "Very",
      pinyin: "fēicháng",
      simplified: "非常",
      traditional: "非常",
    },
    {
      english: "Likewise",
      pinyin: "yě",
      simplified: "也",
      traditional: "也",
    },
    {
      english: "Still",
      pinyin: "hái",
      simplified: "还",
      traditional: "還",
    },
    {
      english: "Most",
      pinyin: "zuì",
      simplified: "最",
      traditional: "最",
    },
    {
      english: "Real",
      pinyin: "zhēn",
      simplified: "真",
      traditional: "真",
    },
    {
      english: "Be being",
      pinyin: "zhèngzài",
      simplified: "正在",
      traditional: "正在",
    },
    {
      english: "Already",
      pinyin: "yǐjīng",
      simplified: "已经",
      traditional: "已經",
    },
    {
      english: "Together",
      pinyin: "yìqǐ",
      simplified: "一起",
      traditional: "一起",
    },
    {
      english: "Again",
      pinyin: "zài",
      simplified: "再",
      traditional: "再",
    },
    {
      english: "At once",
      pinyin: "jiǜ",
      simplified: "就",
      traditional: "就",
    },
    {
      english: "You",
      pinyin: "nín",
      simplified: "您",
      traditional: "您",
    },
    {
      english: "And",
      pinyin: "hé",
      simplified: "和",
      traditional: "和",
    },
    {
      english: "Because",
      pinyin: "yīnwèi",
      simplified: "因为",
      traditional: "因為",
    },
    {
      english: "So",
      pinyin: "suǒyǐ",
      simplified: "所以",
      traditional: "所以",
    },
    {
      english: "But",
      pinyin: "dànshì",
      simplified: "但是",
      traditional: "但是",
    },
    {
      english: "In, at",
      pinyin: "zài",
      simplified: "在",
      traditional: "在",
    },
    {
      english: "From",
      pinyin: "cóng",
      simplified: "从",
      traditional: "從",
    },
    {
      english: "Right",
      pinyin: "duì",
      simplified: "对",
      traditional: "對",
    },
    {
      english: "This",
      pinyin: "cǐ",
      simplified: "此",
      traditional: "此",
    },
    {
      english: "Towards",
      pinyin: "xiàng",
      simplified: "向",
      traditional: "向",
    },
    {
      english: "Leave",
      pinyin: "lí",
      simplified: "离",
      traditional: "離",
    },
    {
      english: "Hello",
      pinyin: "wèi",
      simplified: "喂",
      traditional: "餵",
    },
    {
      english: "Home",
      pinyin: "jiā",
      simplified: "家",
      traditional: "家",
    },
    {
      english: "School",
      pinyin: "xuéxiào",
      simplified: "学校",
      traditional: "學校",
    },
    {
      english: "Restaunt",
      pinyin: "fàndiàn",
      simplified: "饭馆",
      traditional: "飯館",
    },
    {
      english: "Store",
      pinyin: "shāngdiàn",
      simplified: "商店",
      traditional: "商店",
    },
    {
      english: "Hospital",
      pinyin: "yīyuàn",
      simplified: "医院",
      traditional: "醫院",
    },
    {
      english: "Train station",
      pinyin: "huǒchēzhàn",
      simplified: "火车站",
      traditional: "火車站",
    },
    {
      english: "China",
      pinyin: "Zhōngguó",
      simplified: "中国",
      traditional: "中國",
    },
    {
      english: "Airport",
      pinyin: "jīchǎng",
      simplified: "机场",
      traditional: "機場",
    },
    {
      english: "Classroom",
      pinyin: "jiàoshì",
      simplified: "教室",
      traditional: "教室",
    },
    {
      english: "Room",
      pinyin: "fángjiān",
      simplified: "房间",
      traditional: "房間",
    },
    {
      english: "Road",
      pinyin: "lù",
      simplified: "路",
      traditional: "路",
    },
    {
      english: "Beijing",
      pinyin: "Běijīng",
      simplified: "北京",
      traditional: "北京",
    },
    {
      english: "Up",
      pinyin: "shàng",
      simplified: "上",
      traditional: "上",
    },
    {
      english: "Below",
      pinyin: "xià",
      simplified: "下",
      traditional: "下",
    },
    {
      english: "Front",
      pinyin: "qiánmiàn",
      simplified: "前面",
      traditional: "前面",
    },
    {
      english: "Behind",
      pinyin: "hòumiàn",
      simplified: "后面",
      traditional: "後面",
    },
    {
      english: "Left",
      pinyin: "zuǒbiān",
      simplified: "左边",
      traditional: "左邊",
    },
    {
      english: "Right",
      pinyin: "yòubiān",
      simplified: "右边",
      traditional: "右邊",
    },
    {
      english: "Out",
      pinyin: "wài",
      simplified: "外",
      traditional: "外",
    },
    {
      english: "Side",
      pinyin: "pángbiān",
      simplified: "旁边",
      traditional: "旁邊",
    },
    {
      english: "Inside",
      pinyin: "lǐ",
      simplified: "里",
      traditional: "裡",
    },
    {
      english: "Today",
      pinyin: "jīntiān",
      simplified: "今天",
      traditional: "今天",
    },
    {
      english: "Tomorrow",
      pinyin: "míngtiān",
      simplified: "明天",
      traditional: "明天",
    },
    {
      english: "Yesterday",
      pinyin: "zuótiān",
      simplified: "昨天",
      traditional: "昨天",
    },
    {
      english: "Morning",
      pinyin: "shàngwǔ",
      simplified: "上午",
      traditional: "上午",
    },
    {
      english: "Noon",
      pinyin: "zhōngwǔ",
      simplified: "中午",
      traditional: "中午",
    },
    {
      english: "Afternoon",
      pinyin: "xiàwǔ",
      simplified: "下午",
      traditional: "下午",
    },
    {
      english: "Year",
      pinyin: "nián",
      simplified: "年",
      traditional: "年",
    },
    {
      english: "Month",
      pinyin: "yuè",
      simplified: "月",
      traditional: "月",
    },
    {
      english: "Day",
      pinyin: "rì",
      simplified: "日",
      traditional: "日",
    },
    {
      english: "Week",
      pinyin: "xīngqī",
      simplified: "星期",
      traditional: "星期",
    },
    {
      english: "Dot, spot",
      pinyin: "diǎn",
      simplified: "点",
      traditional: "點",
    },
    {
      english: "Minute",
      pinyin: "fēnzhōng",
      simplified: "分钟",
      traditional: "分鐘",
    },
    {
      english: "Now",
      pinyin: "xiànzài",
      simplified: "现在",
      traditional: "現在",
    },
    {
      english: "Time, moment",
      pinyin: "shíhou",
      simplified: "时候",
      traditional: "時候",
    },
    {
      english: "Morning, morrow",
      pinyin: "zǎoshàng",
      simplified: "早上",
      traditional: "早上",
    },
    {
      english: "Night",
      pinyin: "wǎnshàng",
      simplified: "晚上",
      traditional: "晚上",
    },
    {
      english: "Hour",
      pinyin: "xiǎoshí",
      simplified: "小时",
      traditional: "小時",
    },
    {
      english: "Time, period",
      pinyin: "shíjiān",
      simplified: "时间",
      traditional: "時間",
    },
    {
      english: "Last year",
      pinyin: "qùnián",
      simplified: "去年",
      traditional: "去年",
    },
    {
      english: "Number",
      pinyin: "hào",
      simplified: "号",
      traditional: "號",
    },
    {
      english: "Birthday",
      pinyin: "shēngrì",
      simplified: "生日",
      traditional: "生日",
    },
    {
      english: "Father",
      pinyin: "bàba",
      simplified: "爸爸",
      traditional: "爸爸",
    },
    {
      english: "Mother",
      pinyin: "māma",
      simplified: "妈妈",
      traditional: "媽媽",
    },
    {
      english: "Son",
      pinyin: "érzi",
      simplified: "儿子",
      traditional: "兒子",
    },
    {
      english: "Daughter",
      pinyin: "nǚ'ér",
      simplified: "女儿",
      traditional: "女兒",
    },
    {
      english: "Teacher",
      pinyin: "lǎoshī",
      simplified: "老师",
      traditional: "老師",
    },
    {
      english: "Student",
      pinyin: "xuéshēng",
      simplified: "学生",
      traditional: "學生",
    },
    {
      english: "Shoolmate",
      pinyin: "tóngxué",
      simplified: "同学",
      traditional: "同學",
    },
    {
      english: "Friend",
      pinyin: "péngyǒu",
      simplified: "朋友",
      traditional: "朋友",
    },
    {
      english: "Doctor",
      pinyin: "yīshēng",
      simplified: "医生",
      traditional: "醫生",
    },
    {
      english: "Sir",
      pinyin: "xiānsheng",
      simplified: "先生",
      traditional: "先生",
    },
    {
      english: "Miss",
      pinyin: "xiǎojiě",
      simplified: "小姐",
      traditional: "小姐",
    },
    {
      english: "Older brother",
      pinyin: "gēge",
      simplified: "哥哥",
      traditional: "哥哥",
    },
    {
      english: "Older sister",
      pinyin: "jiějie",
      simplified: "姐姐",
      traditional: "姐姐",
    },
    {
      english: "Younger brother",
      pinyin: "dìdi",
      simplified: "弟弟",
      traditional: "弟弟",
    },
    {
      english: "Younger sister",
      pinyin: "mèimei",
      simplified: "妹妹",
      traditional: "妹妹",
    },
    {
      english: "Husband",
      pinyin: "zhàngfu",
      simplified: "丈夫",
      traditional: "丈夫",
    },
    {
      english: "Wife",
      pinyin: "qīzi",
      simplified: "妻子",
      traditional: "妻子",
    },
    {
      english: "Child",
      pinyin: "háizi",
      simplified: "孩子",
      traditional: "孩子",
    },
    {
      english: "Man",
      pinyin: "nánrén",
      simplified: "男人",
      traditional: "男人",
    },
    {
      english: "Woman",
      pinyin: "nǚrén",
      simplified: "女人",
      traditional: "女人",
    },
    {
      english: "Waiter",
      pinyin: "fúwùyuán",
      simplified: "服务员",
      traditional: "服務員",
    },
    {
      english: "Cloth",
      pinyin: "yīfu",
      simplified: "衣服",
      traditional: "衣服",
    },
    {
      english: "Water",
      pinyin: "shuǐ",
      simplified: "水",
      traditional: "水",
    },
    {
      english: "Dish",
      pinyin: "cài",
      simplified: "菜",
      traditional: "菜",
    },
    {
      english: "Rice",
      pinyin: "mǐfàn",
      simplified: "米饭",
      traditional: "米飯",
    },
    {
      english: "Fruit",
      pinyin: "shuǐguǒ",
      simplified: "水果",
      traditional: "水果",
    },
    {
      english: "Apple",
      pinyin: "píngguǒ",
      simplified: "苹果",
      traditional: "蘋果",
    },
    {
      english: "Tea",
      pinyin: "chá",
      simplified: "茶",
      traditional: "茶",
    },
    {
      english: "Cup",
      pinyin: "bēizi",
      simplified: "杯子",
      traditional: "杯子",
    },
    {
      english: "Money",
      pinyin: "qián",
      simplified: "钱",
      traditional: "錢",
    },
    {
      english: "Airplane",
      pinyin: "fēijī",
      simplified: "飞机",
      traditional: "飛機",
    },
    {
      english: "Taxi",
      pinyin: "chūzūchē",
      simplified: "出租车",
      traditional: "出租車",
    },
    {
      english: "Television",
      pinyin: "diànshì",
      simplified: "电视",
      traditional: "電視",
    },
    {
      english: "Computer",
      pinyin: "diànnǎo",
      simplified: "电脑",
      traditional: "電腦",
    },
    {
      english: "Movie",
      pinyin: "diànyǐng",
      simplified: "电影",
      traditional: "電影",
    },
    {
      english: "Weather",
      pinyin: "tiānqì",
      simplified: "天气",
      traditional: "天氣",
    },
    {
      english: "Cat",
      pinyin: "māo",
      simplified: "猫",
      traditional: "貓",
    },
    {
      english: "Dog",
      pinyin: "gǒu",
      simplified: "狗",
      traditional: "狗",
    },
    {
      english: "Thing",
      pinyin: "dōngxi",
      simplified: "东西",
      traditional: "東西",
    },
    {
      english: "Fish",
      pinyin: "yú",
      simplified: "鱼",
      traditional: "魚",
    },
    {
      english: "Mutton",
      pinyin: "yángròu",
      simplified: "羊肉",
      traditional: "羊肉",
    },
    {
      english: "Milk",
      pinyin: "niúnǎi",
      simplified: "牛奶",
      traditional: "牛奶",
    },
    {
      english: "Egg",
      pinyin: "jīdàn",
      simplified: "鸡蛋",
      traditional: "雞蛋",
    },
    {
      english: "Watermelon",
      pinyin: "xīguā",
      simplified: "西瓜",
      traditional: "西瓜",
    },
    {
      english: "Coffee",
      pinyin: "kāfēi",
      simplified: "咖啡",
      traditional: "咖啡",
    },
    {
      english: "Bike",
      pinyin: "zìxíngchē",
      simplified: "自行车",
      traditional: "自行車",
    },
    {
      english: "Boat",
      pinyin: "chuán",
      simplified: "船",
      traditional: "船",
    },
    {
      english: "Snow",
      pinyin: "xuě",
      simplified: "雪",
      traditional: "雪",
    },
    {
      english: "Medicine",
      pinyin: "yào",
      simplified: "药",
      traditional: "藥",
    },
    {
      english: "Cellphone",
      pinyin: "shǒujī",
      simplified: "手机",
      traditional: "手機",
    },
    {
      english: "Watch",
      pinyin: "shǒubiǎo",
      simplified: "手表",
      traditional: "手錶",
    },
    {
      english: "Eye",
      pinyin: "yǎnjīng",
      simplified: "眼睛",
      traditional: "眼睛",
    },
    {
      english: "Body",
      pinyin: "shēntǐ",
      simplified: "身体",
      traditional: "身體",
    },
    {
      english: "Bus",
      pinyin: "gōnggòngqìchē",
      simplified: "公共汽车",
      traditional: "公共汽車",
    },
  ],
};

export default lesson1;
