import type HskList from "~/types/HskList";

const lesson4: HskList = {
  id: "aZuy5YQTO5",
  level: 4,
  words: [
    {
      simplified: "爱情",
      traditional: "愛情",
      pinyin: "àiqíng",
      english: "Love",
    },
    {
      simplified: "安排",
      traditional: "安排",
      pinyin: "ānpái",
      english: "Arrange",
    },
    {
      simplified: "安全",
      traditional: "安全",
      pinyin: "ānquán",
      english: "Security",
    },
    {
      simplified: "暗",
      traditional: "暗",
      pinyin: "àn",
      english: "Dark",
    },
    {
      simplified: "按时",
      traditional: "按時",
      pinyin: "ànshí",
      english: "On time",
    },
    {
      simplified: "按照",
      traditional: "按照",
      pinyin: "ànzhào",
      english: "According to",
    },
    {
      simplified: "包括",
      traditional: "包括",
      pinyin: "bāokuò",
      english: "Include",
    },
    {
      simplified: "保护",
      traditional: "保護",
      pinyin: "bǎohù",
      english: "Protect",
    },
    {
      simplified: "保证",
      traditional: "保證",
      pinyin: "bǎozhèng",
      english: "Ensure",
    },
    {
      simplified: "抱",
      traditional: "抱",
      pinyin: "bào",
      english: "Hold",
    },
    {
      simplified: "抱歉",
      traditional: "抱歉",
      pinyin: "bàoqiàn",
      english: "Feel sorry",
    },
    {
      simplified: "报道",
      traditional: "報導",
      pinyin: "bàodào",
      english: "Report",
    },
    {
      simplified: "报名",
      traditional: "報名",
      pinyin: "bàomíng",
      english: "Sign up",
    },
    {
      simplified: "倍",
      traditional: "倍",
      pinyin: "bèi",
      english: "Times",
    },
    {
      simplified: "本来",
      traditional: "本來",
      pinyin: "běnlái",
      english: "Originally",
    },
    {
      simplified: "笨",
      traditional: "笨",
      pinyin: "bèn",
      english: "Stupid",
    },
    {
      simplified: "笔记本",
      traditional: "筆記本",
      pinyin: "bǐjìběn",
      english: "Notebook",
    },
    {
      simplified: "毕业",
      traditional: "畢業",
      pinyin: "bìyè",
      english: "Graduation",
    },
    {
      simplified: "遍",
      traditional: "遍",
      pinyin: "biàn",
      english: "Times, all over",
    },
    {
      simplified: "标准",
      traditional: "標準",
      pinyin: "biāozhǔn",
      english: "Standard",
    },
    {
      simplified: "表达",
      traditional: "表達",
      pinyin: "biǎodá",
      english: "Expression",
    },
    {
      simplified: "表格",
      traditional: "表格",
      pinyin: "biǎogé",
      english: "Form",
    },
    {
      simplified: "表扬",
      traditional: "表揚",
      pinyin: "biǎoyáng",
      english: "Praise",
    },
    {
      simplified: "饼干",
      traditional: "餅乾",
      pinyin: "bǐnggān",
      english: "Biscuits",
    },
    {
      simplified: "并且",
      traditional: "並且",
      pinyin: "bìngqiě",
      english: "Also",
    },
    {
      simplified: "博士",
      traditional: "博士",
      pinyin: "bóshì",
      english: "Doctor",
    },
    {
      simplified: "不但",
      traditional: "不但",
      pinyin: "búdàn",
      english: "Not only",
    },
    {
      simplified: "不过",
      traditional: "不過",
      pinyin: "búguò",
      english: "However",
    },
    {
      simplified: "不得不",
      traditional: "不得不",
      pinyin: "bùdébù",
      english: "Have to",
    },
    {
      simplified: "不管",
      traditional: "不管",
      pinyin: "bùguǎn",
      english: "No matter",
    },
    {
      simplified: "不仅",
      traditional: "不僅",
      pinyin: "bùjǐn",
      english: "Not only",
    },
    {
      simplified: "部分",
      traditional: "部分",
      pinyin: "bùfen",
      english: "Part",
    },
    {
      simplified: "擦",
      traditional: "擦",
      pinyin: "cā",
      english: "Wipe",
    },
    {
      simplified: "猜",
      traditional: "猜",
      pinyin: "cāi",
      english: "Guess",
    },
    {
      simplified: "材料",
      traditional: "材料",
      pinyin: "cáiliào",
      english: "Material Science",
    },
    {
      simplified: "参观",
      traditional: "參觀",
      pinyin: "cānguān",
      english: "Visit",
    },
    {
      simplified: "差不多",
      traditional: "差不多",
      pinyin: "chàbuduō",
      english: "Almost",
    },
    {
      simplified: "尝",
      traditional: "嘗",
      pinyin: "cháng",
      english: "Taste",
    },
    {
      simplified: "长城",
      traditional: "長城",
      pinyin: "chángchéng",
      english: "The Great Wall",
    },
    {
      simplified: "长江",
      traditional: "長江",
      pinyin: "chángjiāng",
      english: "The Yangtze River",
    },
    {
      simplified: "场",
      traditional: "場",
      pinyin: "chǎng",
      english: "Site",
    },
    {
      simplified: "超过",
      traditional: "超過",
      pinyin: "chāoguò",
      english: "Exceed",
    },
    {
      simplified: "吵",
      traditional: "吵",
      pinyin: "chǎo",
      english: "Noisy",
    },
    {
      simplified: "成功",
      traditional: "成功",
      pinyin: "chénggōng",
      english: "Success",
    },
    {
      simplified: "成熟",
      traditional: "成熟",
      pinyin: "chéngshú",
      english: "Mature",
    },
    {
      simplified: "成为",
      traditional: "成為",
      pinyin: "chéngwéi",
      english: "Become",
    },
    {
      simplified: "诚实",
      traditional: "誠實",
      pinyin: "chéngshí",
      english: "Honest",
    },
    {
      simplified: "乘坐",
      traditional: "乘坐",
      pinyin: "chéngzuò",
      english: "Ride",
    },
    {
      simplified: "吃惊",
      traditional: "吃驚",
      pinyin: "chījīng",
      english: "Be amazed",
    },
    {
      simplified: "重新",
      traditional: "重新",
      pinyin: "chóngxīn",
      english: "Again",
    },
    {
      simplified: "抽烟",
      traditional: "抽煙",
      pinyin: "chōuyān",
      english: "Smoking",
    },
    {
      simplified: "出差",
      traditional: "出差",
      pinyin: "chūchāi",
      english: "A business travel",
    },
    {
      simplified: "出发",
      traditional: "出發",
      pinyin: "chūfā",
      english: "Set out",
    },
    {
      simplified: "出生",
      traditional: "出生",
      pinyin: "chūshēng",
      english: "Birth",
    },
    {
      simplified: "传真",
      traditional: "傳真",
      pinyin: "chuánzhēn",
      english: "Fax",
    },
    {
      simplified: "窗户",
      traditional: "窗戶",
      pinyin: "chuānghu",
      english: "Window",
    },
    {
      simplified: "词典",
      traditional: "詞典",
      pinyin: "cídiǎn",
      english: "Dictionary",
    },
    {
      simplified: "从来",
      traditional: "從來",
      pinyin: "cónglái",
      english: "Always",
    },
    {
      simplified: "粗心",
      traditional: "粗心",
      pinyin: "cūxīn",
      english: "Careless",
    },
    {
      simplified: "答案",
      traditional: "答案",
      pinyin: "dá'àn",
      english: "Answer",
    },
    {
      simplified: "打扮",
      traditional: "打扮",
      pinyin: "dǎban",
      english: "Dress up",
    },
    {
      simplified: "打扰",
      traditional: "打擾",
      pinyin: "dǎrǎo",
      english: "Disturb",
    },
    {
      simplified: "打印",
      traditional: "打印",
      pinyin: "dǎyìn",
      english: "Print",
    },
    {
      simplified: "打折",
      traditional: "打折",
      pinyin: "dǎzhé",
      english: "Discount",
    },
    {
      simplified: "打针",
      traditional: "打針",
      pinyin: "dǎzhēn",
      english: "To make an injection",
    },
    {
      simplified: "大概",
      traditional: "大概",
      pinyin: "dàgài",
      english: "Probably",
    },
    {
      simplified: "大使馆",
      traditional: "大使館",
      pinyin: "dàshǐguǎn",
      english: "Embassy",
    },
    {
      simplified: "大约",
      traditional: "大約",
      pinyin: "dàyuē",
      english: "About",
    },
    {
      simplified: "戴",
      traditional: "戴",
      pinyin: "dài",
      english: "Wear",
    },
    {
      simplified: "代表",
      traditional: "代表",
      pinyin: "dàibiǎo",
      english: "Representative",
    },
    {
      simplified: "代替",
      traditional: "代替",
      pinyin: "dàitì",
      english: "Replace",
    },
    {
      simplified: "大夫",
      traditional: "大夫",
      pinyin: "dàifu",
      english: "Doctor",
    },
    {
      simplified: "当",
      traditional: "當",
      pinyin: "dāng",
      english: "When",
    },
    {
      simplified: "当地",
      traditional: "當地",
      pinyin: "dāngdì",
      english: "Local",
    },
    {
      simplified: "当时",
      traditional: "當時",
      pinyin: "dāngshí",
      english: "At that time",
    },
    {
      simplified: "刀",
      traditional: "刀",
      pinyin: "dāo",
      english: "Knife",
    },
    {
      simplified: "导游",
      traditional: "導遊",
      pinyin: "dǎoyóu",
      english: "Guide",
    },
    {
      simplified: "到处",
      traditional: "到處",
      pinyin: "dàochù",
      english: "Everywhere",
    },
    {
      simplified: "到底",
      traditional: "到底",
      pinyin: "dàodǐ",
      english: "To the end",
    },
    {
      simplified: "道歉",
      traditional: "道歉",
      pinyin: "dàoqiàn",
      english: "Apologize",
    },
    {
      simplified: "得意",
      traditional: "擅長",
      pinyin: "déyì",
      english: "Proud",
    },
    {
      simplified: "得",
      traditional: "得",
      pinyin: "děi",
      english: "Have to",
    },
    {
      simplified: "底",
      traditional: "底",
      pinyin: "dǐ",
      english: "Bottom",
    },
    {
      simplified: "地球",
      traditional: "地球",
      pinyin: "dìqiú",
      english: "Earth",
    },
    {
      simplified: "地址",
      traditional: "地址",
      pinyin: "dìzhǐ",
      english: "Address",
    },
    {
      simplified: "掉",
      traditional: "掉",
      pinyin: "diào",
      english: "Fall",
    },
    {
      simplified: "调查",
      traditional: "調查",
      pinyin: "diàochá",
      english: "Investigation",
    },
    {
      simplified: "丢",
      traditional: "丟",
      pinyin: "diū",
      english: "Lose",
    },
    {
      simplified: "动作",
      traditional: "動作",
      pinyin: "dòngzuò",
      english: "Action",
    },
    {
      simplified: "堵车",
      traditional: "堵車",
      pinyin: "dǔchē",
      english: "Traffic jam",
    },
    {
      simplified: "肚子",
      traditional: "肚子",
      pinyin: "dùzi",
      english: "Belly",
    },
    {
      simplified: "断",
      traditional: "斷",
      pinyin: "duàn",
      english: "Break",
    },
    {
      simplified: "对话",
      traditional: "對話",
      pinyin: "duìhuà",
      english: "Dialogue",
    },
    {
      simplified: "对面",
      traditional: "對面",
      pinyin: "duìmiàn",
      english: "Opposite side",
    },
    {
      simplified: "顿",
      traditional: "頓",
      pinyin: "dùn",
      english: "Meal",
    },
    {
      simplified: "朵",
      traditional: "朵",
      pinyin: "duǒ",
      english: "Classifier of flower",
    },
    {
      simplified: "而",
      traditional: "而",
      pinyin: "ér",
      english: "And",
    },
    {
      simplified: "儿童",
      traditional: "兒童",
      pinyin: "értóng",
      english: "Children",
    },
    {
      simplified: "发",
      traditional: "發",
      pinyin: "fā",
      english: "Send out",
    },
    {
      simplified: "发生",
      traditional: "發生",
      pinyin: "fāshēng",
      english: "Happen",
    },
    {
      simplified: "发展",
      traditional: "發展",
      pinyin: "fāzhǎn",
      english: "Development",
    },
    {
      simplified: "法律",
      traditional: "法律",
      pinyin: "fǎlǜ",
      english: "Law",
    },
    {
      simplified: "翻译",
      traditional: "翻譯",
      pinyin: "fānyì",
      english: "Translate",
    },
    {
      simplified: "烦恼",
      traditional: "煩惱",
      pinyin: "fánnǎo",
      english: "Annoyance",
    },
    {
      simplified: "反对",
      traditional: "反對",
      pinyin: "fǎnduì",
      english: "Opposition",
    },
    {
      simplified: "反映",
      traditional: "反映",
      pinyin: "fǎnyìng",
      english: "Reflect",
    },
    {
      simplified: "范围",
      traditional: "範圍",
      pinyin: "fànwéi",
      english: "Range",
    },
    {
      simplified: "方法",
      traditional: "方法",
      pinyin: "fāngfǎ",
      english: "Method",
    },
    {
      simplified: "方面",
      traditional: "方面",
      pinyin: "fāngmiàn",
      english: "Aspect",
    },
    {
      simplified: "方向",
      traditional: "方向",
      pinyin: "fāngxiàng",
      english: "Direction",
    },
    {
      simplified: "访问",
      traditional: "訪問",
      pinyin: "fǎngwèn",
      english: "Visit",
    },
    {
      simplified: "放弃",
      traditional: "放棄",
      pinyin: "fàngqì",
      english: "Give up",
    },
    {
      simplified: "放暑假",
      traditional: "放暑假",
      pinyin: "fàngshǔjià",
      english: "Summer vacation",
    },
    {
      simplified: "分之",
      traditional: "分之",
      pinyin: "fēnzhī",
      english: "Percent",
    },
    {
      simplified: "份",
      traditional: "份",
      pinyin: "fèn",
      english: "Share (measure word)",
    },
    {
      simplified: "丰富",
      traditional: "豐富",
      pinyin: "fēngfù",
      english: "Rich, plentiful, abundant",
    },
    {
      simplified: "风景",
      traditional: "風景",
      pinyin: "fēngjǐng",
      english: "Scenery",
    },
    {
      simplified: "否则",
      traditional: "否則",
      pinyin: "fǒuzé",
      english: "Otherwise",
    },
    {
      simplified: "符合",
      traditional: "符合",
      pinyin: "fúhé",
      english: "Accord with",
    },
    {
      simplified: "富",
      traditional: "富",
      pinyin: "fù",
      english: "Rich",
    },
    {
      simplified: "父亲",
      traditional: "父親",
      pinyin: "fùqīn",
      english: "Father",
    },
    {
      simplified: "复印",
      traditional: "複印",
      pinyin: "fùyìn",
      english: "To copy",
    },
    {
      simplified: "复杂",
      traditional: "複雜",
      pinyin: "fùzá",
      english: "Complex",
    },
    {
      simplified: "负责",
      traditional: "負責",
      pinyin: "fùzé",
      english: "Be responsible for",
    },
    {
      simplified: "改变",
      traditional: "改變",
      pinyin: "gǎibiàn",
      english: "Change",
    },
    {
      simplified: "干杯",
      traditional: "乾杯",
      pinyin: "gānbēi",
      english: "Cheers!",
    },
    {
      simplified: "干燥",
      traditional: "乾燥",
      pinyin: "gānzào",
      english: "Dry, arid, dull",
    },
    {
      simplified: "感动",
      traditional: "感動",
      pinyin: "gǎndòng",
      english: "Be moved",
    },
    {
      simplified: "感觉",
      traditional: "感覺",
      pinyin: "gǎnjué",
      english: "Feel",
    },
    {
      simplified: "感情",
      traditional: "感情",
      pinyin: "gǎnqíng",
      english: "Feeling",
    },
    {
      simplified: "感谢",
      traditional: "感謝",
      pinyin: "gǎnxiè",
      english: "Thank",
    },
    {
      simplified: "干",
      traditional: "幹",
      pinyin: "gān",
      english: "Dry",
    },
    {
      simplified: "刚刚",
      traditional: "剛剛",
      pinyin: "gānggāng",
      english: "Just",
    },
    {
      simplified: "高级",
      traditional: "高級",
      pinyin: "gāojí",
      english: "Senior",
    },
    {
      simplified: "各",
      traditional: "各",
      pinyin: "gè",
      english: "Various",
    },
    {
      simplified: "个子",
      traditional: "個子",
      pinyin: "gèzi",
      english: "Height",
    },
    {
      simplified: "公里",
      traditional: "公里",
      pinyin: "gōnglǐ",
      english: "Kilometre",
    },
    {
      simplified: "工具",
      traditional: "工具",
      pinyin: "gōngjù",
      english: "Tool",
    },
    {
      simplified: "工资",
      traditional: "工資",
      pinyin: "gōngzī",
      english: "Wages",
    },
    {
      simplified: "共同",
      traditional: "共同",
      pinyin: "gòngtóng",
      english: "Common",
    },
    {
      simplified: "够",
      traditional: "夠",
      pinyin: "gòu",
      english: "Enough",
    },
    {
      simplified: "购物",
      traditional: "購物",
      pinyin: "gòuwù",
      english: "Shopping",
    },
    {
      simplified: "孤单",
      traditional: "孤單",
      pinyin: "gūdān",
      english: "Alone",
    },
    {
      simplified: "估计",
      traditional: "估計",
      pinyin: "gūjì",
      english: "Estimate",
    },
    {
      simplified: "鼓励",
      traditional: "鼓勵",
      pinyin: "gǔlì",
      english: "Encourage",
    },
    {
      simplified: "鼓掌",
      traditional: "鼓掌",
      pinyin: "gǔzhǎng",
      english: "Applause",
    },
    {
      simplified: "顾客",
      traditional: "顧客",
      pinyin: "gùkè",
      english: "Customer",
    },
    {
      simplified: "故意",
      traditional: "故意",
      pinyin: "gùyì",
      english: "Deliberately",
    },
    {
      simplified: "挂",
      traditional: "掛",
      pinyin: "guà",
      english: "Hang",
    },
    {
      simplified: "关键",
      traditional: "關鍵",
      pinyin: "guānjiàn",
      english: "Key",
    },
    {
      simplified: "观众",
      traditional: "觀眾",
      pinyin: "guānzhòng",
      english: "Audience",
    },
    {
      simplified: "管理",
      traditional: "管理",
      pinyin: "guǎnlǐ",
      english: "Administration",
    },
    {
      simplified: "光",
      traditional: "光",
      pinyin: "guāng",
      english: "Light",
    },
    {
      simplified: "广播",
      traditional: "廣播",
      pinyin: "guǎngbō",
      english: "Radio broadcast",
    },
    {
      simplified: "广告",
      traditional: "廣告",
      pinyin: "guǎnggào",
      english: "Advertisement",
    },
    {
      simplified: "逛",
      traditional: "逛",
      pinyin: "guàng",
      english: "Stroll",
    },
    {
      simplified: "规定",
      traditional: "規定",
      pinyin: "guīdìng",
      english: "Regulations",
    },
    {
      simplified: "国际",
      traditional: "國際",
      pinyin: "guójì",
      english: "International",
    },
    {
      simplified: "果然",
      traditional: "果然",
      pinyin: "guǒrán",
      english: "Sure enough",
    },
    {
      simplified: "过程",
      traditional: "過程",
      pinyin: "guòchéng",
      english: "Process",
    },
    {
      simplified: "海洋",
      traditional: "海洋",
      pinyin: "hǎiyáng",
      english: "Ocean",
    },
    {
      simplified: "害羞",
      traditional: "害羞",
      pinyin: "hàixiū",
      english: "Shy",
    },
    {
      simplified: "寒假",
      traditional: "寒假",
      pinyin: "hánjià",
      english: "The winter vacation",
    },
    {
      simplified: "汗",
      traditional: "汗",
      pinyin: "hàn",
      english: "Sweat",
    },
    {
      simplified: "航班",
      traditional: "航班",
      pinyin: "hángbān",
      english: "Flight",
    },
    {
      simplified: "好处",
      traditional: "好處",
      pinyin: "hǎochù",
      english: "Benefit",
    },
    {
      simplified: "好像",
      traditional: "好像",
      pinyin: "hǎoxiàng",
      english: "Be like, seem",
    },
    {
      simplified: "号码",
      traditional: "號碼",
      pinyin: "hàomǎ",
      english: "Number, size",
    },
    {
      simplified: "合格",
      traditional: "合格",
      pinyin: "hégé",
      english: "Qualified",
    },
    {
      simplified: "合适",
      traditional: "合適",
      pinyin: "héshì",
      english: "Appropriate",
    },
    {
      simplified: "盒子",
      traditional: "盒子",
      pinyin: "hézi",
      english: "Box",
    },
    {
      simplified: "猴子",
      traditional: "猴子",
      pinyin: "hóuzi",
      english: "Monkey",
    },
    {
      simplified: "厚",
      traditional: "厚",
      pinyin: "hòu",
      english: "Thick",
    },
    {
      simplified: "后悔",
      traditional: "後悔",
      pinyin: "hòuhuǐ",
      english: "Regret",
    },
    {
      simplified: "后来",
      traditional: "後來",
      pinyin: "hòulái",
      english: "Later",
    },
    {
      simplified: "忽然",
      traditional: "忽然",
      pinyin: "hūrán",
      english: "Suddenly",
    },
    {
      simplified: "护士",
      traditional: "護士",
      pinyin: "hùshi",
      english: "Nurse",
    },
    {
      simplified: "互相",
      traditional: "互相",
      pinyin: "hùxiāng",
      english: "Each other",
    },
    {
      simplified: "怀疑",
      traditional: "懷疑",
      pinyin: "huáiyí",
      english: "Doubt",
    },
    {
      simplified: "回忆",
      traditional: "回憶",
      pinyin: "huíyì",
      english: "Memory",
    },
    {
      simplified: "活动",
      traditional: "活動",
      pinyin: "huódòng",
      english: "Activity",
    },
    {
      simplified: "活泼",
      traditional: "活潑",
      pinyin: "huópō",
      english: "Lively",
    },
    {
      simplified: "火",
      traditional: "火",
      pinyin: "huǒ",
      english: "Fire",
    },
    {
      simplified: "获得",
      traditional: "獲得",
      pinyin: "huòdé",
      english: "Get",
    },
    {
      simplified: "基础",
      traditional: "基礎",
      pinyin: "jīchǔ",
      english: "Basics",
    },
    {
      simplified: "激动",
      traditional: "激動",
      pinyin: "jīdòng",
      english: "Excited",
    },
    {
      simplified: "积极",
      traditional: "積極",
      pinyin: "jījí",
      english: "Positive",
    },
    {
      simplified: "积累",
      traditional: "積累",
      pinyin: "jīlěi",
      english: "Accumulation",
    },
    {
      simplified: "极其",
      traditional: "極其",
      pinyin: "jíqí",
      english: "Extremely",
    },
    {
      simplified: "集合",
      traditional: "集合",
      pinyin: "jíhé",
      english: "Aggregate",
    },
    {
      simplified: "及时",
      traditional: "及時",
      pinyin: "jíshí",
      english: "Timely",
    },
    {
      simplified: "即使",
      traditional: "即使",
      pinyin: "jíshǐ",
      english: "Even if",
    },
    {
      simplified: "寄",
      traditional: "寄",
      pinyin: "jì",
      english: "Send",
    },
    {
      simplified: "记者",
      traditional: "記者",
      pinyin: "jìzhě",
      english: "Reporter",
    },
    {
      simplified: "计划",
      traditional: "計劃",
      pinyin: "jìhuà",
      english: "Plan",
    },
    {
      simplified: "既然",
      traditional: "既然",
      pinyin: "jìrán",
      english: "Although",
    },
    {
      simplified: "技术",
      traditional: "技術",
      pinyin: "jìshù",
      english: "Technology",
    },
    {
      simplified: "继续",
      traditional: "繼續",
      pinyin: "jìxù",
      english: "Continue",
    },
    {
      simplified: "家具",
      traditional: "家具",
      pinyin: "jiājù",
      english: "Furniture",
    },
    {
      simplified: "加班",
      traditional: "加班",
      pinyin: "jiābān",
      english: "Overtime work",
    },
    {
      simplified: "加油站",
      traditional: "加油站",
      pinyin: "jiāyóuzhàn",
      english: "Gas station",
    },
    {
      simplified: "假",
      traditional: "假",
      pinyin: "jiǎ",
      english: "False",
    },
    {
      simplified: "价格",
      traditional: "價格",
      pinyin: "jiàgé",
      english: "Price",
    },
    {
      simplified: "坚持",
      traditional: "堅持",
      pinyin: "jiānchí",
      english: "Insist",
    },
    {
      simplified: "减肥",
      traditional: "減肥",
      pinyin: "jiǎnféi",
      english: "Reduce weight",
    },
    {
      simplified: "减少",
      traditional: "減少",
      pinyin: "jiǎnshǎo",
      english: "Reduce",
    },
    {
      simplified: "将来",
      traditional: "未來",
      pinyin: "jiānglái",
      english: "Future",
    },
    {
      simplified: "奖金",
      traditional: "獎金",
      pinyin: "jiǎngjīn",
      english: "Bonus",
    },
    {
      simplified: "降低",
      traditional: "降低",
      pinyin: "jiàngdī",
      english: "Reduce, cut down",
    },
    {
      simplified: "交",
      traditional: "交",
      pinyin: "jiāo",
      english: "Hand over",
    },
    {
      simplified: "交流",
      traditional: "交流",
      pinyin: "jiāoliú",
      english: "Communication",
    },
    {
      simplified: "交通",
      traditional: "交通",
      pinyin: "jiāotōng",
      english: "Traffic",
    },
    {
      simplified: "骄傲",
      traditional: "驕傲",
      pinyin: "jiāo'ào",
      english: "Proud",
    },
    {
      simplified: "饺子",
      traditional: "餃子",
      pinyin: "jiǎozi",
      english: "Dumplings",
    },
    {
      simplified: "教授",
      traditional: "教授",
      pinyin: "jiàoshòu",
      english: "Professor",
    },
    {
      simplified: "教育",
      traditional: "教育",
      pinyin: "jiàoyù",
      english: "Education",
    },
    {
      simplified: "接受",
      traditional: "接受",
      pinyin: "jiēshòu",
      english: "Accept",
    },
    {
      simplified: "结果",
      traditional: "結果",
      pinyin: "jiéguǒ",
      english: "Result",
    },
    {
      simplified: "节约",
      traditional: "節約",
      pinyin: "jiéyuē",
      english: "Save",
    },
    {
      simplified: "解释",
      traditional: "解釋",
      pinyin: "jiěshì",
      english: "Explain",
    },
    {
      simplified: "尽管",
      traditional: "儘管",
      pinyin: "jǐnguǎn",
      english: "Although",
    },
    {
      simplified: "紧张",
      traditional: "緊張",
      pinyin: "jǐnzhāng",
      english: "Nervous",
    },
    {
      simplified: "进行",
      traditional: "進行",
      pinyin: "jìnxíng",
      english: "In process of",
    },
    {
      simplified: "禁止",
      traditional: "禁止",
      pinyin: "jìnzhǐ",
      english: "Prohibit",
    },
    {
      simplified: "精彩",
      traditional: "精彩",
      pinyin: "jīngcǎi",
      english: "Marvellous",
    },
    {
      simplified: "精神",
      traditional: "精神",
      pinyin: "jīngshén",
      english: "Spirit",
    },
    {
      simplified: "经济",
      traditional: "經濟",
      pinyin: "jīngjì",
      english: "Economics",
    },
    {
      simplified: "经验",
      traditional: "經驗",
      pinyin: "jīngyàn",
      english: "Experience",
    },
    {
      simplified: "京剧",
      traditional: "京劇",
      pinyin: "jīngjù",
      english: "Beijing opera",
    },
    {
      simplified: "警察",
      traditional: "警察",
      pinyin: "jǐngchá",
      english: "Policeman",
    },
    {
      simplified: "竟然",
      traditional: "竟然",
      pinyin: "jìngrán",
      english: "Unexpectedly",
    },
    {
      simplified: "竞争",
      traditional: "競爭",
      pinyin: "jìngzhēng",
      english: "Compete",
    },
    {
      simplified: "镜子",
      traditional: "鏡子",
      pinyin: "jìngzi",
      english: "Mirror",
    },
    {
      simplified: "究竟",
      traditional: "究竟",
      pinyin: "jiūjìng",
      english: "Exactly",
    },
    {
      simplified: "举办",
      traditional: "舉辦",
      pinyin: "jǔbàn",
      english: "Hold",
    },
    {
      simplified: "拒绝",
      traditional: "拒絕",
      pinyin: "jùjué",
      english: "Refuse",
    },
    {
      simplified: "距离",
      traditional: "距離",
      pinyin: "jùlí",
      english: "Distance",
    },
    {
      simplified: "开玩笑",
      traditional: "開玩笑",
      pinyin: "kāiwánxiào",
      english: "Make fun of",
    },
    {
      simplified: "看法",
      traditional: "看法",
      pinyin: "kànfǎ",
      english: "View",
    },
    {
      simplified: "考虑",
      traditional: "考慮",
      pinyin: "kǎolǜ",
      english: "Consider",
    },
    {
      simplified: "棵",
      traditional: "棵",
      pinyin: "kē",
      english: "Tree (measure word)",
    },
    {
      simplified: "科学",
      traditional: "科學",
      pinyin: "kēxué",
      english: "Science",
    },
    {
      simplified: "咳嗽",
      traditional: "咳嗽",
      pinyin: "késou",
      english: "Cough",
    },
    {
      simplified: "可怜",
      traditional: "可憐",
      pinyin: "kělián",
      english: "Poor",
    },
    {
      simplified: "可是",
      traditional: "可是",
      pinyin: "kěshì",
      english: "However",
    },
    {
      simplified: "可惜",
      traditional: "可惜",
      pinyin: "kěxī",
      english: "Unfortunately",
    },
    {
      simplified: "肯定",
      traditional: "肯定",
      pinyin: "kěndìng",
      english: "Sure",
    },
    {
      simplified: "空气",
      traditional: "空氣",
      pinyin: "kōngqì",
      english: "Air",
    },
    {
      simplified: "恐怕",
      traditional: "恐怕",
      pinyin: "kǒngpà",
      english: "I'm afraid",
    },
    {
      simplified: "苦",
      traditional: "苦",
      pinyin: "kǔ",
      english: "Bitter",
    },
    {
      simplified: "宽",
      traditional: "寬",
      pinyin: "kuān",
      english: "Wide",
    },
    {
      simplified: "困",
      traditional: "困",
      pinyin: "kùn",
      english: "Sleepy",
    },
    {
      simplified: "困难",
      traditional: "困難",
      pinyin: "kùnnan",
      english: "Difficulty",
    },
    {
      simplified: "扩大",
      traditional: "擴大",
      pinyin: "kuòdà",
      english: "Expand",
    },
    {
      simplified: "拉",
      traditional: "拉",
      pinyin: "lā",
      english: "Pull",
    },
    {
      simplified: "垃圾桶",
      traditional: "垃圾桶",
      pinyin: "lājītǒng",
      english: "Trash",
    },
    {
      simplified: "辣",
      traditional: "辣",
      pinyin: "là",
      english: "Spicy",
    },
    {
      simplified: "来不及",
      traditional: "來不及",
      pinyin: "láibují",
      english: "There's not enough time",
    },
    {
      simplified: "来得及",
      traditional: "來得及",
      pinyin: "láidejí",
      english: "In time",
    },
    {
      simplified: "懒",
      traditional: "懶",
      pinyin: "lǎn",
      english: "Lazy",
    },
    {
      simplified: "浪费",
      traditional: "浪費",
      pinyin: "làngfèi",
      english: "Waste",
    },
    {
      simplified: "浪漫",
      traditional: "浪漫",
      pinyin: "làngmàn",
      english: "Romantic",
    },
    {
      simplified: "老虎",
      traditional: "老虎",
      pinyin: "lǎohǔ",
      english: "Tiger",
    },
    {
      simplified: "冷静",
      traditional: "冷靜",
      pinyin: "lěngjìng",
      english: "Calm down",
    },
    {
      simplified: "理发",
      traditional: "理髮",
      pinyin: "lǐfà",
      english: "Haircut",
    },
    {
      simplified: "理解",
      traditional: "理解",
      pinyin: "lǐjiě",
      english: "Understand",
    },
    {
      simplified: "理想",
      traditional: "理想",
      pinyin: "lǐxiǎng",
      english: "Ideal",
    },
    {
      simplified: "礼貌",
      traditional: "禮貌",
      pinyin: "lǐmào",
      english: "Politeness",
    },
    {
      simplified: "厉害",
      traditional: "厲害",
      pinyin: "lìhai",
      english: "Fierce",
    },
    {
      simplified: "经历",
      traditional: "經歷",
      pinyin: "jīnglì",
      english: "Experience, skill",
    },
    {
      simplified: "力气",
      traditional: "力氣",
      pinyin: "lìqi",
      english: "Strength",
    },
    {
      simplified: "例如",
      traditional: "例如",
      pinyin: "lìrú",
      english: "For example",
    },
    {
      simplified: "俩",
      traditional: "倆",
      pinyin: "liǎ",
      english: "Two",
    },
    {
      simplified: "连",
      traditional: "連",
      pinyin: "lián",
      english: "Even",
    },
    {
      simplified: "联系",
      traditional: "聯繫",
      pinyin: "liánxì",
      english: "Contact",
    },
    {
      simplified: "凉快",
      traditional: "涼快",
      pinyin: "liángkuai",
      english: "Pleasantly cool",
    },
    {
      simplified: "亮",
      traditional: "亮",
      pinyin: "liàng",
      english: "Bright",
    },
    {
      simplified: "聊天",
      traditional: "聊天",
      pinyin: "liáotiān",
      english: "Chat",
    },
    {
      simplified: "另外",
      traditional: "另外",
      pinyin: "lìngwài",
      english: "In addition",
    },
    {
      simplified: "留",
      traditional: "留",
      pinyin: "liú",
      english: "Stay",
    },
    {
      simplified: "留学",
      traditional: "留學",
      pinyin: "liúxué",
      english: "Overseas Study",
    },
    {
      simplified: "流泪",
      traditional: "流淚",
      pinyin: "liúlèi",
      english: "Shed tears",
    },
    {
      simplified: "流利",
      traditional: "流利",
      pinyin: "liúlì",
      english: "Fluent",
    },
    {
      simplified: "流行",
      traditional: "流行",
      pinyin: "liúxíng",
      english: "Popular",
    },
    {
      simplified: "乱",
      traditional: "亂",
      pinyin: "luàn",
      english: "Chaos",
    },
    {
      simplified: "律师",
      traditional: "律師",
      pinyin: "lǜshī",
      english: "Lawyer",
    },
    {
      simplified: "麻烦",
      traditional: "麻煩",
      pinyin: "máfan",
      english: "Trouble",
    },
    {
      simplified: "马虎",
      traditional: "馬虎",
      pinyin: "mǎhu",
      english: "Careless",
    },
    {
      simplified: "满",
      traditional: "滿",
      pinyin: "mǎn",
      english: "Full",
    },
    {
      simplified: "毛巾",
      traditional: "毛巾",
      pinyin: "máojīn",
      english: "Towel",
    },
    {
      simplified: "美丽",
      traditional: "美麗",
      pinyin: "měilì",
      english: "Beautiful",
    },
    {
      simplified: "梦",
      traditional: "夢",
      pinyin: "mèng",
      english: "Dream",
    },
    {
      simplified: "密码",
      traditional: "密碼",
      pinyin: "mìmǎ",
      english: "Password",
    },
    {
      simplified: "免费",
      traditional: "免費",
      pinyin: "miǎnfèi",
      english: "Free of charge",
    },
    {
      simplified: "民族",
      traditional: "民族",
      pinyin: "mínzú",
      english: "Nation",
    },
    {
      simplified: "母亲",
      traditional: "母親",
      pinyin: "mǔqīn",
      english: "Mother",
    },
    {
      simplified: "目的",
      traditional: "目的",
      pinyin: "mùdì",
      english: "Objective",
    },
    {
      simplified: "耐心",
      traditional: "耐心",
      pinyin: "nàixīn",
      english: "Patience",
    },
    {
      simplified: "难道",
      traditional: "難道",
      pinyin: "nándào",
      english: "Could it be said that...",
    },
    {
      simplified: "难受",
      traditional: "難受",
      pinyin: "nánshòu",
      english: "Uncomfortable",
    },
    {
      simplified: "内",
      traditional: "內",
      pinyin: "nèi",
      english: "Within",
    },
    {
      simplified: "内容",
      traditional: "內容",
      pinyin: "nèiróng",
      english: "Content",
    },
    {
      simplified: "能力",
      traditional: "能力",
      pinyin: "nénglì",
      english: "Ability",
    },
    {
      simplified: "年龄",
      traditional: "年齡",
      pinyin: "niánlíng",
      english: "Age",
    },
    {
      simplified: "农村",
      traditional: "農村",
      pinyin: "nóngcūn",
      english: "Countryside",
    },
    {
      simplified: "弄",
      traditional: "弄",
      pinyin: "nòng",
      english: "Get, make",
    },
    {
      simplified: "暖和",
      traditional: "暖和",
      pinyin: "nuǎnhuo",
      english: "Warm",
    },
    {
      simplified: "偶尔",
      traditional: "偶爾",
      pinyin: "ǒu'ěr",
      english: "Occasionally",
    },
    {
      simplified: "排列",
      traditional: "排列",
      pinyin: "páiliè",
      english: "Array",
    },
    {
      simplified: "判断",
      traditional: "判斷",
      pinyin: "pànduàn",
      english: "Judge",
    },
    {
      simplified: "陪",
      traditional: "陪",
      pinyin: "péi",
      english: "Accompany",
    },
    {
      simplified: "批评",
      traditional: "批評",
      pinyin: "pīpíng",
      english: "Criticism",
    },
    {
      simplified: "皮肤",
      traditional: "皮膚",
      pinyin: "pífū",
      english: "Skin",
    },
    {
      simplified: "脾气",
      traditional: "脾氣",
      pinyin: "píqi",
      english: "Bad temper",
    },
    {
      simplified: "篇",
      traditional: "篇",
      pinyin: "piān",
      english: "Piece",
    },
    {
      simplified: "骗",
      traditional: "騙",
      pinyin: "piàn",
      english: "Fool",
    },
    {
      simplified: "乒乓球",
      traditional: "乒乓球",
      pinyin: "pīngpāngqiú",
      english: "Table Tennis",
    },
    {
      simplified: "平时",
      traditional: "平時",
      pinyin: "píngshí",
      english: "Peacetime",
    },
    {
      simplified: "瓶子",
      traditional: "瓶子",
      pinyin: "píngzi",
      english: "Bottle",
    },
    {
      simplified: "破",
      traditional: "破",
      pinyin: "pò",
      english: "Broken",
    },
    {
      simplified: "普遍",
      traditional: "普遍",
      pinyin: "pǔbiàn",
      english: "Universal",
    },
    {
      simplified: "其次",
      traditional: "其次",
      pinyin: "qícì",
      english: "Secondly",
    },
    {
      simplified: "其中",
      traditional: "其中",
      pinyin: "qízhōng",
      english: "Among",
    },
    {
      simplified: "起飞",
      traditional: "起飛",
      pinyin: "qǐfēi",
      english: "Take off",
    },
    {
      simplified: "起来",
      traditional: "起來",
      pinyin: "qǐlái",
      english: "Get up",
    },
    {
      simplified: "气候",
      traditional: "氣候",
      pinyin: "qìhòu",
      english: "Climate",
    },
    {
      simplified: "千万",
      traditional: "千萬",
      pinyin: "qiānwàn",
      english: "Must",
    },
    {
      simplified: "签证",
      traditional: "簽證",
      pinyin: "qiānzhèng",
      english: "Visa",
    },
    {
      simplified: "墙",
      traditional: "牆",
      pinyin: "qiáng",
      english: "Wall",
    },
    {
      simplified: "敲",
      traditional: "敲",
      pinyin: "qiāo",
      english: "Knock",
    },
    {
      simplified: "桥",
      traditional: "橋",
      pinyin: "qiáo",
      english: "Bridge",
    },
    {
      simplified: "巧克力",
      traditional: "巧克力",
      pinyin: "qiǎokèlì",
      english: "Chocolates",
    },
    {
      simplified: "亲戚",
      traditional: "親戚",
      pinyin: "qīnqi",
      english: "Relative",
    },
    {
      simplified: "轻",
      traditional: "輕",
      pinyin: "qīng",
      english: "Light",
    },
    {
      simplified: "轻松",
      traditional: "輕鬆",
      pinyin: "qīngsōng",
      english: "Relaxed",
    },
    {
      simplified: "情况",
      traditional: "情況",
      pinyin: "qíngkuàng",
      english: "Situation",
    },
    {
      simplified: "请假",
      traditional: "請假",
      pinyin: "qǐngjià",
      english: "Leave",
    },
    {
      simplified: "请客",
      traditional: "請客",
      pinyin: "qǐngkè",
      english: "Treat",
    },
    {
      simplified: "穷",
      traditional: "窮",
      pinyin: "qióng",
      english: "Poor",
    },
    {
      simplified: "区别",
      traditional: "區別",
      pinyin: "qūbié",
      english: "Difference",
    },
    {
      simplified: "取",
      traditional: "取",
      pinyin: "qǔ",
      english: "Take",
    },
    {
      simplified: "全部",
      traditional: "全部",
      pinyin: "quánbù",
      english: "Whole",
    },
    {
      simplified: "缺点",
      traditional: "缺點",
      pinyin: "quēdiǎn",
      english: "Shortcoming",
    },
    {
      simplified: "缺少",
      traditional: "缺少",
      pinyin: "quēshǎo",
      english: "Lack",
    },
    {
      simplified: "却",
      traditional: "卻",
      pinyin: "què",
      english: "But",
    },
    {
      simplified: "确实",
      traditional: "確實",
      pinyin: "quèshí",
      english: "Exactly",
    },
    {
      simplified: "群",
      traditional: "群",
      pinyin: "qún",
      english: "Group",
    },
    {
      simplified: "然而",
      traditional: "然而",
      pinyin: "rán'ér",
      english: "However",
    },
    {
      simplified: "热闹",
      traditional: "熱鬧",
      pinyin: "rènao",
      english: "Lively",
    },
    {
      simplified: "人民币",
      traditional: "人民幣",
      pinyin: "rénmínbì",
      english: "RMB",
    },
    {
      simplified: "任何",
      traditional: "任何",
      pinyin: "rènhé",
      english: "Whatever, any",
    },
    {
      simplified: "任务",
      traditional: "任務",
      pinyin: "rènwu",
      english: "Task",
    },
    {
      simplified: "扔",
      traditional: "扔",
      pinyin: "rēng",
      english: "Throw",
    },
    {
      simplified: "仍然",
      traditional: "仍然",
      pinyin: "réngrán",
      english: "Still",
    },
    {
      simplified: "日记",
      traditional: "日記",
      pinyin: "rìjì",
      english: "Diary",
    },
    {
      simplified: "入口",
      traditional: "入口",
      pinyin: "rùkǒu",
      english: "Entrance",
    },
    {
      simplified: "软",
      traditional: "軟",
      pinyin: "ruǎn",
      english: "Soft",
    },
    {
      simplified: "散步",
      traditional: "散步",
      pinyin: "sànbù",
      english: "Take a walk",
    },
    {
      simplified: "森林",
      traditional: "森林",
      pinyin: "sēnlín",
      english: "Forest",
    },
    {
      simplified: "沙发",
      traditional: "沙發",
      pinyin: "shāfā",
      english: "Sofa",
    },
    {
      simplified: "商量",
      traditional: "商量",
      pinyin: "shāngliang",
      english: "Discuss",
    },
    {
      simplified: "伤心",
      traditional: "傷心",
      pinyin: "shāngxīn",
      english: "Sad",
    },
    {
      simplified: "稍微",
      traditional: "稍微",
      pinyin: "shāowēi",
      english: "Slightly",
    },
    {
      simplified: "社会",
      traditional: "社會",
      pinyin: "shèhuì",
      english: "Sociology",
    },
    {
      simplified: "深",
      traditional: "深",
      pinyin: "shēn",
      english: "Deep",
    },
    {
      simplified: "申请",
      traditional: "申請",
      pinyin: "shēnqǐng",
      english: "Apply",
    },
    {
      simplified: "甚至",
      traditional: "甚至",
      pinyin: "shènzhì",
      english: "Even to the extent that",
    },
    {
      simplified: "生活",
      traditional: "生活",
      pinyin: "shēnghuó",
      english: "Life, livlihood, activity",
    },
    {
      simplified: "省",
      traditional: "省",
      pinyin: "shěng",
      english: "Province",
    },
    {
      simplified: "剩",
      traditional: "剩",
      pinyin: "shèng",
      english: "Left",
    },
    {
      simplified: "失败",
      traditional: "失敗",
      pinyin: "shībài",
      english: "Fail",
    },
    {
      simplified: "失望",
      traditional: "失望",
      pinyin: "shīwàng",
      english: "Disappointment",
    },
    {
      simplified: "师傅",
      traditional: "師傅",
      pinyin: "shīfu",
      english: "Master worker",
    },
    {
      simplified: "湿润",
      traditional: "濕潤",
      pinyin: "shīrùn",
      english: "Moist",
    },
    {
      simplified: "狮子",
      traditional: "獅子",
      pinyin: "shīzi",
      english: "Lion",
    },
    {
      simplified: "十分",
      traditional: "十分",
      pinyin: "shífēn",
      english: "Very",
    },
    {
      simplified: "实际",
      traditional: "實際",
      pinyin: "shíjì",
      english: "Actual",
    },
    {
      simplified: "实在",
      traditional: "實在",
      pinyin: "shízài",
      english: "Really",
    },
    {
      simplified: "食品",
      traditional: "食品",
      pinyin: "shípǐn",
      english: "Food",
    },
    {
      simplified: "使用",
      traditional: "使用",
      pinyin: "shǐyòng",
      english: "Use",
    },
    {
      simplified: "试",
      traditional: "試",
      pinyin: "shì",
      english: "Try",
    },
    {
      simplified: "市场",
      traditional: "市場",
      pinyin: "shìchǎng",
      english: "Market",
    },
    {
      simplified: "适合",
      traditional: "適合",
      pinyin: "shìhé",
      english: "Fit",
    },
    {
      simplified: "适应",
      traditional: "適應",
      pinyin: "shìyìng",
      english: "Adapt",
    },
    {
      simplified: "世纪",
      traditional: "世紀",
      pinyin: "shìjì",
      english: "Century",
    },
    {
      simplified: "收",
      traditional: "收",
      pinyin: "shōu",
      english: "Collect",
    },
    {
      simplified: "收入",
      traditional: "收入",
      pinyin: "shōurù",
      english: "Income",
    },
    {
      simplified: "收拾",
      traditional: "收拾",
      pinyin: "shōushi",
      english: "Tidy",
    },
    {
      simplified: "首都",
      traditional: "首都",
      pinyin: "shǒudū",
      english: "Capital",
    },
    {
      simplified: "首先",
      traditional: "首先",
      pinyin: "shǒuxiān",
      english: "First",
    },
    {
      simplified: "受不了",
      traditional: "受不了",
      pinyin: "shòubuliǎo",
      english: "Cannot bear sth",
    },
    {
      simplified: "受到",
      traditional: "受到",
      pinyin: "shòudào",
      english: "Suffer",
    },
    {
      simplified: "售货员",
      traditional: "售貨員",
      pinyin: "shòuhuòyuán",
      english: "Salesperson",
    },
    {
      simplified: "输",
      traditional: "輸",
      pinyin: "shū",
      english: "Lose, fail",
    },
    {
      simplified: "熟悉",
      traditional: "熟悉",
      pinyin: "shúxī",
      english: "Be familiar with",
    },
    {
      simplified: "数量",
      traditional: "數量",
      pinyin: "shùliàng",
      english: "Number, quantity, amount",
    },
    {
      simplified: "数字",
      traditional: "數字",
      pinyin: "shùzì",
      english: "Number, figure, digit",
    },
    {
      simplified: "帅",
      traditional: "帥",
      pinyin: "shuài",
      english: "Handsome",
    },
    {
      simplified: "顺便",
      traditional: "順便",
      pinyin: "shùnbiàn",
      english: "Incidentally",
    },
    {
      simplified: "顺利",
      traditional: "順利",
      pinyin: "shùnlì",
      english: "Smoothly",
    },
    {
      simplified: "顺序",
      traditional: "順序",
      pinyin: "shùnxù",
      english: "Order",
    },
    {
      simplified: "说明",
      traditional: "說明",
      pinyin: "shuōmíng",
      english: "Explain",
    },
    {
      simplified: "硕士",
      traditional: "碩士",
      pinyin: "shuòshì",
      english: "Master",
    },
    {
      simplified: "死",
      traditional: "死",
      pinyin: "sǐ",
      english: "Die",
    },
    {
      simplified: "速度",
      traditional: "速度",
      pinyin: "sùdù",
      english: "Speed",
    },
    {
      simplified: "塑料袋",
      traditional: "塑料袋",
      pinyin: "sùliàodài",
      english: "Plastic bag",
    },
    {
      simplified: "酸",
      traditional: "酸",
      pinyin: "suān",
      english: "Acid",
    },
    {
      simplified: "算",
      traditional: "算",
      pinyin: "suàn",
      english: "Count",
    },
    {
      simplified: "随便",
      traditional: "隨便",
      pinyin: "suíbiàn",
      english: "Casual",
    },
    {
      simplified: "随着",
      traditional: "隨著",
      pinyin: "suízhe",
      english: "Along with",
    },
    {
      simplified: "孙子",
      traditional: "孫子",
      pinyin: "sūnzi",
      english: "Grandson",
    },
    {
      simplified: "所有",
      traditional: "所有",
      pinyin: "suǒyǒu",
      english: "All",
    },
    {
      simplified: "台",
      traditional: "台",
      pinyin: "tái",
      english: "Platform",
    },
    {
      simplified: "抬",
      traditional: "抬",
      pinyin: "tái",
      english: "Lift",
    },
    {
      simplified: "态度",
      traditional: "態度",
      pinyin: "tàidu",
      english: "Attitude",
    },
    {
      simplified: "生命",
      traditional: "生命",
      pinyin: "shēngmìng",
      english: "Life, anima",
    },
    {
      simplified: "谈",
      traditional: "談",
      pinyin: "tán",
      english: "Talk",
    },
    {
      simplified: "弹钢琴",
      traditional: "彈鋼琴",
      pinyin: "tángāngqín",
      english: "Play the piano",
    },
    {
      simplified: "汤",
      traditional: "湯",
      pinyin: "tāng",
      english: "Soup",
    },
    {
      simplified: "躺",
      traditional: "躺",
      pinyin: "tǎng",
      english: "Lie",
    },
    {
      simplified: "趟",
      traditional: "趟",
      pinyin: "tàng",
      english: "Trip",
    },
    {
      simplified: "讨论",
      traditional: "討論",
      pinyin: "tǎolùn",
      english: "Discuss",
    },
    {
      simplified: "讨厌",
      traditional: "討厭",
      pinyin: "tǎoyàn",
      english: "Hate",
    },
    {
      simplified: "特点",
      traditional: "特點",
      pinyin: "tèdiǎn",
      english: "Characteristic",
    },
    {
      simplified: "提供",
      traditional: "提供",
      pinyin: "tígōng",
      english: "Provide",
    },
    {
      simplified: "提前",
      traditional: "提前",
      pinyin: "tíqián",
      english: "In advance",
    },
    {
      simplified: "提醒",
      traditional: "提醒",
      pinyin: "tíxǐng",
      english: "Remind",
    },
    {
      simplified: "填空",
      traditional: "填空",
      pinyin: "tiánkòng",
      english: "Fill in the blanks",
    },
    {
      simplified: "条件",
      traditional: "條件",
      pinyin: "tiáojiàn",
      english: "Condition",
    },
    {
      simplified: "停止",
      traditional: "停止",
      pinyin: "tíngzhǐ",
      english: "Stop it",
    },
    {
      simplified: "挺",
      traditional: "挺",
      pinyin: "tǐng",
      english: "Quite",
    },
    {
      simplified: "通过",
      traditional: "通過",
      pinyin: "tōngguò",
      english: "Through",
    },
    {
      simplified: "通知",
      traditional: "通知",
      pinyin: "tōngzhī",
      english: "Notice",
    },
    {
      simplified: "同情",
      traditional: "同情",
      pinyin: "tóngqíng",
      english: "Sympathy",
    },
    {
      simplified: "推",
      traditional: "推",
      pinyin: "tuī",
      english: "Push",
    },
    {
      simplified: "推迟",
      traditional: "推遲",
      pinyin: "tuīchí",
      english: "Delay",
    },
    {
      simplified: "脱",
      traditional: "脫",
      pinyin: "tuō",
      english: "Take off",
    },
    {
      simplified: "袜子",
      traditional: "襪子",
      pinyin: "wàzi",
      english: "Socks",
    },
    {
      simplified: "完全",
      traditional: "完全",
      pinyin: "wánquán",
      english: "Completely",
    },
    {
      simplified: "往",
      traditional: "往",
      pinyin: "wǎng",
      english: "To, towards",
    },
    {
      simplified: "往往",
      traditional: "往往",
      pinyin: "wǎngwǎng",
      english: "Often",
    },
    {
      simplified: "网球",
      traditional: "網球",
      pinyin: "wǎngqiú",
      english: "Tennis",
    },
    {
      simplified: "网站",
      traditional: "網站",
      pinyin: "wǎngzhàn",
      english: "Website",
    },
    {
      simplified: "危险",
      traditional: "危險",
      pinyin: "wēixiǎn",
      english: "Danger",
    },
    {
      simplified: "味道",
      traditional: "味道",
      pinyin: "wèidào",
      english: "Taste",
    },
    {
      simplified: "温度",
      traditional: "溫度",
      pinyin: "wēndù",
      english: "Temperature",
    },
    {
      simplified: "文章",
      traditional: "文章",
      pinyin: "wénzhāng",
      english: "Article",
    },
    {
      simplified: "握手",
      traditional: "握手",
      pinyin: "wòshǒu",
      english: "Handshake",
    },
    {
      simplified: "污染",
      traditional: "污染",
      pinyin: "wūrǎn",
      english: "Contaminated",
    },
    {
      simplified: "无",
      traditional: "無",
      pinyin: "wú",
      english: "Nothing",
    },
    {
      simplified: "无聊",
      traditional: "無聊",
      pinyin: "wúliáo",
      english: "Boring",
    },
    {
      simplified: "无论",
      traditional: "無論",
      pinyin: "wúlùn",
      english: "No matter what",
    },
    {
      simplified: "误会",
      traditional: "誤會",
      pinyin: "wùhuì",
      english: "Misunderstanding",
    },
    {
      simplified: "西红柿",
      traditional: "西紅柿",
      pinyin: "xīhóngshì",
      english: "Tomato",
    },
    {
      simplified: "吸引",
      traditional: "吸引",
      pinyin: "xīyǐn",
      english: "Attract",
    },
    {
      simplified: "洗衣机",
      traditional: "洗衣機",
      pinyin: "xǐyījī",
      english: "Washing machine",
    },
    {
      simplified: "咸",
      traditional: "咸",
      pinyin: "xián",
      english: "Salty",
    },
    {
      simplified: "现代",
      traditional: "現代",
      pinyin: "xiàndài",
      english: "Modern",
    },
    {
      simplified: "羡慕",
      traditional: "羨慕",
      pinyin: "xiànmù",
      english: "Envy",
    },
    {
      simplified: "限制",
      traditional: "限制",
      pinyin: "xiànzhì",
      english: "Limit",
    },
    {
      simplified: "香",
      traditional: "香",
      pinyin: "xiāng",
      english: "Fragrant",
    },
    {
      simplified: "相反",
      traditional: "相反",
      pinyin: "xiāngfǎn",
      english: "Contrary",
    },
    {
      simplified: "详细",
      traditional: "詳細",
      pinyin: "xiángxì",
      english: "Detailed",
    },
    {
      simplified: "响",
      traditional: "響",
      pinyin: "xiǎng",
      english: "Ring",
    },
    {
      simplified: "消息",
      traditional: "消息",
      pinyin: "xiāoxi",
      english: "Message",
    },
    {
      simplified: "小说",
      traditional: "小說",
      pinyin: "xiǎoshuō",
      english: "Novel",
    },
    {
      simplified: "笑话",
      traditional: "笑話",
      pinyin: "xiàohua",
      english: "Joke",
    },
    {
      simplified: "效果",
      traditional: "效果",
      pinyin: "xiàoguǒ",
      english: "Effect",
    },
    {
      simplified: "辛苦",
      traditional: "辛苦",
      pinyin: "xīnkǔ",
      english: "Hard",
    },
    {
      simplified: "心情",
      traditional: "心情",
      pinyin: "xīnqíng",
      english: "Mood",
    },
    {
      simplified: "信任",
      traditional: "信任",
      pinyin: "xìnrèn",
      english: "Trust",
    },
    {
      simplified: "信心",
      traditional: "信心",
      pinyin: "xìnxīn",
      english: "Confidence",
    },
    {
      simplified: "信用卡",
      traditional: "信用卡",
      pinyin: "xìnyòngkǎ",
      english: "Credit card",
    },
    {
      simplified: "兴奋",
      traditional: "興奮",
      pinyin: "xīngfèn",
      english: "Excitement",
    },
    {
      simplified: "行",
      traditional: "行",
      pinyin: "xíng",
      english: "That's ok",
    },
    {
      simplified: "醒",
      traditional: "醒",
      pinyin: "xǐng",
      english: "Wake up",
    },
    {
      simplified: "性别",
      traditional: "性別",
      pinyin: "xìngbié",
      english: "Gender",
    },
    {
      simplified: "性格",
      traditional: "性格",
      pinyin: "xìnggé",
      english: "Character",
    },
    {
      simplified: "幸福",
      traditional: "幸福",
      pinyin: "xìngfú",
      english: "Happiness",
    },
    {
      simplified: "修",
      traditional: "修",
      pinyin: "xiū",
      english: "Repair",
    },
    {
      simplified: "许多",
      traditional: "許多",
      pinyin: "xǔduō",
      english: "Many",
    },
    {
      simplified: "血",
      traditional: "血",
      pinyin: "xuè",
      english: "Blood",
    },
    {
      simplified: "压力",
      traditional: "壓力",
      pinyin: "yālì",
      english: "Pressure",
    },
    {
      simplified: "牙膏",
      traditional: "牙膏",
      pinyin: "yágāo",
      english: "Toothpaste",
    },
    {
      simplified: "亚洲",
      traditional: "亞洲",
      pinyin: "yàzhōu",
      english: "Asia",
    },
    {
      simplified: "呀",
      traditional: "呀",
      pinyin: "ya",
      english: "Ah",
    },
    {
      simplified: "盐",
      traditional: "鹽",
      pinyin: "yán",
      english: "Salt",
    },
    {
      simplified: "严格",
      traditional: "嚴格",
      pinyin: "yángé",
      english: "Strict",
    },
    {
      simplified: "严重",
      traditional: "嚴重",
      pinyin: "yánzhòng",
      english: "Serious",
    },
    {
      simplified: "研究生",
      traditional: "研究生",
      pinyin: "yánjiūshēng",
      english: "Graduate student",
    },
    {
      simplified: "演出",
      traditional: "演出",
      pinyin: "yǎnchū",
      english: "Show",
    },
    {
      simplified: "演员",
      traditional: "演員",
      pinyin: "yǎnyuán",
      english: "Performer, actor",
    },
    {
      simplified: "阳光",
      traditional: "陽光",
      pinyin: "yángguāng",
      english: "Sunshine",
    },
    {
      simplified: "养成",
      traditional: "養成",
      pinyin: "yǎngchéng",
      english: "Cultivate",
    },
    {
      simplified: "样子",
      traditional: "樣子",
      pinyin: "yàngzi",
      english: "A look",
    },
    {
      simplified: "邀请",
      traditional: "邀請",
      pinyin: "yāoqǐng",
      english: "Invitation",
    },
    {
      simplified: "钥匙",
      traditional: "鑰匙",
      pinyin: "yàoshi",
      english: "Key",
    },
    {
      simplified: "也许",
      traditional: "也許",
      pinyin: "yěxǔ",
      english: "Perhaps",
    },
    {
      simplified: "页",
      traditional: "頁",
      pinyin: "yè",
      english: "Page",
    },
    {
      simplified: "叶子",
      traditional: "葉子",
      pinyin: "yèzi",
      english: "Leaf",
    },
    {
      simplified: "一切",
      traditional: "一切",
      pinyin: "yíqiè",
      english: "Everything",
    },
    {
      simplified: "以",
      traditional: "以",
      pinyin: "yǐ",
      english: "With",
    },
    {
      simplified: "亿",
      traditional: "億",
      pinyin: "yì",
      english: "Billion",
    },
    {
      simplified: "意见",
      traditional: "意見",
      pinyin: "yìjiàn",
      english: "Opinion",
    },
    {
      simplified: "艺术",
      traditional: "藝術",
      pinyin: "yìshù",
      english: "Art",
    },
    {
      simplified: "因此",
      traditional: "因此",
      pinyin: "yīncǐ",
      english: "Therefore",
    },
    {
      simplified: "座",
      traditional: "座",
      pinyin: "zuò",
      english: "Seat, base, stand",
    },
    {
      simplified: "饮料",
      traditional: "飲料",
      pinyin: "yǐnliào",
      english: "Drinks",
    },
    {
      simplified: "引起",
      traditional: "引起",
      pinyin: "yǐnqǐ",
      english: "Cause",
    },
    {
      simplified: "印象",
      traditional: "印象",
      pinyin: "yìnxiàng",
      english: "Impression",
    },
    {
      simplified: "赢",
      traditional: "贏",
      pinyin: "yíng",
      english: "Win",
    },
    {
      simplified: "硬",
      traditional: "硬",
      pinyin: "yìng",
      english: "Hard",
    },
    {
      simplified: "勇敢",
      traditional: "勇敢",
      pinyin: "yǒnggǎn",
      english: "Brave",
    },
    {
      simplified: "永远",
      traditional: "永遠",
      pinyin: "yǒngyuǎn",
      english: "Forever",
    },
    {
      simplified: "优点",
      traditional: "優點",
      pinyin: "yōudiǎn",
      english: "Advantage",
    },
    {
      simplified: "优秀",
      traditional: "優秀",
      pinyin: "yōuxiù",
      english: "Excellent",
    },
    {
      simplified: "幽默",
      traditional: "幽默",
      pinyin: "yōumò",
      english: "Humor",
    },
    {
      simplified: "由",
      traditional: "由",
      pinyin: "yóu",
      english: "From",
    },
    {
      simplified: "由于",
      traditional: "由於",
      pinyin: "yóuyú",
      english: "Because",
    },
    {
      simplified: "尤其",
      traditional: "尤其",
      pinyin: "yóuqí",
      english: "Especially",
    },
    {
      simplified: "有趣",
      traditional: "有趣",
      pinyin: "yǒuqù",
      english: "Interesting",
    },
    {
      simplified: "友好",
      traditional: "友好",
      pinyin: "yǒuhǎo",
      english: "Friendly",
    },
    {
      simplified: "友谊",
      traditional: "友誼",
      pinyin: "yǒuyì",
      english: "Friendship",
    },
    {
      simplified: "愉快",
      traditional: "愉快",
      pinyin: "yúkuài",
      english: "Cheerful",
    },
    {
      simplified: "于是",
      traditional: "於是",
      pinyin: "yúshì",
      english: "Therefore",
    },
    {
      simplified: "与",
      traditional: "與",
      pinyin: "yǔ",
      english: "And",
    },
    {
      simplified: "语法",
      traditional: "語法",
      pinyin: "yǔfǎ",
      english: "Grammar",
    },
    {
      simplified: "语言",
      traditional: "語言",
      pinyin: "yǔyán",
      english: "Language",
    },
    {
      simplified: "羽毛球",
      traditional: "羽毛球",
      pinyin: "yǔmáoqiú",
      english: "Badminton",
    },
    {
      simplified: "预习",
      traditional: "預習",
      pinyin: "yùxí",
      english: "Preview",
    },
    {
      simplified: "圆",
      traditional: "圓",
      pinyin: "yuán",
      english: "Circle",
    },
    {
      simplified: "原来",
      traditional: "原來",
      pinyin: "yuánlái",
      english: "Original",
    },
    {
      simplified: "原谅",
      traditional: "原諒",
      pinyin: "yuánliàng",
      english: "Forgive",
    },
    {
      simplified: "原因",
      traditional: "原因",
      pinyin: "yuányīn",
      english: "Reason",
    },
    {
      simplified: "约会",
      traditional: "約會",
      pinyin: "yuēhuì",
      english: "Date",
    },
    {
      simplified: "阅读",
      traditional: "閱讀",
      pinyin: "yuèdú",
      english: "Read",
    },
    {
      simplified: "允许",
      traditional: "允許",
      pinyin: "yǔnxǔ",
      english: "Allow",
    },
    {
      simplified: "杂志",
      traditional: "雜誌",
      pinyin: "zázhì",
      english: "Magazine",
    },
    {
      simplified: "咱们",
      traditional: "咱們",
      pinyin: "zánmen",
      english: "We",
    },
    {
      simplified: "暂时",
      traditional: "暫時",
      pinyin: "zànshí",
      english: "Temporary",
    },
    {
      simplified: "脏",
      traditional: "臟",
      pinyin: "zāng",
      english: "Dirty",
    },
    {
      simplified: "责任",
      traditional: "責任",
      pinyin: "zérèn",
      english: "Responsibility",
    },
    {
      simplified: "增加",
      traditional: "增加",
      pinyin: "zēngjiā",
      english: "Increase, addition",
    },
    {
      simplified: "窄",
      traditional: "窄",
      pinyin: "zhǎi",
      english: "Narrow",
    },
    {
      simplified: "招聘",
      traditional: "招聘",
      pinyin: "zhāopìn",
      english: "Recruit",
    },
    {
      simplified: "着",
      traditional: "著",
      pinyin: "zhe",
      english: "In process of",
    },
    {
      simplified: "真正",
      traditional: "真正",
      pinyin: "zhēnzhèng",
      english: "Real",
    },
    {
      simplified: "整理",
      traditional: "整理",
      pinyin: "zhěnglǐ",
      english: "Arrangement",
    },
    {
      simplified: "整齐",
      traditional: "整齊",
      pinyin: "zhěngqí",
      english: "Neat",
    },
    {
      simplified: "正常",
      traditional: "正常",
      pinyin: "zhèngcháng",
      english: "Normal",
    },
    {
      simplified: "正好",
      traditional: "正好",
      pinyin: "zhènghǎo",
      english: "Just right",
    },
    {
      simplified: "正确",
      traditional: "正確",
      pinyin: "zhèngquè",
      english: "Correct",
    },
    {
      simplified: "正式",
      traditional: "正式",
      pinyin: "zhèngshì",
      english: "Formal",
    },
    {
      simplified: "证明",
      traditional: "證明",
      pinyin: "zhèngmíng",
      english: "Prove",
    },
    {
      simplified: "之",
      traditional: "之",
      pinyin: "zhī",
      english: "Of",
    },
    {
      simplified: "支持",
      traditional: "支持",
      pinyin: "zhīchí",
      english: "Support",
    },
    {
      simplified: "知识",
      traditional: "知識",
      pinyin: "zhīshi",
      english: "Knowledge",
    },
    {
      simplified: "值得",
      traditional: "值得",
      pinyin: "zhídé",
      english: "Worth",
    },
    {
      simplified: "直接",
      traditional: "直接",
      pinyin: "zhíjiē",
      english: "Direct",
    },
    {
      simplified: "植物",
      traditional: "植物",
      pinyin: "zhíwù",
      english: "Botany, plant",
    },
    {
      simplified: "职业",
      traditional: "職業",
      pinyin: "zhíyè",
      english: "Occupation",
    },
    {
      simplified: "指",
      traditional: "指",
      pinyin: "zhǐ",
      english: "Finger, to point",
    },
    {
      simplified: "只好",
      traditional: "只好",
      pinyin: "zhǐhǎo",
      english: "Have to",
    },
    {
      simplified: "只要",
      traditional: "只要",
      pinyin: "zhǐyào",
      english: "As long as",
    },
    {
      simplified: "质量",
      traditional: "質量",
      pinyin: "zhìliàng",
      english: "Quality",
    },
    {
      simplified: "至少",
      traditional: "至少",
      pinyin: "zhìshǎo",
      english: "At least",
    },
    {
      simplified: "制造",
      traditional: "製造",
      pinyin: "zhìzào",
      english: "Manufacture",
    },
    {
      simplified: "中文",
      traditional: "中文",
      pinyin: "zhōngwén",
      english: "Chinese",
    },
    {
      simplified: "重点",
      traditional: "重點",
      pinyin: "zhòngdiǎn",
      english: "A key",
    },
    {
      simplified: "重视",
      traditional: "重視",
      pinyin: "zhòngshì",
      english: "Importance, attach importance to",
    },
    {
      simplified: "周围",
      traditional: "周圍",
      pinyin: "zhōuwéi",
      english: "Around",
    },
    {
      simplified: "猪",
      traditional: "豬",
      pinyin: "zhū",
      english: "Pig",
    },
    {
      simplified: "逐渐",
      traditional: "逐漸",
      pinyin: "zhújiàn",
      english: "Gradually",
    },
    {
      simplified: "主动",
      traditional: "主動",
      pinyin: "zhǔdòng",
      english: "Active",
    },
    {
      simplified: "主意",
      traditional: "主意",
      pinyin: "zhǔyi",
      english: "Idea",
    },
    {
      simplified: "祝贺",
      traditional: "祝賀",
      pinyin: "zhùhè",
      english: "Congratulate",
    },
    {
      simplified: "著名",
      traditional: "著名",
      pinyin: "zhùmíng",
      english: "Famous",
    },
    {
      simplified: "专门",
      traditional: "專門",
      pinyin: "zhuānmén",
      english: "Specialized",
    },
    {
      simplified: "专业",
      traditional: "專業",
      pinyin: "zhuānyè",
      english: "Major",
    },
    {
      simplified: "赚",
      traditional: "賺",
      pinyin: "zhuàn",
      english: "Earn",
    },
    {
      simplified: "撞",
      traditional: "撞",
      pinyin: "zhuàng",
      english: "Hit",
    },
    {
      simplified: "准确",
      traditional: "準確",
      pinyin: "zhǔnquè",
      english: "Accuracy",
    },
    {
      simplified: "准时",
      traditional: "準時",
      pinyin: "zhǔnshí",
      english: "On time",
    },
    {
      simplified: "仔细",
      traditional: "仔細",
      pinyin: "zǐxì",
      english: "Careful",
    },
    {
      simplified: "自然",
      traditional: "自然",
      pinyin: "zìrán",
      english: "Natural",
    },
    {
      simplified: "总结",
      traditional: "總結",
      pinyin: "zǒngjié",
      english: "Summary",
    },
    {
      simplified: "租",
      traditional: "租",
      pinyin: "zū",
      english: "Rent",
    },
    {
      simplified: "组成",
      traditional: "組成",
      pinyin: "zǔchéng",
      english: "Form",
    },
    {
      simplified: "组织",
      traditional: "組織",
      pinyin: "zǔzhī",
      english: "Organization",
    },
    {
      simplified: "嘴",
      traditional: "嘴",
      pinyin: "zuǐ",
      english: "Mouth",
    },
    {
      simplified: "最好",
      traditional: "最好",
      pinyin: "zuìhǎo",
      english: "Best",
    },
    {
      simplified: "最后",
      traditional: "最後",
      pinyin: "zuìhòu",
      english: "Last",
    },
    {
      simplified: "尊重",
      traditional: "尊重",
      pinyin: "zūnzhòng",
      english: "Respect",
    },
    {
      simplified: "做生意",
      traditional: "做生意",
      pinyin: "zuòshēngyi",
      english: "Do business",
    },
    {
      simplified: "座位",
      traditional: "座位",
      pinyin: "zuòwèi",
      english: "Seat, place, pew",
    },
    {
      simplified: "增长",
      traditional: "增長",
      pinyin: "zēngzhǎng",
      english: "Increase, grow",
    },
    {
      simplified: "作者",
      traditional: "作者",
      pinyin: "zuòzhě",
      english: "Author",
    },
    {
      simplified: "作用",
      traditional: "作用",
      pinyin: "zuòyòng",
      english: "Effect",
    },
    {
      simplified: "吃瓜群众",
      traditional: "吃瓜群眾",
      pinyin: "Chī guā qúnzhòng",
      english: "Bystanders, gawkers",
    },
    {
      simplified: "土豪",
      traditional: "土豪",
      pinyin: "tǔháo",
      english: "Rich person, upstart",
    },
  ],
};

export default lesson4;
