import type HskList from "~/types/HskList";

const lesson3: HskList = {
  id: "m1uti3kcG",
  level: 3,
  words: [
    {
      english: "Aunt",
      pinyin: "āyí",
      simplified: "阿姨",
      traditional: "阿姨",
    },
    {
      english: "Ah",
      pinyin: "a",
      simplified: "啊",
      traditional: "啊",
    },
    {
      english: "Short",
      pinyin: "ǎi",
      simplified: "矮",
      traditional: "矮",
    },
    {
      english: "Hobby",
      pinyin: "àihào",
      simplified: "爱好",
      traditional: "愛好",
    },
    {
      english: "Be quiet",
      pinyin: "ānjìng",
      simplified: "安静",
      traditional: "安靜",
    },
    {
      english: "Hold",
      pinyin: "bǎ",
      simplified: "把",
      traditional: "把",
    },
    {
      english: "Class",
      pinyin: "bān",
      simplified: "班",
      traditional: "班",
    },
    {
      english: "Move",
      pinyin: "bān",
      simplified: "搬",
      traditional: "搬",
    },
    {
      english: "Half",
      pinyin: "bàn",
      simplified: "半",
      traditional: "半",
    },
    {
      english: "Way",
      pinyin: "bànfǎ",
      simplified: "办法",
      traditional: "辦法",
    },
    {
      english: "Office",
      pinyin: "bàngōngshì",
      simplified: "办公室",
      traditional: "辦公室",
    },
    {
      english: "Help",
      pinyin: "bāngmáng",
      simplified: "帮忙",
      traditional: "幫忙",
    },
    {
      english: "Package",
      pinyin: "bāo",
      simplified: "包",
      traditional: "包",
    },
    {
      english: "Full",
      pinyin: "bǎo",
      simplified: "饱",
      traditional: "飽",
    },
    {
      english: "North",
      pinyin: "běifāng",
      simplified: "北方",
      traditional: "北方",
    },
    {
      english: "Cover",
      pinyin: "bèi",
      simplified: "被",
      traditional: "被",
    },
    {
      english: "Nose",
      pinyin: "bízi",
      simplified: "鼻子",
      traditional: "鼻子",
    },
    {
      english: "Than",
      pinyin: "bǐ",
      simplified: "比",
      traditional: "比",
    },
    {
      english: "Compare",
      pinyin: "bǐjiào",
      simplified: "比较",
      traditional: "比較",
    },
    {
      english: "Match",
      pinyin: "bǐsài",
      simplified: "比赛",
      traditional: "比賽",
    },
    {
      english: "Must",
      pinyin: "bìxū",
      simplified: "必须",
      traditional: "必須",
    },
    {
      english: "Change",
      pinyin: "biànhuà",
      simplified: "变化",
      traditional: "變化",
    },
    {
      english: "Express",
      pinyin: "biǎoshì",
      simplified: "表示",
      traditional: "表示",
    },
    {
      english: "Perform",
      pinyin: "biǎoyǎn",
      simplified: "表演",
      traditional: "表演",
    },
    {
      english: "Others",
      pinyin: "biéren",
      simplified: "别人",
      traditional: "別人",
    },
    {
      english: "Hotel",
      pinyin: "bīnguǎn",
      simplified: "宾馆",
      traditional: "賓館",
    },
    {
      english: "Refrigerator",
      pinyin: "bīngxiāng",
      simplified: "冰箱",
      traditional: "冰箱",
    },
    {
      english: "Just",
      pinyin: "cái",
      simplified: "才",
      traditional: "才",
    },
    {
      english: "Menu",
      pinyin: "càidān",
      simplified: "菜单",
      traditional: "菜單",
    },
    {
      english: "Participate in",
      pinyin: "cānjiā",
      simplified: "参加",
      traditional: "參加",
    },
    {
      english: "Grass",
      pinyin: "cǎo",
      simplified: "草",
      traditional: "草",
    },
    {
      english: "Layer",
      pinyin: "céng",
      simplified: "层",
      traditional: "層",
    },
    {
      english: "Bad",
      pinyin: "chà",
      simplified: "差",
      traditional: "差",
    },
    {
      english: "Supermarket",
      pinyin: "chāoshì",
      simplified: "超市",
      traditional: "超市",
    },
    {
      english: "Shirt",
      pinyin: "chènshān",
      simplified: "衬衫",
      traditional: "襯衫",
    },
    {
      english: "Achievement",
      pinyin: "chéngjì",
      simplified: "成绩",
      traditional: "成績",
    },
    {
      english: "City",
      pinyin: "chéngshì",
      simplified: "城市",
      traditional: "城市",
    },
    {
      english: "Late",
      pinyin: "chídào",
      simplified: "迟到",
      traditional: "遲到",
    },
    {
      english: "Appear",
      pinyin: "chūxiàn",
      simplified: "出现",
      traditional: "出現",
    },
    {
      english: "Kitchen",
      pinyin: "chúfáng",
      simplified: "厨房",
      traditional: "廚房",
    },
    {
      english: "Except, besides",
      pinyin: "chúle",
      simplified: "除了",
      traditional: "除了",
    },
    {
      english: "Spring",
      pinyin: "chūn",
      simplified: "春",
      traditional: "春天",
    },
    {
      english: "Terms, words",
      pinyin: "cíyǔ",
      simplified: "词语",
      traditional: "詞語",
    },
    {
      english: "Clever",
      pinyin: "cōngming",
      simplified: "聪明",
      traditional: "聰明",
    },
    {
      english: "Clean",
      pinyin: "dǎsǎo",
      simplified: "打扫",
      traditional: "打掃",
    },
    {
      english: "Plan",
      pinyin: "dǎsuàn",
      simplified: "打算",
      traditional: "打算",
    },
    {
      english: "Belt",
      pinyin: "dài",
      simplified: "带",
      traditional: "帶",
    },
    {
      english: "Worry",
      pinyin: "dānxīn",
      simplified: "担心",
      traditional: "擔心",
    },
    {
      english: "Cake",
      pinyin: "dàngāo",
      simplified: "蛋糕",
      traditional: "蛋糕",
    },
    {
      english: "Of course",
      pinyin: "dāngrán",
      simplified: "当然",
      traditional: "當然",
    },
    {
      english: "Lamp",
      pinyin: "dēng",
      simplified: "灯",
      traditional: "燈",
    },
    {
      english: "Low",
      pinyin: "dī",
      simplified: "低",
      traditional: "低",
    },
    {
      english: "Local",
      pinyin: "dìfang",
      simplified: "地方",
      traditional: "地方",
    },
    {
      english: "Metro",
      pinyin: "dìtiě",
      simplified: "地铁",
      traditional: "地鐵",
    },
    {
      english: "Map",
      pinyin: "dìtú",
      simplified: "地图",
      traditional: "地圖",
    },
    {
      english: "Elevator",
      pinyin: "diàntī",
      simplified: "电梯",
      traditional: "電梯",
    },
    {
      english: "E-mail",
      pinyin: "diànzǐyóujiàn",
      simplified: "电子邮件",
      traditional: "電子郵件",
    },
    {
      english: "East",
      pinyin: "dōng",
      simplified: "东",
      traditional: "東",
    },
    {
      english: "Winter",
      pinyin: "dōng",
      simplified: "冬",
      traditional: "冬季",
    },
    {
      english: "Animal",
      pinyin: "dòngwù",
      simplified: "动物",
      traditional: "動物",
    },
    {
      english: "Short",
      pinyin: "duǎn",
      simplified: "短",
      traditional: "短",
    },
    {
      english: "Paragraph",
      pinyin: "duàn",
      simplified: "段",
      traditional: "段",
    },
    {
      english: "Physical exercise",
      pinyin: "duànliàn",
      simplified: "锻炼",
      traditional: "鍛煉",
    },
    {
      english: "Such",
      pinyin: "duōme",
      simplified: "多么",
      traditional: "多麼",
    },
    {
      english: "Hungry",
      pinyin: "è",
      simplified: "饿",
      traditional: "餓",
    },
    {
      english: "And",
      pinyin: "érqiě",
      simplified: "而且",
      traditional: "而且",
    },
    {
      english: "Ears",
      pinyin: "ěrduo",
      simplified: "耳朵",
      traditional: "耳朵",
    },
    {
      english: "Have a fever",
      pinyin: "fāshāo",
      simplified: "发烧",
      traditional: "發燒",
    },
    {
      english: "Find, discover",
      pinyin: "fāxiàn",
      simplified: "发现",
      traditional: "發現",
    },
    {
      english: "Convenient",
      pinyin: "fāngbiàn",
      simplified: "方便",
      traditional: "方便",
    },
    {
      english: "Discharge",
      pinyin: "fàng",
      simplified: "放",
      traditional: "放",
    },
    {
      english: "Don't worry",
      pinyin: "fàngxīn",
      simplified: "放心",
      traditional: "放心",
    },
    {
      english: "Minute",
      pinyin: "fēn",
      simplified: "分",
      traditional: "分",
    },
    {
      english: "Nearby",
      pinyin: "fùjìn",
      simplified: "附近",
      traditional: "附近",
    },
    {
      english: "Review",
      pinyin: "fùxí",
      simplified: "复习",
      traditional: "複習",
    },
    {
      english: "Clean",
      pinyin: "gānjìng",
      simplified: "干净",
      traditional: "乾淨",
    },
    {
      english: "Dare",
      pinyin: "gǎn",
      simplified: "敢",
      traditional: "敢",
    },
    {
      english: "Get a cold",
      pinyin: "gǎnmào",
      simplified: "感冒",
      traditional: "感冒",
    },
    {
      english: "Just",
      pinyin: "gāngcái",
      simplified: "刚才",
      traditional: "剛才",
    },
    {
      english: "With",
      pinyin: "gēn",
      simplified: "跟",
      traditional: "跟",
    },
    {
      english: "According to",
      pinyin: "gēnjù",
      simplified: "根据",
      traditional: "根據",
    },
    {
      english: "More",
      pinyin: "gèng",
      simplified: "更",
      traditional: "更",
    },
    {
      english: "Company",
      pinyin: "gōngsī",
      simplified: "公司",
      traditional: "公司",
    },
    {
      english: "Park",
      pinyin: "gōngyuán",
      simplified: "公园",
      traditional: "公園",
    },
    {
      english: "Story",
      pinyin: "gùshi",
      simplified: "故事",
      traditional: "故事",
    },
    {
      english: "Windy",
      pinyin: "guāfēng",
      simplified: "刮风",
      traditional: "刮風",
    },
    {
      english: "Shut",
      pinyin: "guān",
      simplified: "关",
      traditional: "關",
    },
    {
      english: "Relationship",
      pinyin: "guānxì",
      simplified: "关系",
      traditional: "關係",
    },
    {
      english: "Care for",
      pinyin: "guānxīn",
      simplified: "关心",
      traditional: "關心",
    },
    {
      english: "About",
      pinyin: "guānyú",
      simplified: "关于",
      traditional: "關於",
    },
    {
      english: "Country",
      pinyin: "guójiā",
      simplified: "国家",
      traditional: "國家",
    },
    {
      english: "Fruit juice",
      pinyin: "guǒzhī",
      simplified: "果汁",
      traditional: "果汁",
    },
    {
      english: "Past times",
      pinyin: "guòqù",
      simplified: "过去",
      traditional: "過去",
    },
    {
      english: "Too",
      pinyin: "guo",
      simplified: "过",
      traditional: "過",
    },
    {
      english: "Still",
      pinyin: "háishì",
      simplified: "还是",
      traditional: "還是",
    },
    {
      english: "Fear",
      pinyin: "hàipà",
      simplified: "害怕",
      traditional: "害怕",
    },
    {
      english: "River",
      pinyin: "hé",
      simplified: "河",
      traditional: "河",
    },
    {
      english: "Blackboard",
      pinyin: "hēibǎn",
      simplified: "黑板",
      traditional: "黑板",
    },
    {
      english: "Passport",
      pinyin: "hùzhào",
      simplified: "护照",
      traditional: "護照",
    },
    {
      english: "Spend (verb)",
      pinyin: "huā",
      simplified: "花",
      traditional: "花",
    },
    {
      english: "Garden",
      pinyin: "huāyuán",
      simplified: "花园",
      traditional: "花園",
    },
    {
      english: "Painting",
      pinyin: "huà",
      simplified: "画",
      traditional: "畫",
    },
    {
      english: "Bad",
      pinyin: "huài",
      simplified: "坏",
      traditional: "壞",
    },
    {
      english: "Environment",
      pinyin: "huánjìng",
      simplified: "环境",
      traditional: "環境",
    },
    {
      english: "Change",
      pinyin: "huàn",
      simplified: "换",
      traditional: "換",
    },
    {
      english: "Yellow",
      pinyin: "huáng",
      simplified: "黄",
      traditional: "黃",
    },
    {
      english: "Meeting",
      pinyin: "huìyì",
      simplified: "会议",
      traditional: "會議",
    },
    {
      english: "Perhaps",
      pinyin: "huòzhě",
      simplified: "或者",
      traditional: "或者",
    },
    {
      english: "Almost",
      pinyin: "jīhū",
      simplified: "几乎",
      traditional: "幾乎",
    },
    {
      english: "Opportunity",
      pinyin: "jīhuì",
      simplified: "机会",
      traditional: "機會",
    },
    {
      english: "Extremely",
      pinyin: "jí",
      simplified: "极",
      traditional: "極",
    },
    {
      english: "Remember",
      pinyin: "jìde",
      simplified: "记得",
      traditional: "記得",
    },
    {
      english: "Season",
      pinyin: "jìjié",
      simplified: "季节",
      traditional: "季節",
    },
    {
      english: "Inspect",
      pinyin: "jiǎnchá",
      simplified: "检查",
      traditional: "檢查",
    },
    {
      english: "Simple",
      pinyin: "jiǎndān",
      simplified: "简单",
      traditional: "簡單",
    },
    {
      english: "Healthy",
      pinyin: "jiànkāng",
      simplified: "健康",
      traditional: "健康",
    },
    {
      english: "Meet",
      pinyin: "jiànmiàn",
      simplified: "见面",
      traditional: "見面",
    },
    {
      english: "Speak",
      pinyin: "jiǎng",
      simplified: "讲",
      traditional: "講",
    },
    {
      english: "Teach",
      pinyin: "jiāo",
      simplified: "教",
      traditional: "教",
    },
    {
      english: "Horn",
      pinyin: "jiǎo",
      simplified: "角",
      traditional: "角",
    },
    {
      english: "Foot",
      pinyin: "jiǎo",
      simplified: "脚",
      traditional: "腳",
    },
    {
      english: "Pick,get",
      pinyin: "jiē",
      simplified: "接",
      traditional: "接",
    },
    {
      english: "Street",
      pinyin: "jiēdào",
      simplified: "街道",
      traditional: "街道",
    },
    {
      english: "Marry",
      pinyin: "jiéhūn",
      simplified: "结婚",
      traditional: "結婚",
    },
    {
      english: "End",
      pinyin: "jiéshù",
      simplified: "结束",
      traditional: "結束",
    },
    {
      english: "Program",
      pinyin: "jiémù",
      simplified: "节目",
      traditional: "節目",
    },
    {
      english: "Festival",
      pinyin: "jiérì",
      simplified: "节日",
      traditional: "節日",
    },
    {
      english: "Solve",
      pinyin: "jiějué",
      simplified: "解决",
      traditional: "解決",
    },
    {
      english: "Borrow",
      pinyin: "jiè",
      simplified: "借",
      traditional: "借",
    },
    {
      english: "Often",
      pinyin: "jīngcháng",
      simplified: "经常",
      traditional: "經常",
    },
    {
      english: "After, through",
      pinyin: "jīngguò",
      simplified: "经过",
      traditional: "經過",
    },
    {
      english: "Manager",
      pinyin: "jīnglǐ",
      simplified: "经理",
      traditional: "經理",
    },
    {
      english: "Long",
      pinyin: "jiǔ",
      simplified: "久",
      traditional: "久",
    },
    {
      english: "Old,used",
      pinyin: "jiù",
      simplified: "旧",
      traditional: "舊",
    },
    {
      english: "Hold",
      pinyin: "jǔxíng",
      simplified: "举行",
      traditional: "舉行",
    },
    {
      english: "Sentence",
      pinyin: "jùzi",
      simplified: "句子",
      traditional: "句子",
    },
    {
      english: "Decision",
      pinyin: "juédìng",
      simplified: "决定",
      traditional: "決定",
    },
    {
      english: "Thirsty",
      pinyin: "kě",
      simplified: "渴",
      traditional: "渴",
    },
    {
      english: "Lovely",
      pinyin: "kě'ài",
      simplified: "可爱",
      traditional: "可愛",
    },
    {
      english: "Moment",
      pinyin: "kè",
      simplified: "刻",
      traditional: "刻",
    },
    {
      english: "Guest",
      pinyin: "kèrén",
      simplified: "客人",
      traditional: "客人",
    },
    {
      english: "Air conditioner",
      pinyin: "kōngtiáo",
      simplified: "空调",
      traditional: "空調",
    },
    {
      english: "Mouth",
      pinyin: "kǒu",
      simplified: "口",
      traditional: "口",
    },
    {
      english: "Cry",
      pinyin: "kū",
      simplified: "哭",
      traditional: "哭",
    },
    {
      english: "Trousers",
      pinyin: "kùzi",
      simplified: "裤子",
      traditional: "褲子",
    },
    {
      english: "Chopsticks",
      pinyin: "kuàizi",
      simplified: "筷子",
      traditional: "筷子",
    },
    {
      english: "Blue",
      pinyin: "lán",
      simplified: "蓝",
      traditional: "藍",
    },
    {
      english: "Old",
      pinyin: "lǎo",
      simplified: "老",
      traditional: "老",
    },
    {
      english: "Leave",
      pinyin: "líkāi",
      simplified: "离开",
      traditional: "離開",
    },
    {
      english: "Gift",
      pinyin: "lǐwù",
      simplified: "礼物",
      traditional: "禮物",
    },
    {
      english: "History",
      pinyin: "lìshǐ",
      simplified: "历史",
      traditional: "歷史",
    },
    {
      english: "Face",
      pinyin: "liǎn",
      simplified: "脸",
      traditional: "臉",
    },
    {
      english: "Practice",
      pinyin: "liànxí",
      simplified: "练习",
      traditional: "練習",
    },
    {
      english: "Car",
      pinyin: "liàng",
      simplified: "辆",
      traditional: "輛",
    },
    {
      english: "Understand",
      pinyin: "liǎojiě",
      simplified: "了解",
      traditional: "了解",
    },
    {
      english: "Neighbor",
      pinyin: "línjū",
      simplified: "邻居",
      traditional: "鄰居",
    },
    {
      english: "Floor",
      pinyin: "lóu",
      simplified: "楼",
      traditional: "樓",
    },
    {
      english: "Green",
      pinyin: "lǜ",
      simplified: "绿",
      traditional: "綠",
    },
    {
      english: "Horse",
      pinyin: "mǎ",
      simplified: "马",
      traditional: "馬",
    },
    {
      english: "Right off",
      pinyin: "mǎshàng",
      simplified: "马上",
      traditional: "馬上",
    },
    {
      english: "Sell",
      pinyin: "mài",
      simplified: "卖",
      traditional: "賣",
    },
    {
      english: "Satisfied",
      pinyin: "mǎnyì",
      simplified: "满意",
      traditional: "滿意",
    },
    {
      english: "Hat",
      pinyin: "màozi",
      simplified: "帽子",
      traditional: "帽子",
    },
    {
      english: "Rice",
      pinyin: "mǐ",
      simplified: "米",
      traditional: "米",
    },
    {
      english: "Bread",
      pinyin: "miànbāo",
      simplified: "面包",
      traditional: "麵包",
    },
    {
      english: "Noodle",
      pinyin: "miàntiáo",
      simplified: "面条",
      traditional: "麵條",
    },
    {
      english: "Clear",
      pinyin: "míngbai",
      simplified: "明白",
      traditional: "明白",
    },
    {
      english: "Take",
      pinyin: "ná",
      simplified: "拿",
      traditional: "拿",
    },
    {
      english: "Grandma",
      pinyin: "nǎinai",
      simplified: "奶奶",
      traditional: "奶奶",
    },
    {
      english: "South",
      pinyin: "nán",
      simplified: "南",
      traditional: "南",
    },
    {
      english: "Difficult",
      pinyin: "nán",
      simplified: "难",
      traditional: "難",
    },
    {
      english: "Sad",
      pinyin: "nánguò",
      simplified: "难过",
      traditional: "難過",
    },
    {
      english: "Grade",
      pinyin: "niánjí",
      simplified: "年级",
      traditional: "年級",
    },
    {
      english: "Young",
      pinyin: "niánqīng",
      simplified: "年轻",
      traditional: "年輕",
    },
    {
      english: "Bird",
      pinyin: "niǎo",
      simplified: "鸟",
      traditional: "鳥",
    },
    {
      english: "Strive",
      pinyin: "nǔlì",
      simplified: "努力",
      traditional: "努力",
    },
    {
      english: "Mountain climbing",
      pinyin: "páshān",
      simplified: "爬山",
      traditional: "爬山",
    },
    {
      english: "Plate",
      pinyin: "pánzi",
      simplified: "盘子",
      traditional: "盤子",
    },
    {
      english: "Fat",
      pinyin: "pàng",
      simplified: "胖",
      traditional: "胖",
    },
    {
      english: "Beer",
      pinyin: "píjiǔ",
      simplified: "啤酒",
      traditional: "啤酒",
    },
    {
      english: "Grape",
      pinyin: "pútao",
      simplified: "葡萄",
      traditional: "葡萄",
    },
    {
      english: "Mandarin",
      pinyin: "pǔtōnghuà",
      simplified: "普通话",
      traditional: "普通話",
    },
    {
      english: "Actually",
      pinyin: "qíshí",
      simplified: "其实",
      traditional: "其實",
    },
    {
      english: "Other",
      pinyin: "qítā",
      simplified: "其他",
      traditional: "其他",
    },
    {
      english: "Ride",
      pinyin: "qí",
      simplified: "骑",
      traditional: "騎",
    },
    {
      english: "Strange",
      pinyin: "qíguài",
      simplified: "奇怪",
      traditional: "奇怪",
    },
    {
      english: "Pencil",
      pinyin: "qiānbǐ",
      simplified: "铅笔",
      traditional: "鉛筆",
    },
    {
      english: "Clear",
      pinyin: "qīngchu",
      simplified: "清楚",
      traditional: "清楚",
    },
    {
      english: "Autumn",
      pinyin: "qiū",
      simplified: "秋",
      traditional: "秋",
    },
    {
      english: "Skirt",
      pinyin: "qúnzi",
      simplified: "裙子",
      traditional: "裙子",
    },
    {
      english: "Then",
      pinyin: "ránhòu",
      simplified: "然后",
      traditional: "然後",
    },
    {
      english: "Enthusiasm",
      pinyin: "rèqíng",
      simplified: "热情",
      traditional: "熱情",
    },
    {
      english: "Think",
      pinyin: "rènwéi",
      simplified: "认为",
      traditional: "認為",
    },
    {
      english: "Earnest",
      pinyin: "rènzhēn",
      simplified: "认真",
      traditional: "認真",
    },
    {
      english: "Easily",
      pinyin: "róngyì",
      simplified: "容易",
      traditional: "容易",
    },
    {
      english: "If",
      pinyin: "rúguǒ",
      simplified: "如果",
      traditional: "如果",
    },
    {
      english: "Umbrella",
      pinyin: "sǎn",
      simplified: "伞",
      traditional: "傘",
    },
    {
      english: "Surf the Internet",
      pinyin: "shàngwǎng",
      simplified: "上网",
      traditional: "上網",
    },
    {
      english: "Get angry",
      pinyin: "shēngqì",
      simplified: "生气",
      traditional: "生氣",
    },
    {
      english: "Voice",
      pinyin: "shēngyīn",
      simplified: "声音",
      traditional: "聲音",
    },
    {
      english: "Make",
      pinyin: "shǐ",
      simplified: "使",
      traditional: "使",
    },
    {
      english: "World",
      pinyin: "shìjiè",
      simplified: "世界",
      traditional: "世界",
    },
    {
      english: "Thin",
      pinyin: "shòu",
      simplified: "瘦",
      traditional: "瘦",
    },
    {
      english: "Comfortable",
      pinyin: "shūfu",
      simplified: "舒服",
      traditional: "舒服",
    },
    {
      english: "Uncle",
      pinyin: "shūshu",
      simplified: "叔叔",
      traditional: "叔叔",
    },
    {
      english: "Tree",
      pinyin: "shù",
      simplified: "树",
      traditional: "樹",
    },
    {
      english: "Mathematics",
      pinyin: "shùxué",
      simplified: "数学",
      traditional: "數學",
    },
    {
      english: "Brush one's teeth",
      pinyin: "shuāyá",
      simplified: "刷牙",
      traditional: "刷牙",
    },
    {
      english: "Double, pair",
      pinyin: "shuāng",
      simplified: "双",
      traditional: "雙",
    },
    {
      english: "Level",
      pinyin: "shuǐpíng",
      simplified: "水平",
      traditional: "水平",
    },
    {
      english: "Driver",
      pinyin: "sījī",
      simplified: "司机",
      traditional: "司機",
    },
    {
      english: "Although",
      pinyin: "suīrán",
      simplified: "虽然",
      traditional: "雖然",
    },
    {
      english: "Sun",
      pinyin: "tàiyáng",
      simplified: "太阳",
      traditional: "太陽",
    },
    {
      english: "Sugar",
      pinyin: "táng",
      simplified: "糖",
      traditional: "糖",
    },
    {
      english: "Especially",
      pinyin: "tèbié",
      simplified: "特别",
      traditional: "特別",
    },
    {
      english: "Hurt",
      pinyin: "téng",
      simplified: "疼",
      traditional: "疼",
    },
    {
      english: "Increase",
      pinyin: "tígāo",
      simplified: "提高",
      traditional: "提高",
    },
    {
      english: "Sports",
      pinyin: "tǐyù",
      simplified: "体育",
      traditional: "體育",
    },
    {
      english: "Sweet",
      pinyin: "tián",
      simplified: "甜",
      traditional: "甜",
    },
    {
      english: "Strip",
      pinyin: "tiáo",
      simplified: "条",
      traditional: "條",
    },
    {
      english: "Colleague",
      pinyin: "tóngshì",
      simplified: "同事",
      traditional: "同事",
    },
    {
      english: "Agree",
      pinyin: "tóngyì",
      simplified: "同意",
      traditional: "同意",
    },
    {
      english: "Hair",
      pinyin: "tóufa",
      simplified: "头发",
      traditional: "頭髮",
    },
    {
      english: "Suddenly",
      pinyin: "tūrán",
      simplified: "突然",
      traditional: "突然",
    },
    {
      english: "Library",
      pinyin: "túshūguǎn",
      simplified: "图书馆",
      traditional: "圖書館",
    },
    {
      english: "Leg",
      pinyin: "tuǐ",
      simplified: "腿",
      traditional: "腿",
    },
    {
      english: "Complete",
      pinyin: "wánchéng",
      simplified: "完成",
      traditional: "完成",
    },
    {
      english: "Bowl",
      pinyin: "wǎn",
      simplified: "碗",
      traditional: "碗",
    },
    {
      english: "Ten thousand",
      pinyin: "wàn",
      simplified: "万",
      traditional: "萬",
    },
    {
      english: "Forget",
      pinyin: "wàngjì",
      simplified: "忘记",
      traditional: "忘記",
    },
    {
      english: "For",
      pinyin: "wèi",
      simplified: "为",
      traditional: "為",
    },
    {
      english: "In order to",
      pinyin: "wèile",
      simplified: "为了",
      traditional: "為了",
    },
    {
      english: "Position",
      pinyin: "wèi",
      simplified: "位",
      traditional: "位",
    },
    {
      english: "Culture",
      pinyin: "wénhuà",
      simplified: "文化",
      traditional: "文化",
    },
    {
      english: "West",
      pinyin: "xī",
      simplified: "西",
      traditional: "西",
    },
    {
      english: "Habit",
      pinyin: "xíguàn",
      simplified: "习惯",
      traditional: "習慣",
    },
    {
      english: "Restroom",
      pinyin: "xǐshǒujiān",
      simplified: "洗手间",
      traditional: "洗手間",
    },
    {
      english: "Take a shower",
      pinyin: "xǐzǎo",
      simplified: "洗澡",
      traditional: "洗澡",
    },
    {
      english: "Summer",
      pinyin: "xià",
      simplified: "夏",
      traditional: "夏天",
    },
    {
      english: "First",
      pinyin: "xiān",
      simplified: "先",
      traditional: "先",
    },
    {
      english: "Banana",
      pinyin: "xiāngjiāo",
      simplified: "香蕉",
      traditional: "香蕉",
    },
    {
      english: "Identical",
      pinyin: "xiāngtóng",
      simplified: "相同",
      traditional: "相同",
    },
    {
      english: "Believe",
      pinyin: "xiāngxìn",
      simplified: "相信",
      traditional: "相信",
    },
    {
      english: "Image",
      pinyin: "xiàng",
      simplified: "像",
      traditional: "像",
    },
    {
      english: "Watch out",
      pinyin: "xiǎoxīn",
      simplified: "小心",
      traditional: "小心",
    },
    {
      english: "Principal",
      pinyin: "xiàozhǎng",
      simplified: "校长",
      traditional: "校長",
    },
    {
      english: "Shoes",
      pinyin: "xié",
      simplified: "鞋",
      traditional: "鞋",
    },
    {
      english: "News",
      pinyin: "xīnwén",
      simplified: "新闻",
      traditional: "新聞",
    },
    {
      english: "Fresh",
      pinyin: "xīnxiān",
      simplified: "新鲜",
      traditional: "新鮮",
    },
    {
      english: "Letter",
      pinyin: "xìn",
      simplified: "信",
      traditional: "信",
    },
    {
      english: "Trunk",
      pinyin: "xínglixiāng",
      simplified: "行李箱",
      traditional: "行李箱",
    },
    {
      english: "Interest",
      pinyin: "xìngqù",
      simplified: "兴趣",
      traditional: "興趣",
    },
    {
      english: "Panda",
      pinyin: "xióngmāo",
      simplified: "熊猫",
      traditional: "熊貓",
    },
    {
      english: "Need",
      pinyin: "xūyào",
      simplified: "需要",
      traditional: "需要",
    },
    {
      english: "Choice",
      pinyin: "xuǎnzé",
      simplified: "选择",
      traditional: "選擇",
    },
    {
      english: "Glasses",
      pinyin: "yǎnjìng",
      simplified: "眼镜",
      traditional: "眼鏡",
    },
    {
      english: "Requirement",
      pinyin: "yāoqiú",
      simplified: "要求",
      traditional: "要求",
    },
    {
      english: "Grandpa",
      pinyin: "yéye",
      simplified: "爷爷",
      traditional: "爺爺",
    },
    {
      english: "Certain",
      pinyin: "yídìng",
      simplified: "一定",
      traditional: "一定",
    },
    {
      english: "Altogether",
      pinyin: "yígòng",
      simplified: "一共",
      traditional: "一共",
    },
    {
      english: "A while",
      pinyin: "yíhuìr",
      simplified: "一会儿",
      traditional: "一會兒",
    },
    {
      english: "Equally",
      pinyin: "yíyàng",
      simplified: "一样",
      traditional: "一樣",
    },
    {
      english: "In the future",
      pinyin: "yǐhòu",
      simplified: "以后",
      traditional: "以後",
    },
    {
      english: "Before",
      pinyin: "yǐqián",
      simplified: "以前",
      traditional: "以前",
    },
    {
      english: "Think",
      pinyin: "yǐwéi",
      simplified: "以为",
      traditional: "以為",
    },
    {
      english: "Commonly",
      pinyin: "yìbān",
      simplified: "一般",
      traditional: "一般",
    },
    {
      english: "One side",
      pinyin: "yìbiān",
      simplified: "一边",
      traditional: "一邊",
    },
    {
      english: "Always",
      pinyin: "yìzhí",
      simplified: "一直",
      traditional: "一直",
    },
    {
      english: "Music",
      pinyin: "yīnyuè",
      simplified: "音乐",
      traditional: "音樂",
    },
    {
      english: "Bank",
      pinyin: "yínháng",
      simplified: "银行",
      traditional: "銀行",
    },
    {
      english: "Should",
      pinyin: "yīnggāi",
      simplified: "应该",
      traditional: "應該",
    },
    {
      english: "Influence",
      pinyin: "yǐngxiǎng",
      simplified: "影响",
      traditional: "影響",
    },
    {
      english: "Use",
      pinyin: "yòng",
      simplified: "用",
      traditional: "用",
    },
    {
      english: "Game",
      pinyin: "yóuxì",
      simplified: "游戏",
      traditional: "遊戲",
    },
    {
      english: "Famous",
      pinyin: "yǒumíng",
      simplified: "有名",
      traditional: "名譽",
    },
    {
      english: "Again",
      pinyin: "yòu",
      simplified: "又",
      traditional: "又",
    },
    {
      english: "Encounter",
      pinyin: "yùdào",
      simplified: "遇到",
      traditional: "遇到",
    },
    {
      english: "Be willing",
      pinyin: "yuànyì",
      simplified: "愿意",
      traditional: "願意",
    },
    {
      english: "Moon",
      pinyin: "yuèliang",
      simplified: "月亮",
      traditional: "月亮",
    },
    {
      english: "The more",
      pinyin: "yuè",
      simplified: "越",
      traditional: "越",
    },
    {
      english: "Cloud",
      pinyin: "yún",
      simplified: "云",
      traditional: "雲",
    },
    {
      english: "Station",
      pinyin: "zhàn",
      simplified: "站",
      traditional: "站",
    },
    {
      english: "Worry",
      pinyin: "zháojí",
      simplified: "着急",
      traditional: "著急",
    },
    {
      english: "Look after",
      pinyin: "zhàogù",
      simplified: "照顾",
      traditional: "照顧",
    },
    {
      english: "Photo",
      pinyin: "zhàopiàn",
      simplified: "照片",
      traditional: "照片",
    },
    {
      english: "Camera",
      pinyin: "zhàoxiàngjī",
      simplified: "照相机",
      traditional: "照相機",
    },
    {
      english: "Only",
      pinyin: "zhǐ",
      simplified: "只",
      traditional: "只",
    },
    {
      english: "Middle",
      pinyin: "zhōngjiān",
      simplified: "中间",
      traditional: "中間",
    },
    {
      english: "Finally",
      pinyin: "zhōngyú",
      simplified: "终于",
      traditional: "終於",
    },
    {
      english: "Species",
      pinyin: "zhǒng",
      simplified: "种",
      traditional: "種",
    },
    {
      english: "Important",
      pinyin: "zhòngyào",
      simplified: "重要",
      traditional: "重要",
    },
    {
      english: "Weekend",
      pinyin: "zhōumò",
      simplified: "周末",
      traditional: "週末",
    },
    {
      english: "Main",
      pinyin: "zhǔyào",
      simplified: "主要",
      traditional: "主要",
    },
    {
      english: "Wish",
      pinyin: "zhù",
      simplified: "祝",
      traditional: "祝",
    },
    {
      english: "Be careful",
      pinyin: "zhùyì",
      simplified: "注意",
      traditional: "注意",
    },
    {
      english: "Dictionaries",
      pinyin: "zìdiǎn",
      simplified: "字典",
      traditional: "字典",
    },
    {
      english: "Own, self",
      pinyin: "zìjǐ",
      simplified: "自己",
      traditional: "自己",
    },
    {
      english: "Always",
      pinyin: "zǒngshì",
      simplified: "总是",
      traditional: "總是",
    },
    {
      english: "Lately",
      pinyin: "zuìjìn",
      simplified: "最近",
      traditional: "最近",
    },
    {
      english: "Task",
      pinyin: "zuòyè",
      simplified: "作业",
      traditional: "作業",
    },
  ],
};

export default lesson3;
