import type HskList from "~/types/HskList";

const lesson2: HskList = {
  id: "hmcs97kF5",
  level: 2,
  words: [
    {
      simplified: "报纸",
      traditional: "報紙",
      pinyin: "bàozhǐ",
      english: "Newspaper",
    },
    {
      simplified: "人",
      traditional: "人",
      pinyin: "rén",
      english: "Person",
    },
    {
      simplified: "名字",
      traditional: "名字",
      pinyin: "míngzì",
      english: "Name",
    },
    {
      simplified: "书",
      traditional: "書",
      pinyin: "shū",
      english: "Book",
    },
    {
      simplified: "汉语",
      traditional: "漢語",
      pinyin: "hànyǔ",
      english: "Chinese",
    },
    {
      simplified: "字",
      traditional: "字",
      pinyin: "zì",
      english: "Character",
    },
    {
      simplified: "桌子",
      traditional: "桌子",
      pinyin: "zhuōzi",
      english: "Desk",
    },
    {
      simplified: "椅子",
      traditional: "椅子",
      pinyin: "yǐzi",
      english: "Chair",
    },
    {
      simplified: "门",
      traditional: "門",
      pinyin: "mén",
      english: "Door",
    },
    {
      simplified: "题",
      traditional: "題",
      pinyin: "tí",
      english: "Topic",
    },
    {
      simplified: "课",
      traditional: "課",
      pinyin: "kè",
      english: "Lesson",
    },
    {
      simplified: "姓",
      traditional: "姓",
      pinyin: "xìng",
      english: "Surname",
    },
    {
      simplified: "问题",
      traditional: "問題",
      pinyin: "wèntí",
      english: "Question",
    },
    {
      simplified: "事情",
      traditional: "事情",
      pinyin: "shìqing",
      english: "Matter",
    },
    {
      simplified: "考试",
      traditional: "考試",
      pinyin: "kǎoshì",
      english: "Exam",
    },
    {
      simplified: "票",
      traditional: "票",
      pinyin: "piào",
      english: "Ticket",
    },
    {
      simplified: "意思",
      traditional: "意思",
      pinyin: "yìsi",
      english: "Meaning",
    },
    {
      simplified: "颜色",
      traditional: "顏色",
      pinyin: "yánsè",
      english: "Color",
    },
    {
      simplified: "谢谢",
      traditional: "謝謝",
      pinyin: "xièxie",
      english: "Thank",
    },
    {
      simplified: "不客气",
      traditional: "不客氣",
      pinyin: "búkèqì",
      english: "You are welcome",
    },
    {
      simplified: "再见",
      traditional: "再見",
      pinyin: "zàijiàn",
      english: "Good-bye",
    },
    {
      simplified: "请",
      traditional: "請",
      pinyin: "qǐng",
      english: "Please",
    },
    {
      simplified: "对不起",
      traditional: "對不起",
      pinyin: "duìbùqǐ",
      english: "Sorry",
    },
    {
      simplified: "没关系",
      traditional: "沒關係",
      pinyin: "méiguānxi",
      english: "It doesn't matter",
    },
    {
      simplified: "欢迎",
      traditional: "歡迎",
      pinyin: "huānyíng",
      english: "Welcome",
    },
    {
      simplified: "是",
      traditional: "是",
      pinyin: "shì",
      english: "Am, is, are",
    },
    {
      simplified: "有",
      traditional: "有",
      pinyin: "yǒu",
      english: "Have",
    },
    {
      simplified: "看",
      traditional: "看",
      pinyin: "kàn",
      english: "Look",
    },
    {
      simplified: "听",
      traditional: "聽",
      pinyin: "tīng",
      english: "Listen",
    },
    {
      simplified: "说话",
      traditional: "說話",
      pinyin: "shuōhuà",
      english: "Speak",
    },
    {
      simplified: "读",
      traditional: "讀",
      pinyin: "dú",
      english: "Read",
    },
    {
      simplified: "写",
      traditional: "寫",
      pinyin: "xiě",
      english: "Write",
    },
    {
      simplified: "看见",
      traditional: "看見",
      pinyin: "kànjiàn",
      english: "See",
    },
    {
      simplified: "叫",
      traditional: "叫",
      pinyin: "jiào",
      english: "Call",
    },
    {
      simplified: "来",
      traditional: "來",
      pinyin: "lái",
      english: "Come",
    },
    {
      simplified: "回",
      traditional: "時",
      pinyin: "huí",
      english: "Return",
    },
    {
      simplified: "去",
      traditional: "去",
      pinyin: "qù",
      english: "Go",
    },
    {
      simplified: "吃",
      traditional: "吃",
      pinyin: "chī",
      english: "Eat",
    },
    {
      simplified: "喝",
      traditional: "喝",
      pinyin: "hē",
      english: "Drink",
    },
    {
      simplified: "睡觉",
      traditional: "睡覺",
      pinyin: "shuìjiào",
      english: "Sleep",
    },
    {
      simplified: "认识",
      traditional: "認識",
      pinyin: "rènshi",
      english: "Know",
    },
    {
      simplified: "打电话",
      traditional: "打電話",
      pinyin: "dǎdiànhuà",
      english: "Call up",
    },
    {
      simplified: "做",
      traditional: "做",
      pinyin: "zuò",
      english: "Do",
    },
    {
      simplified: "高兴",
      traditional: "高興",
      pinyin: "gāoxìng",
      english: "Happy",
    },
    {
      simplified: "买",
      traditional: "買",
      pinyin: "mǎi",
      english: "Buy",
    },
    {
      simplified: "开",
      traditional: "開",
      pinyin: "kāi",
      english: "Open",
    },
    {
      simplified: "坐",
      traditional: "坐",
      pinyin: "zuò",
      english: "Sit",
    },
    {
      simplified: "住",
      traditional: "住",
      pinyin: "zhù",
      english: "Live",
    },
    {
      simplified: "学习",
      traditional: "學習",
      pinyin: "xuéxí",
      english: "Study",
    },
    {
      simplified: "工作",
      traditional: "工作",
      pinyin: "gōngzuò",
      english: "Work",
    },
    {
      simplified: "下雨",
      traditional: "下雨",
      pinyin: "xiàyǔ",
      english: "Rain",
    },
    {
      simplified: "问",
      traditional: "問",
      pinyin: "wèn",
      english: "Ask",
    },
    {
      simplified: "走",
      traditional: "走",
      pinyin: "zǒu",
      english: "Walk",
    },
    {
      simplified: "进",
      traditional: "進",
      pinyin: "jìn",
      english: "Enter",
    },
    {
      simplified: "出",
      traditional: "出",
      pinyin: "chū",
      english: "Come",
    },
    {
      simplified: "跑步",
      traditional: "跑步",
      pinyin: "pǎobù",
      english: "Run",
    },
    {
      simplified: "到",
      traditional: "到",
      pinyin: "dào",
      english: "Arrive",
    },
    {
      simplified: "穿",
      traditional: "穿",
      pinyin: "chuān",
      english: "Wear",
    },
    {
      simplified: "洗",
      traditional: "洗",
      pinyin: "xǐ",
      english: "Wash",
    },
    {
      simplified: "给",
      traditional: "給",
      pinyin: "gěi",
      english: "Give",
    },
    {
      simplified: "找",
      traditional: "找",
      pinyin: "zhǎo",
      english: "Find",
    },
    {
      simplified: "懂",
      traditional: "懂",
      pinyin: "dǒng",
      english: "Understand",
    },
    {
      simplified: "笑",
      traditional: "笑",
      pinyin: "xiào",
      english: "Smile",
    },
    {
      simplified: "回答",
      traditional: "回答",
      pinyin: "huídá",
      english: "Answer",
    },
    {
      simplified: "告诉",
      traditional: "告訴",
      pinyin: "gàosù",
      english: "Tell",
    },
    {
      simplified: "准备",
      traditional: "準備",
      pinyin: "zhǔnbèi",
      english: "Prepare",
    },
    {
      simplified: "开始",
      traditional: "開始",
      pinyin: "kāishǐ",
      english: "Begin",
    },
    {
      simplified: "介绍",
      traditional: "介紹",
      pinyin: "jièshào",
      english: "Introduce",
    },
    {
      simplified: "帮助",
      traditional: "幫助",
      pinyin: "bāngzhù",
      english: "Help",
    },
    {
      simplified: "玩",
      traditional: "玩",
      pinyin: "wán",
      english: "Play",
    },
    {
      simplified: "送",
      traditional: "送",
      pinyin: "sòng",
      english: "Present",
    },
    {
      simplified: "等",
      traditional: "等",
      pinyin: "děng",
      english: "Wait",
    },
    {
      simplified: "让",
      traditional: "讓",
      pinyin: "ràng",
      english: "Let",
    },
    {
      simplified: "起床",
      traditional: "起床",
      pinyin: "qǐchuáng",
      english: "Get up",
    },
    {
      simplified: "唱歌",
      traditional: "唱歌",
      pinyin: "chànggē",
      english: "Sing",
    },
    {
      simplified: "跳舞",
      traditional: "跳舞",
      pinyin: "tiàowǔ",
      english: "Dance",
    },
    {
      simplified: "旅游",
      traditional: "旅遊",
      pinyin: "lǚyóu",
      english: "Travel",
    },
    {
      simplified: "上班",
      traditional: "上班",
      pinyin: "shàngbān",
      english: "Be on duty",
    },
    {
      simplified: "生病",
      traditional: "生病",
      pinyin: "shēngbìng",
      english: "Fall ill",
    },
    {
      simplified: "休息",
      traditional: "休息",
      pinyin: "xiūxi",
      english: "Rest",
    },
    {
      simplified: "运动",
      traditional: "運動",
      pinyin: "yùndòng",
      english: "Exercise",
    },
    {
      simplified: "游泳",
      traditional: "游泳",
      pinyin: "yóuyǒng",
      english: "Swim",
    },
    {
      simplified: "踢足球",
      traditional: "踢足球",
      pinyin: "tīzúqiú",
      english: "Play footbal",
    },
    {
      simplified: "打篮球",
      traditional: "打籃球",
      pinyin: "dǎlánqiú",
      english: "Play basketball",
    },
    {
      simplified: "完",
      traditional: "完",
      pinyin: "wán",
      english: "Finish",
    },
    {
      simplified: "爱",
      traditional: "愛",
      pinyin: "ài",
      english: "Love",
    },
    {
      simplified: "喜欢",
      traditional: "喜歡",
      pinyin: "xǐhuān",
      english: "Love, like",
    },
    {
      simplified: "想",
      traditional: "想",
      pinyin: "xiǎng",
      english: "Want",
    },
    {
      simplified: "觉得",
      traditional: "覺得",
      pinyin: "juédé",
      english: "Think",
    },
    {
      simplified: "知道",
      traditional: "知道",
      pinyin: "zhīdao",
      english: "Know",
    },
    {
      simplified: "希望",
      traditional: "希望",
      pinyin: "xīwàng",
      english: "Hope",
    },
    {
      simplified: "能",
      traditional: "能",
      pinyin: "néng",
      english: "Can, be able to",
    },
    {
      simplified: "可以",
      traditional: "可以",
      pinyin: "kěyǐ",
      english: "Can",
    },
    {
      simplified: "要",
      traditional: "要",
      pinyin: "yào",
      english: "Ask for",
    },
    {
      simplified: "可能",
      traditional: "可能",
      pinyin: "kěnéng",
      english: "May",
    },
    {
      simplified: "好",
      traditional: "好",
      pinyin: "hǎo",
      english: "Good",
    },
    {
      simplified: "大",
      traditional: "大",
      pinyin: "dà",
      english: "Big",
    },
    {
      simplified: "小",
      traditional: "小",
      pinyin: "xiǎo",
      english: "Small",
    },
    {
      simplified: "多",
      traditional: "多",
      pinyin: "duō",
      english: "Many, much",
    },
    {
      simplified: "少",
      traditional: "少",
      pinyin: "shǎo",
      english: "Few, little",
    },
    {
      simplified: "冷",
      traditional: "冷",
      pinyin: "lěng",
      english: "Cold",
    },
    {
      simplified: "热",
      traditional: "熱",
      pinyin: "rè",
      english: "Hot",
    },
    {
      simplified: "漂亮",
      traditional: "漂亮",
      pinyin: "piàoliang",
      english: "Beautiful",
    },
    {
      simplified: "高",
      traditional: "高",
      pinyin: "gāo",
      english: "Tall",
    },
    {
      simplified: "红",
      traditional: "紅",
      pinyin: "hóng",
      english: "Red",
    },
    {
      simplified: "白",
      traditional: "白",
      pinyin: "bái",
      english: "White",
    },
    {
      simplified: "黑",
      traditional: "黑",
      pinyin: "hēi",
      english: "Black",
    },
    {
      simplified: "忙",
      traditional: "忙",
      pinyin: "máng",
      english: "Busy",
    },
    {
      simplified: "快",
      traditional: "快",
      pinyin: "kuài",
      english: "Fast",
    },
    {
      simplified: "慢",
      traditional: "慢",
      pinyin: "màn",
      english: "Slow",
    },
    {
      simplified: "远",
      traditional: "遠",
      pinyin: "yuǎn",
      english: "Far",
    },
    {
      simplified: "近",
      traditional: "近",
      pinyin: "jìn",
      english: "Close",
    },
    {
      simplified: "好吃",
      traditional: "好吃",
      pinyin: "hǎochī",
      english: "Delicioous",
    },
    {
      simplified: "累",
      traditional: "累",
      pinyin: "lèi",
      english: "Tired",
    },
    {
      simplified: "长",
      traditional: "長",
      pinyin: "cháng",
      english: "Long",
    },
    {
      simplified: "新",
      traditional: "新",
      pinyin: "xīn",
      english: "New",
    },
    {
      simplified: "贵",
      traditional: "貴",
      pinyin: "guì",
      english: "Expensive",
    },
    {
      simplified: "便宜",
      traditional: "便宜",
      pinyin: "piányi",
      english: "Cheap",
    },
    {
      simplified: "晴",
      traditional: "晴",
      pinyin: "qíng",
      english: "Fine",
    },
    {
      simplified: "阴",
      traditional: "陰",
      pinyin: "yīn",
      english: "Cloudy",
    },
    {
      simplified: "错",
      traditional: "錯",
      pinyin: "cuò",
      english: "Wrong",
    },
    {
      simplified: "快乐",
      traditional: "快樂",
      pinyin: "kuàilè",
      english: "Happy",
    },
    {
      simplified: "会",
      traditional: "會",
      pinyin: "huì",
      english: "Can",
    },

    {
      simplified: "打鸡血",
      traditional: "打雞血",
      pinyin: "dǎ jī xuè",
      english: "Become excited",
    },
    {
      simplified: "萌萌哒",
      traditional: "萌萌噠",
      pinyin: "méng méng dá",
      english: "Cute or adorable",
    },
    {
      simplified: "老板",
      traditional: "老闆",
      pinyin: "lǎobǎn",
      english: "Boss",
    },
    {
      simplified: "辣眼睛",
      traditional: "辣眼睛",
      pinyin: "là yǎnjīng",
      english: "Spicy eyes (an eyesore)",
    },
    {
      simplified: "方了",
      traditional: "方了",
      pinyin: "fāngle",
      english: "To panic",
    },
    {
      simplified: "接地气",
      traditional: "接地氣",
      pinyin: "Jiēdì qì",
      english: "Down to Earth",
    },
    {
      simplified: "一脸懵逼",
      traditional: "一臉懵逼",
      pinyin: "yī liǎn měng bī",
      english: "To feel completely lost",
    },
  ],
};

export default lesson2;
