import type HskList from "~/types/HskList";

const lesson4: HskList = {
  id: "aZuy5YQTO5",
  level: 4,
  words: [
    {
      english: "Love",
      pinyin: "àiqíng",
      simplified: "爱情",
      traditional: "愛情",
    },
    {
      english: "Arrange",
      pinyin: "ānpái",
      simplified: "安排",
      traditional: "安排",
    },
    {
      english: "Security",
      pinyin: "ānquán",
      simplified: "安全",
      traditional: "安全",
    },
    {
      english: "Dark",
      pinyin: "àn",
      simplified: "暗",
      traditional: "暗",
    },
    {
      english: "On time",
      pinyin: "ànshí",
      simplified: "按时",
      traditional: "按時",
    },
    {
      english: "According to",
      pinyin: "ànzhào",
      simplified: "按照",
      traditional: "按照",
    },
    {
      english: "Include",
      pinyin: "bāokuò",
      simplified: "包括",
      traditional: "包括",
    },
    {
      english: "Protect",
      pinyin: "bǎohù",
      simplified: "保护",
      traditional: "保護",
    },
    {
      english: "Ensure",
      pinyin: "bǎozhèng",
      simplified: "保证",
      traditional: "保證",
    },
    {
      english: "Hold",
      pinyin: "bào",
      simplified: "抱",
      traditional: "抱",
    },
    {
      english: "Feel sorry",
      pinyin: "bàoqiàn",
      simplified: "抱歉",
      traditional: "抱歉",
    },
    {
      english: "Report",
      pinyin: "bàodào",
      simplified: "报道",
      traditional: "報導",
    },
    {
      english: "Sign up",
      pinyin: "bàomíng",
      simplified: "报名",
      traditional: "報名",
    },
    {
      english: "Times",
      pinyin: "bèi",
      simplified: "倍",
      traditional: "倍",
    },
    {
      english: "Originally",
      pinyin: "běnlái",
      simplified: "本来",
      traditional: "本來",
    },
    {
      english: "Stupid",
      pinyin: "bèn",
      simplified: "笨",
      traditional: "笨",
    },
    {
      english: "Notebook",
      pinyin: "bǐjìběn",
      simplified: "笔记本",
      traditional: "筆記本",
    },
    {
      english: "Graduation",
      pinyin: "bìyè",
      simplified: "毕业",
      traditional: "畢業",
    },
    {
      english: "Times, all over",
      pinyin: "biàn",
      simplified: "遍",
      traditional: "遍",
    },
    {
      english: "Standard",
      pinyin: "biāozhǔn",
      simplified: "标准",
      traditional: "標準",
    },
    {
      english: "Expression",
      pinyin: "biǎodá",
      simplified: "表达",
      traditional: "表達",
    },
    {
      english: "Form",
      pinyin: "biǎogé",
      simplified: "表格",
      traditional: "表格",
    },
    {
      english: "Praise",
      pinyin: "biǎoyáng",
      simplified: "表扬",
      traditional: "表揚",
    },
    {
      english: "Biscuits",
      pinyin: "bǐnggān",
      simplified: "饼干",
      traditional: "餅乾",
    },
    {
      english: "Also",
      pinyin: "bìngqiě",
      simplified: "并且",
      traditional: "並且",
    },
    {
      english: "Doctor",
      pinyin: "bóshì",
      simplified: "博士",
      traditional: "博士",
    },
    {
      english: "Not only",
      pinyin: "búdàn",
      simplified: "不但",
      traditional: "不但",
    },
    {
      english: "However",
      pinyin: "búguò",
      simplified: "不过",
      traditional: "不過",
    },
    {
      english: "Have to",
      pinyin: "bùdébù",
      simplified: "不得不",
      traditional: "不得不",
    },
    {
      english: "No matter",
      pinyin: "bùguǎn",
      simplified: "不管",
      traditional: "不管",
    },
    {
      english: "Not only",
      pinyin: "bùjǐn",
      simplified: "不仅",
      traditional: "不僅",
    },
    {
      english: "Part",
      pinyin: "bùfen",
      simplified: "部分",
      traditional: "部分",
    },
    {
      english: "Wipe",
      pinyin: "cā",
      simplified: "擦",
      traditional: "擦",
    },
    {
      english: "Guess",
      pinyin: "cāi",
      simplified: "猜",
      traditional: "猜",
    },
    {
      english: "Material Science",
      pinyin: "cáiliào",
      simplified: "材料",
      traditional: "材料",
    },
    {
      english: "Visit",
      pinyin: "cānguān",
      simplified: "参观",
      traditional: "參觀",
    },
    {
      english: "Almost",
      pinyin: "chàbuduō",
      simplified: "差不多",
      traditional: "差不多",
    },
    {
      english: "Taste",
      pinyin: "cháng",
      simplified: "尝",
      traditional: "嘗",
    },
    {
      english: "The Great Wall",
      pinyin: "chángchéng",
      simplified: "长城",
      traditional: "長城",
    },
    {
      english: "The Yangtze River",
      pinyin: "chángjiāng",
      simplified: "长江",
      traditional: "長江",
    },
    {
      english: "Site",
      pinyin: "chǎng",
      simplified: "场",
      traditional: "場",
    },
    {
      english: "Exceed",
      pinyin: "chāoguò",
      simplified: "超过",
      traditional: "超過",
    },
    {
      english: "Noisy",
      pinyin: "chǎo",
      simplified: "吵",
      traditional: "吵",
    },
    {
      english: "Success",
      pinyin: "chénggōng",
      simplified: "成功",
      traditional: "成功",
    },
    {
      english: "Mature",
      pinyin: "chéngshú",
      simplified: "成熟",
      traditional: "成熟",
    },
    {
      english: "Become",
      pinyin: "chéngwéi",
      simplified: "成为",
      traditional: "成為",
    },
    {
      english: "Honest",
      pinyin: "chéngshí",
      simplified: "诚实",
      traditional: "誠實",
    },
    {
      english: "Ride",
      pinyin: "chéngzuò",
      simplified: "乘坐",
      traditional: "乘坐",
    },
    {
      english: "Be amazed",
      pinyin: "chījīng",
      simplified: "吃惊",
      traditional: "吃驚",
    },
    {
      english: "Again",
      pinyin: "chóngxīn",
      simplified: "重新",
      traditional: "重新",
    },
    {
      english: "Smoking",
      pinyin: "chōuyān",
      simplified: "抽烟",
      traditional: "抽煙",
    },
    {
      english: "A business travel",
      pinyin: "chūchāi",
      simplified: "出差",
      traditional: "出差",
    },
    {
      english: "Set out",
      pinyin: "chūfā",
      simplified: "出发",
      traditional: "出發",
    },
    {
      english: "Birth",
      pinyin: "chūshēng",
      simplified: "出生",
      traditional: "出生",
    },
    {
      english: "Fax",
      pinyin: "chuánzhēn",
      simplified: "传真",
      traditional: "傳真",
    },
    {
      english: "Window",
      pinyin: "chuānghu",
      simplified: "窗户",
      traditional: "窗戶",
    },
    {
      english: "Dictionary",
      pinyin: "cídiǎn",
      simplified: "词典",
      traditional: "詞典",
    },
    {
      english: "Always",
      pinyin: "cónglái",
      simplified: "从来",
      traditional: "從來",
    },
    {
      english: "Careless",
      pinyin: "cūxīn",
      simplified: "粗心",
      traditional: "粗心",
    },
    {
      english: "Answer",
      pinyin: "dá'àn",
      simplified: "答案",
      traditional: "答案",
    },
    {
      english: "Dress up",
      pinyin: "dǎban",
      simplified: "打扮",
      traditional: "打扮",
    },
    {
      english: "Disturb",
      pinyin: "dǎrǎo",
      simplified: "打扰",
      traditional: "打擾",
    },
    {
      english: "Print",
      pinyin: "dǎyìn",
      simplified: "打印",
      traditional: "打印",
    },
    {
      english: "Discount",
      pinyin: "dǎzhé",
      simplified: "打折",
      traditional: "打折",
    },
    {
      english: "To make an injection",
      pinyin: "dǎzhēn",
      simplified: "打针",
      traditional: "打針",
    },
    {
      english: "Probably",
      pinyin: "dàgài",
      simplified: "大概",
      traditional: "大概",
    },
    {
      english: "Embassy",
      pinyin: "dàshǐguǎn",
      simplified: "大使馆",
      traditional: "大使館",
    },
    {
      english: "About",
      pinyin: "dàyuē",
      simplified: "大约",
      traditional: "大約",
    },
    {
      english: "Wear",
      pinyin: "dài",
      simplified: "戴",
      traditional: "戴",
    },
    {
      english: "Representative",
      pinyin: "dàibiǎo",
      simplified: "代表",
      traditional: "代表",
    },
    {
      english: "Replace",
      pinyin: "dàitì",
      simplified: "代替",
      traditional: "代替",
    },
    {
      english: "Doctor",
      pinyin: "dàifu",
      simplified: "大夫",
      traditional: "大夫",
    },
    {
      english: "When",
      pinyin: "dāng",
      simplified: "当",
      traditional: "當",
    },
    {
      english: "Local",
      pinyin: "dāngdì",
      simplified: "当地",
      traditional: "當地",
    },
    {
      english: "At that time",
      pinyin: "dāngshí",
      simplified: "当时",
      traditional: "當時",
    },
    {
      english: "Knife",
      pinyin: "dāo",
      simplified: "刀",
      traditional: "刀",
    },
    {
      english: "Guide",
      pinyin: "dǎoyóu",
      simplified: "导游",
      traditional: "導遊",
    },
    {
      english: "Everywhere",
      pinyin: "dàochù",
      simplified: "到处",
      traditional: "到處",
    },
    {
      english: "To the end",
      pinyin: "dàodǐ",
      simplified: "到底",
      traditional: "到底",
    },
    {
      english: "Apologize",
      pinyin: "dàoqiàn",
      simplified: "道歉",
      traditional: "道歉",
    },
    {
      english: "Proud",
      pinyin: "déyì",
      simplified: "得意",
      traditional: "擅長",
    },
    {
      english: "Have to",
      pinyin: "děi",
      simplified: "得",
      traditional: "得",
    },
    {
      english: "Bottom",
      pinyin: "dǐ",
      simplified: "底",
      traditional: "底",
    },
    {
      english: "Earth",
      pinyin: "dìqiú",
      simplified: "地球",
      traditional: "地球",
    },
    {
      english: "Address",
      pinyin: "dìzhǐ",
      simplified: "地址",
      traditional: "地址",
    },
    {
      english: "Fall",
      pinyin: "diào",
      simplified: "掉",
      traditional: "掉",
    },
    {
      english: "Investigation",
      pinyin: "diàochá",
      simplified: "调查",
      traditional: "調查",
    },
    {
      english: "Lose",
      pinyin: "diū",
      simplified: "丢",
      traditional: "丟",
    },
    {
      english: "Action",
      pinyin: "dòngzuò",
      simplified: "动作",
      traditional: "動作",
    },
    {
      english: "Traffic jam",
      pinyin: "dǔchē",
      simplified: "堵车",
      traditional: "堵車",
    },
    {
      english: "Belly",
      pinyin: "dùzi",
      simplified: "肚子",
      traditional: "肚子",
    },
    {
      english: "Break",
      pinyin: "duàn",
      simplified: "断",
      traditional: "斷",
    },
    {
      english: "Dialogue",
      pinyin: "duìhuà",
      simplified: "对话",
      traditional: "對話",
    },
    {
      english: "Opposite side",
      pinyin: "duìmiàn",
      simplified: "对面",
      traditional: "對面",
    },
    {
      english: "Meal",
      pinyin: "dùn",
      simplified: "顿",
      traditional: "頓",
    },
    {
      english: "Classifier of flower",
      pinyin: "duǒ",
      simplified: "朵",
      traditional: "朵",
    },
    {
      english: "And",
      pinyin: "ér",
      simplified: "而",
      traditional: "而",
    },
    {
      english: "Children",
      pinyin: "értóng",
      simplified: "儿童",
      traditional: "兒童",
    },
    {
      english: "Send out",
      pinyin: "fā",
      simplified: "发",
      traditional: "發",
    },
    {
      english: "Happen",
      pinyin: "fāshēng",
      simplified: "发生",
      traditional: "發生",
    },
    {
      english: "Development",
      pinyin: "fāzhǎn",
      simplified: "发展",
      traditional: "發展",
    },
    {
      english: "Law",
      pinyin: "fǎlǜ",
      simplified: "法律",
      traditional: "法律",
    },
    {
      english: "Translate",
      pinyin: "fānyì",
      simplified: "翻译",
      traditional: "翻譯",
    },
    {
      english: "Annoyance",
      pinyin: "fánnǎo",
      simplified: "烦恼",
      traditional: "煩惱",
    },
    {
      english: "Opposition",
      pinyin: "fǎnduì",
      simplified: "反对",
      traditional: "反對",
    },
    {
      english: "Reflect",
      pinyin: "fǎnyìng",
      simplified: "反映",
      traditional: "反映",
    },
    {
      english: "Range",
      pinyin: "fànwéi",
      simplified: "范围",
      traditional: "範圍",
    },
    {
      english: "Method",
      pinyin: "fāngfǎ",
      simplified: "方法",
      traditional: "方法",
    },
    {
      english: "Aspect",
      pinyin: "fāngmiàn",
      simplified: "方面",
      traditional: "方面",
    },
    {
      english: "Direction",
      pinyin: "fāngxiàng",
      simplified: "方向",
      traditional: "方向",
    },
    {
      english: "Visit",
      pinyin: "fǎngwèn",
      simplified: "访问",
      traditional: "訪問",
    },
    {
      english: "Give up",
      pinyin: "fàngqì",
      simplified: "放弃",
      traditional: "放棄",
    },
    {
      english: "Summer vacation",
      pinyin: "fàngshǔjià",
      simplified: "放暑假",
      traditional: "放暑假",
    },
    {
      english: "Percent",
      pinyin: "fēnzhī",
      simplified: "分之",
      traditional: "分之",
    },
    {
      english: "Share (measure word)",
      pinyin: "fèn",
      simplified: "份",
      traditional: "份",
    },
    {
      english: "Rich, plentiful, abundant",
      pinyin: "fēngfù",
      simplified: "丰富",
      traditional: "豐富",
    },
    {
      english: "Scenery",
      pinyin: "fēngjǐng",
      simplified: "风景",
      traditional: "風景",
    },
    {
      english: "Otherwise",
      pinyin: "fǒuzé",
      simplified: "否则",
      traditional: "否則",
    },
    {
      english: "Accord with",
      pinyin: "fúhé",
      simplified: "符合",
      traditional: "符合",
    },
    {
      english: "Rich",
      pinyin: "fù",
      simplified: "富",
      traditional: "富",
    },
    {
      english: "Father",
      pinyin: "fùqīn",
      simplified: "父亲",
      traditional: "父親",
    },
    {
      english: "To copy",
      pinyin: "fùyìn",
      simplified: "复印",
      traditional: "複印",
    },
    {
      english: "Complex",
      pinyin: "fùzá",
      simplified: "复杂",
      traditional: "複雜",
    },
    {
      english: "Be responsible for",
      pinyin: "fùzé",
      simplified: "负责",
      traditional: "負責",
    },
    {
      english: "Change",
      pinyin: "gǎibiàn",
      simplified: "改变",
      traditional: "改變",
    },
    {
      english: "Cheers!",
      pinyin: "gānbēi",
      simplified: "干杯",
      traditional: "乾杯",
    },
    {
      english: "Dry, arid, dull",
      pinyin: "gānzào",
      simplified: "干燥",
      traditional: "乾燥",
    },
    {
      english: "Be moved",
      pinyin: "gǎndòng",
      simplified: "感动",
      traditional: "感動",
    },
    {
      english: "Feel",
      pinyin: "gǎnjué",
      simplified: "感觉",
      traditional: "感覺",
    },
    {
      english: "Feeling",
      pinyin: "gǎnqíng",
      simplified: "感情",
      traditional: "感情",
    },
    {
      english: "Thank",
      pinyin: "gǎnxiè",
      simplified: "感谢",
      traditional: "感謝",
    },
    {
      english: "Dry",
      pinyin: "gān",
      simplified: "干",
      traditional: "幹",
    },
    {
      english: "Just",
      pinyin: "gānggāng",
      simplified: "刚刚",
      traditional: "剛剛",
    },
    {
      english: "Senior",
      pinyin: "gāojí",
      simplified: "高级",
      traditional: "高級",
    },
    {
      english: "Various",
      pinyin: "gè",
      simplified: "各",
      traditional: "各",
    },
    {
      english: "Height",
      pinyin: "gèzi",
      simplified: "个子",
      traditional: "個子",
    },
    {
      english: "Kilometre",
      pinyin: "gōnglǐ",
      simplified: "公里",
      traditional: "公里",
    },
    {
      english: "Tool",
      pinyin: "gōngjù",
      simplified: "工具",
      traditional: "工具",
    },
    {
      english: "Wages",
      pinyin: "gōngzī",
      simplified: "工资",
      traditional: "工資",
    },
    {
      english: "Common",
      pinyin: "gòngtóng",
      simplified: "共同",
      traditional: "共同",
    },
    {
      english: "Enough",
      pinyin: "gòu",
      simplified: "够",
      traditional: "夠",
    },
    {
      english: "Shopping",
      pinyin: "gòuwù",
      simplified: "购物",
      traditional: "購物",
    },
    {
      english: "Alone",
      pinyin: "gūdān",
      simplified: "孤单",
      traditional: "孤單",
    },
    {
      english: "Estimate",
      pinyin: "gūjì",
      simplified: "估计",
      traditional: "估計",
    },
    {
      english: "Encourage",
      pinyin: "gǔlì",
      simplified: "鼓励",
      traditional: "鼓勵",
    },
    {
      english: "Applause",
      pinyin: "gǔzhǎng",
      simplified: "鼓掌",
      traditional: "鼓掌",
    },
    {
      english: "Customer",
      pinyin: "gùkè",
      simplified: "顾客",
      traditional: "顧客",
    },
    {
      english: "Deliberately",
      pinyin: "gùyì",
      simplified: "故意",
      traditional: "故意",
    },
    {
      english: "Hang",
      pinyin: "guà",
      simplified: "挂",
      traditional: "掛",
    },
    {
      english: "Key",
      pinyin: "guānjiàn",
      simplified: "关键",
      traditional: "關鍵",
    },
    {
      english: "Audience",
      pinyin: "guānzhòng",
      simplified: "观众",
      traditional: "觀眾",
    },
    {
      english: "Administration",
      pinyin: "guǎnlǐ",
      simplified: "管理",
      traditional: "管理",
    },
    {
      english: "Light",
      pinyin: "guāng",
      simplified: "光",
      traditional: "光",
    },
    {
      english: "Radio broadcast",
      pinyin: "guǎngbō",
      simplified: "广播",
      traditional: "廣播",
    },
    {
      english: "Advertisement",
      pinyin: "guǎnggào",
      simplified: "广告",
      traditional: "廣告",
    },
    {
      english: "Stroll",
      pinyin: "guàng",
      simplified: "逛",
      traditional: "逛",
    },
    {
      english: "Regulations",
      pinyin: "guīdìng",
      simplified: "规定",
      traditional: "規定",
    },
    {
      english: "International",
      pinyin: "guójì",
      simplified: "国际",
      traditional: "國際",
    },
    {
      english: "Sure enough",
      pinyin: "guǒrán",
      simplified: "果然",
      traditional: "果然",
    },
    {
      english: "Process",
      pinyin: "guòchéng",
      simplified: "过程",
      traditional: "過程",
    },
    {
      english: "Ocean",
      pinyin: "hǎiyáng",
      simplified: "海洋",
      traditional: "海洋",
    },
    {
      english: "Shy",
      pinyin: "hàixiū",
      simplified: "害羞",
      traditional: "害羞",
    },
    {
      english: "The winter vacation",
      pinyin: "hánjià",
      simplified: "寒假",
      traditional: "寒假",
    },
    {
      english: "Sweat",
      pinyin: "hàn",
      simplified: "汗",
      traditional: "汗",
    },
    {
      english: "Flight",
      pinyin: "hángbān",
      simplified: "航班",
      traditional: "航班",
    },
    {
      english: "Benefit",
      pinyin: "hǎochù",
      simplified: "好处",
      traditional: "好處",
    },
    {
      english: "Be like, seem",
      pinyin: "hǎoxiàng",
      simplified: "好像",
      traditional: "好像",
    },
    {
      english: "Number, size",
      pinyin: "hàomǎ",
      simplified: "号码",
      traditional: "號碼",
    },
    {
      english: "Qualified",
      pinyin: "hégé",
      simplified: "合格",
      traditional: "合格",
    },
    {
      english: "Appropriate",
      pinyin: "héshì",
      simplified: "合适",
      traditional: "合適",
    },
    {
      english: "Box",
      pinyin: "hézi",
      simplified: "盒子",
      traditional: "盒子",
    },
    {
      english: "Monkey",
      pinyin: "hóuzi",
      simplified: "猴子",
      traditional: "猴子",
    },
    {
      english: "Thick",
      pinyin: "hòu",
      simplified: "厚",
      traditional: "厚",
    },
    {
      english: "Regret",
      pinyin: "hòuhuǐ",
      simplified: "后悔",
      traditional: "後悔",
    },
    {
      english: "Later",
      pinyin: "hòulái",
      simplified: "后来",
      traditional: "後來",
    },
    {
      english: "Suddenly",
      pinyin: "hūrán",
      simplified: "忽然",
      traditional: "忽然",
    },
    {
      english: "Nurse",
      pinyin: "hùshi",
      simplified: "护士",
      traditional: "護士",
    },
    {
      english: "Each other",
      pinyin: "hùxiāng",
      simplified: "互相",
      traditional: "互相",
    },
    {
      english: "Doubt",
      pinyin: "huáiyí",
      simplified: "怀疑",
      traditional: "懷疑",
    },
    {
      english: "Memory",
      pinyin: "huíyì",
      simplified: "回忆",
      traditional: "回憶",
    },
    {
      english: "Activity",
      pinyin: "huódòng",
      simplified: "活动",
      traditional: "活動",
    },
    {
      english: "Lively",
      pinyin: "huópō",
      simplified: "活泼",
      traditional: "活潑",
    },
    {
      english: "Fire",
      pinyin: "huǒ",
      simplified: "火",
      traditional: "火",
    },
    {
      english: "Get",
      pinyin: "huòdé",
      simplified: "获得",
      traditional: "獲得",
    },
    {
      english: "Basics",
      pinyin: "jīchǔ",
      simplified: "基础",
      traditional: "基礎",
    },
    {
      english: "Excited",
      pinyin: "jīdòng",
      simplified: "激动",
      traditional: "激動",
    },
    {
      english: "Positive",
      pinyin: "jījí",
      simplified: "积极",
      traditional: "積極",
    },
    {
      english: "Accumulation",
      pinyin: "jīlěi",
      simplified: "积累",
      traditional: "積累",
    },
    {
      english: "Extremely",
      pinyin: "jíqí",
      simplified: "极其",
      traditional: "極其",
    },
    {
      english: "Aggregate",
      pinyin: "jíhé",
      simplified: "集合",
      traditional: "集合",
    },
    {
      english: "Timely",
      pinyin: "jíshí",
      simplified: "及时",
      traditional: "及時",
    },
    {
      english: "Even if",
      pinyin: "jíshǐ",
      simplified: "即使",
      traditional: "即使",
    },
    {
      english: "Send",
      pinyin: "jì",
      simplified: "寄",
      traditional: "寄",
    },
    {
      english: "Reporter",
      pinyin: "jìzhě",
      simplified: "记者",
      traditional: "記者",
    },
    {
      english: "Plan",
      pinyin: "jìhuà",
      simplified: "计划",
      traditional: "計劃",
    },
    {
      english: "Although",
      pinyin: "jìrán",
      simplified: "既然",
      traditional: "既然",
    },
    {
      english: "Technology",
      pinyin: "jìshù",
      simplified: "技术",
      traditional: "技術",
    },
    {
      english: "Continue",
      pinyin: "jìxù",
      simplified: "继续",
      traditional: "繼續",
    },
    {
      english: "Furniture",
      pinyin: "jiājù",
      simplified: "家具",
      traditional: "家具",
    },
    {
      english: "Overtime work",
      pinyin: "jiābān",
      simplified: "加班",
      traditional: "加班",
    },
    {
      english: "Gas station",
      pinyin: "jiāyóuzhàn",
      simplified: "加油站",
      traditional: "加油站",
    },
    {
      english: "False",
      pinyin: "jiǎ",
      simplified: "假",
      traditional: "假",
    },
    {
      english: "Price",
      pinyin: "jiàgé",
      simplified: "价格",
      traditional: "價格",
    },
    {
      english: "Insist",
      pinyin: "jiānchí",
      simplified: "坚持",
      traditional: "堅持",
    },
    {
      english: "Reduce weight",
      pinyin: "jiǎnféi",
      simplified: "减肥",
      traditional: "減肥",
    },
    {
      english: "Reduce",
      pinyin: "jiǎnshǎo",
      simplified: "减少",
      traditional: "減少",
    },
    {
      english: "Future",
      pinyin: "jiānglái",
      simplified: "将来",
      traditional: "未來",
    },
    {
      english: "Bonus",
      pinyin: "jiǎngjīn",
      simplified: "奖金",
      traditional: "獎金",
    },
    {
      english: "Reduce, cut down",
      pinyin: "jiàngdī",
      simplified: "降低",
      traditional: "降低",
    },
    {
      english: "Hand over",
      pinyin: "jiāo",
      simplified: "交",
      traditional: "交",
    },
    {
      english: "Communication",
      pinyin: "jiāoliú",
      simplified: "交流",
      traditional: "交流",
    },
    {
      english: "Traffic",
      pinyin: "jiāotōng",
      simplified: "交通",
      traditional: "交通",
    },
    {
      english: "Proud",
      pinyin: "jiāo'ào",
      simplified: "骄傲",
      traditional: "驕傲",
    },
    {
      english: "Dumplings",
      pinyin: "jiǎozi",
      simplified: "饺子",
      traditional: "餃子",
    },
    {
      english: "Professor",
      pinyin: "jiàoshòu",
      simplified: "教授",
      traditional: "教授",
    },
    {
      english: "Education",
      pinyin: "jiàoyù",
      simplified: "教育",
      traditional: "教育",
    },
    {
      english: "Accept",
      pinyin: "jiēshòu",
      simplified: "接受",
      traditional: "接受",
    },
    {
      english: "Result",
      pinyin: "jiéguǒ",
      simplified: "结果",
      traditional: "結果",
    },
    {
      english: "Save",
      pinyin: "jiéyuē",
      simplified: "节约",
      traditional: "節約",
    },
    {
      english: "Explain",
      pinyin: "jiěshì",
      simplified: "解释",
      traditional: "解釋",
    },
    {
      english: "Although",
      pinyin: "jǐnguǎn",
      simplified: "尽管",
      traditional: "儘管",
    },
    {
      english: "Nervous",
      pinyin: "jǐnzhāng",
      simplified: "紧张",
      traditional: "緊張",
    },
    {
      english: "In process of",
      pinyin: "jìnxíng",
      simplified: "进行",
      traditional: "進行",
    },
    {
      english: "Prohibit",
      pinyin: "jìnzhǐ",
      simplified: "禁止",
      traditional: "禁止",
    },
    {
      english: "Marvellous",
      pinyin: "jīngcǎi",
      simplified: "精彩",
      traditional: "精彩",
    },
    {
      english: "Spirit",
      pinyin: "jīngshén",
      simplified: "精神",
      traditional: "精神",
    },
    {
      english: "Economics",
      pinyin: "jīngjì",
      simplified: "经济",
      traditional: "經濟",
    },
    {
      english: "Experience",
      pinyin: "jīngyàn",
      simplified: "经验",
      traditional: "經驗",
    },
    {
      english: "Beijing opera",
      pinyin: "jīngjù",
      simplified: "京剧",
      traditional: "京劇",
    },
    {
      english: "Policeman",
      pinyin: "jǐngchá",
      simplified: "警察",
      traditional: "警察",
    },
    {
      english: "Unexpectedly",
      pinyin: "jìngrán",
      simplified: "竟然",
      traditional: "竟然",
    },
    {
      english: "Compete",
      pinyin: "jìngzhēng",
      simplified: "竞争",
      traditional: "競爭",
    },
    {
      english: "Mirror",
      pinyin: "jìngzi",
      simplified: "镜子",
      traditional: "鏡子",
    },
    {
      english: "Exactly",
      pinyin: "jiūjìng",
      simplified: "究竟",
      traditional: "究竟",
    },
    {
      english: "Hold",
      pinyin: "jǔbàn",
      simplified: "举办",
      traditional: "舉辦",
    },
    {
      english: "Refuse",
      pinyin: "jùjué",
      simplified: "拒绝",
      traditional: "拒絕",
    },
    {
      english: "Distance",
      pinyin: "jùlí",
      simplified: "距离",
      traditional: "距離",
    },
    {
      english: "Make fun of",
      pinyin: "kāiwánxiào",
      simplified: "开玩笑",
      traditional: "開玩笑",
    },
    {
      english: "View",
      pinyin: "kànfǎ",
      simplified: "看法",
      traditional: "看法",
    },
    {
      english: "Consider",
      pinyin: "kǎolǜ",
      simplified: "考虑",
      traditional: "考慮",
    },
    {
      english: "Tree (measure word)",
      pinyin: "kē",
      simplified: "棵",
      traditional: "棵",
    },
    {
      english: "Science",
      pinyin: "kēxué",
      simplified: "科学",
      traditional: "科學",
    },
    {
      english: "Cough",
      pinyin: "késou",
      simplified: "咳嗽",
      traditional: "咳嗽",
    },
    {
      english: "Poor",
      pinyin: "kělián",
      simplified: "可怜",
      traditional: "可憐",
    },
    {
      english: "However",
      pinyin: "kěshì",
      simplified: "可是",
      traditional: "可是",
    },
    {
      english: "Unfortunately",
      pinyin: "kěxī",
      simplified: "可惜",
      traditional: "可惜",
    },
    {
      english: "Sure",
      pinyin: "kěndìng",
      simplified: "肯定",
      traditional: "肯定",
    },
    {
      english: "Air",
      pinyin: "kōngqì",
      simplified: "空气",
      traditional: "空氣",
    },
    {
      english: "I'm afraid",
      pinyin: "kǒngpà",
      simplified: "恐怕",
      traditional: "恐怕",
    },
    {
      english: "Bitter",
      pinyin: "kǔ",
      simplified: "苦",
      traditional: "苦",
    },
    {
      english: "Wide",
      pinyin: "kuān",
      simplified: "宽",
      traditional: "寬",
    },
    {
      english: "Sleepy",
      pinyin: "kùn",
      simplified: "困",
      traditional: "困",
    },
    {
      english: "Difficulty",
      pinyin: "kùnnan",
      simplified: "困难",
      traditional: "困難",
    },
    {
      english: "Expand",
      pinyin: "kuòdà",
      simplified: "扩大",
      traditional: "擴大",
    },
    {
      english: "Pull",
      pinyin: "lā",
      simplified: "拉",
      traditional: "拉",
    },
    {
      english: "Trash",
      pinyin: "lājītǒng",
      simplified: "垃圾桶",
      traditional: "垃圾桶",
    },
    {
      english: "Spicy",
      pinyin: "là",
      simplified: "辣",
      traditional: "辣",
    },
    {
      english: "There's not enough time",
      pinyin: "láibují",
      simplified: "来不及",
      traditional: "來不及",
    },
    {
      english: "In time",
      pinyin: "láidejí",
      simplified: "来得及",
      traditional: "來得及",
    },
    {
      english: "Lazy",
      pinyin: "lǎn",
      simplified: "懒",
      traditional: "懶",
    },
    {
      english: "Waste",
      pinyin: "làngfèi",
      simplified: "浪费",
      traditional: "浪費",
    },
    {
      english: "Romantic",
      pinyin: "làngmàn",
      simplified: "浪漫",
      traditional: "浪漫",
    },
    {
      english: "Tiger",
      pinyin: "lǎohǔ",
      simplified: "老虎",
      traditional: "老虎",
    },
    {
      english: "Calm down",
      pinyin: "lěngjìng",
      simplified: "冷静",
      traditional: "冷靜",
    },
    {
      english: "Haircut",
      pinyin: "lǐfà",
      simplified: "理发",
      traditional: "理髮",
    },
    {
      english: "Understand",
      pinyin: "lǐjiě",
      simplified: "理解",
      traditional: "理解",
    },
    {
      english: "Ideal",
      pinyin: "lǐxiǎng",
      simplified: "理想",
      traditional: "理想",
    },
    {
      english: "Politeness",
      pinyin: "lǐmào",
      simplified: "礼貌",
      traditional: "禮貌",
    },
    {
      english: "Fierce",
      pinyin: "lìhai",
      simplified: "厉害",
      traditional: "厲害",
    },
    {
      english: "Experience, skill",
      pinyin: "jīnglì",
      simplified: "经历",
      traditional: "經歷",
    },
    {
      english: "Strength",
      pinyin: "lìqi",
      simplified: "力气",
      traditional: "力氣",
    },
    {
      english: "For example",
      pinyin: "lìrú",
      simplified: "例如",
      traditional: "例如",
    },
    {
      english: "Two",
      pinyin: "liǎ",
      simplified: "俩",
      traditional: "倆",
    },
    {
      english: "Even",
      pinyin: "lián",
      simplified: "连",
      traditional: "連",
    },
    {
      english: "Contact",
      pinyin: "liánxì",
      simplified: "联系",
      traditional: "聯繫",
    },
    {
      english: "Pleasantly cool",
      pinyin: "liángkuai",
      simplified: "凉快",
      traditional: "涼快",
    },
    {
      english: "Bright",
      pinyin: "liàng",
      simplified: "亮",
      traditional: "亮",
    },
    {
      english: "Chat",
      pinyin: "liáotiān",
      simplified: "聊天",
      traditional: "聊天",
    },
    {
      english: "In addition",
      pinyin: "lìngwài",
      simplified: "另外",
      traditional: "另外",
    },
    {
      english: "Stay",
      pinyin: "liú",
      simplified: "留",
      traditional: "留",
    },
    {
      english: "Overseas Study",
      pinyin: "liúxué",
      simplified: "留学",
      traditional: "留學",
    },
    {
      english: "Shed tears",
      pinyin: "liúlèi",
      simplified: "流泪",
      traditional: "流淚",
    },
    {
      english: "Fluent",
      pinyin: "liúlì",
      simplified: "流利",
      traditional: "流利",
    },
    {
      english: "Popular",
      pinyin: "liúxíng",
      simplified: "流行",
      traditional: "流行",
    },
    {
      english: "Chaos",
      pinyin: "luàn",
      simplified: "乱",
      traditional: "亂",
    },
    {
      english: "Lawyer",
      pinyin: "lǜshī",
      simplified: "律师",
      traditional: "律師",
    },
    {
      english: "Trouble",
      pinyin: "máfan",
      simplified: "麻烦",
      traditional: "麻煩",
    },
    {
      english: "Careless",
      pinyin: "mǎhu",
      simplified: "马虎",
      traditional: "馬虎",
    },
    {
      english: "Full",
      pinyin: "mǎn",
      simplified: "满",
      traditional: "滿",
    },
    {
      english: "Towel",
      pinyin: "máojīn",
      simplified: "毛巾",
      traditional: "毛巾",
    },
    {
      english: "Beautiful",
      pinyin: "měilì",
      simplified: "美丽",
      traditional: "美麗",
    },
    {
      english: "Dream",
      pinyin: "mèng",
      simplified: "梦",
      traditional: "夢",
    },
    {
      english: "Password",
      pinyin: "mìmǎ",
      simplified: "密码",
      traditional: "密碼",
    },
    {
      english: "Free of charge",
      pinyin: "miǎnfèi",
      simplified: "免费",
      traditional: "免費",
    },
    {
      english: "Nation",
      pinyin: "mínzú",
      simplified: "民族",
      traditional: "民族",
    },
    {
      english: "Mother",
      pinyin: "mǔqīn",
      simplified: "母亲",
      traditional: "母親",
    },
    {
      english: "Objective",
      pinyin: "mùdì",
      simplified: "目的",
      traditional: "目的",
    },
    {
      english: "Patience",
      pinyin: "nàixīn",
      simplified: "耐心",
      traditional: "耐心",
    },
    {
      english: "Could it be said that...",
      pinyin: "nándào",
      simplified: "难道",
      traditional: "難道",
    },
    {
      english: "Uncomfortable",
      pinyin: "nánshòu",
      simplified: "难受",
      traditional: "難受",
    },
    {
      english: "Within",
      pinyin: "nèi",
      simplified: "内",
      traditional: "內",
    },
    {
      english: "Content",
      pinyin: "nèiróng",
      simplified: "内容",
      traditional: "內容",
    },
    {
      english: "Ability",
      pinyin: "nénglì",
      simplified: "能力",
      traditional: "能力",
    },
    {
      english: "Age",
      pinyin: "niánlíng",
      simplified: "年龄",
      traditional: "年齡",
    },
    {
      english: "Countryside",
      pinyin: "nóngcūn",
      simplified: "农村",
      traditional: "農村",
    },
    {
      english: "Get, make",
      pinyin: "nòng",
      simplified: "弄",
      traditional: "弄",
    },
    {
      english: "Warm",
      pinyin: "nuǎnhuo",
      simplified: "暖和",
      traditional: "暖和",
    },
    {
      english: "Occasionally",
      pinyin: "ǒu'ěr",
      simplified: "偶尔",
      traditional: "偶爾",
    },
    {
      english: "Array",
      pinyin: "páiliè",
      simplified: "排列",
      traditional: "排列",
    },
    {
      english: "Judge",
      pinyin: "pànduàn",
      simplified: "判断",
      traditional: "判斷",
    },
    {
      english: "Accompany",
      pinyin: "péi",
      simplified: "陪",
      traditional: "陪",
    },
    {
      english: "Criticism",
      pinyin: "pīpíng",
      simplified: "批评",
      traditional: "批評",
    },
    {
      english: "Skin",
      pinyin: "pífū",
      simplified: "皮肤",
      traditional: "皮膚",
    },
    {
      english: "Bad temper",
      pinyin: "píqi",
      simplified: "脾气",
      traditional: "脾氣",
    },
    {
      english: "Piece",
      pinyin: "piān",
      simplified: "篇",
      traditional: "篇",
    },
    {
      english: "Fool",
      pinyin: "piàn",
      simplified: "骗",
      traditional: "騙",
    },
    {
      english: "Table Tennis",
      pinyin: "pīngpāngqiú",
      simplified: "乒乓球",
      traditional: "乒乓球",
    },
    {
      english: "Peacetime",
      pinyin: "píngshí",
      simplified: "平时",
      traditional: "平時",
    },
    {
      english: "Bottle",
      pinyin: "píngzi",
      simplified: "瓶子",
      traditional: "瓶子",
    },
    {
      english: "Broken",
      pinyin: "pò",
      simplified: "破",
      traditional: "破",
    },
    {
      english: "Universal",
      pinyin: "pǔbiàn",
      simplified: "普遍",
      traditional: "普遍",
    },
    {
      english: "Secondly",
      pinyin: "qícì",
      simplified: "其次",
      traditional: "其次",
    },
    {
      english: "Among",
      pinyin: "qízhōng",
      simplified: "其中",
      traditional: "其中",
    },
    {
      english: "Take off",
      pinyin: "qǐfēi",
      simplified: "起飞",
      traditional: "起飛",
    },
    {
      english: "Get up",
      pinyin: "qǐlái",
      simplified: "起来",
      traditional: "起來",
    },
    {
      english: "Climate",
      pinyin: "qìhòu",
      simplified: "气候",
      traditional: "氣候",
    },
    {
      english: "Must",
      pinyin: "qiānwàn",
      simplified: "千万",
      traditional: "千萬",
    },
    {
      english: "Visa",
      pinyin: "qiānzhèng",
      simplified: "签证",
      traditional: "簽證",
    },
    {
      english: "Wall",
      pinyin: "qiáng",
      simplified: "墙",
      traditional: "牆",
    },
    {
      english: "Knock",
      pinyin: "qiāo",
      simplified: "敲",
      traditional: "敲",
    },
    {
      english: "Bridge",
      pinyin: "qiáo",
      simplified: "桥",
      traditional: "橋",
    },
    {
      english: "Chocolates",
      pinyin: "qiǎokèlì",
      simplified: "巧克力",
      traditional: "巧克力",
    },
    {
      english: "Relative",
      pinyin: "qīnqi",
      simplified: "亲戚",
      traditional: "親戚",
    },
    {
      english: "Light",
      pinyin: "qīng",
      simplified: "轻",
      traditional: "輕",
    },
    {
      english: "Relaxed",
      pinyin: "qīngsōng",
      simplified: "轻松",
      traditional: "輕鬆",
    },
    {
      english: "Situation",
      pinyin: "qíngkuàng",
      simplified: "情况",
      traditional: "情況",
    },
    {
      english: "Leave",
      pinyin: "qǐngjià",
      simplified: "请假",
      traditional: "請假",
    },
    {
      english: "Treat",
      pinyin: "qǐngkè",
      simplified: "请客",
      traditional: "請客",
    },
    {
      english: "Poor",
      pinyin: "qióng",
      simplified: "穷",
      traditional: "窮",
    },
    {
      english: "Difference",
      pinyin: "qūbié",
      simplified: "区别",
      traditional: "區別",
    },
    {
      english: "Take",
      pinyin: "qǔ",
      simplified: "取",
      traditional: "取",
    },
    {
      english: "Whole",
      pinyin: "quánbù",
      simplified: "全部",
      traditional: "全部",
    },
    {
      english: "Shortcoming",
      pinyin: "quēdiǎn",
      simplified: "缺点",
      traditional: "缺點",
    },
    {
      english: "Lack",
      pinyin: "quēshǎo",
      simplified: "缺少",
      traditional: "缺少",
    },
    {
      english: "But",
      pinyin: "què",
      simplified: "却",
      traditional: "卻",
    },
    {
      english: "Exactly",
      pinyin: "quèshí",
      simplified: "确实",
      traditional: "確實",
    },
    {
      english: "Group",
      pinyin: "qún",
      simplified: "群",
      traditional: "群",
    },
    {
      english: "However",
      pinyin: "rán'ér",
      simplified: "然而",
      traditional: "然而",
    },
    {
      english: "Lively",
      pinyin: "rènao",
      simplified: "热闹",
      traditional: "熱鬧",
    },
    {
      english: "RMB",
      pinyin: "rénmínbì",
      simplified: "人民币",
      traditional: "人民幣",
    },
    {
      english: "Whatever, any",
      pinyin: "rènhé",
      simplified: "任何",
      traditional: "任何",
    },
    {
      english: "Task",
      pinyin: "rènwu",
      simplified: "任务",
      traditional: "任務",
    },
    {
      english: "Throw",
      pinyin: "rēng",
      simplified: "扔",
      traditional: "扔",
    },
    {
      english: "Still",
      pinyin: "réngrán",
      simplified: "仍然",
      traditional: "仍然",
    },
    {
      english: "Diary",
      pinyin: "rìjì",
      simplified: "日记",
      traditional: "日記",
    },
    {
      english: "Entrance",
      pinyin: "rùkǒu",
      simplified: "入口",
      traditional: "入口",
    },
    {
      english: "Soft",
      pinyin: "ruǎn",
      simplified: "软",
      traditional: "軟",
    },
    {
      english: "Take a walk",
      pinyin: "sànbù",
      simplified: "散步",
      traditional: "散步",
    },
    {
      english: "Forest",
      pinyin: "sēnlín",
      simplified: "森林",
      traditional: "森林",
    },
    {
      english: "Sofa",
      pinyin: "shāfā",
      simplified: "沙发",
      traditional: "沙發",
    },
    {
      english: "Discuss",
      pinyin: "shāngliang",
      simplified: "商量",
      traditional: "商量",
    },
    {
      english: "Sad",
      pinyin: "shāngxīn",
      simplified: "伤心",
      traditional: "傷心",
    },
    {
      english: "Slightly",
      pinyin: "shāowēi",
      simplified: "稍微",
      traditional: "稍微",
    },
    {
      english: "Sociology",
      pinyin: "shèhuì",
      simplified: "社会",
      traditional: "社會",
    },
    {
      english: "Deep",
      pinyin: "shēn",
      simplified: "深",
      traditional: "深",
    },
    {
      english: "Apply",
      pinyin: "shēnqǐng",
      simplified: "申请",
      traditional: "申請",
    },
    {
      english: "Even to the extent that",
      pinyin: "shènzhì",
      simplified: "甚至",
      traditional: "甚至",
    },
    {
      english: "Life, livlihood, activity",
      pinyin: "shēnghuó",
      simplified: "生活",
      traditional: "生活",
    },
    {
      english: "Province",
      pinyin: "shěng",
      simplified: "省",
      traditional: "省",
    },
    {
      english: "Left",
      pinyin: "shèng",
      simplified: "剩",
      traditional: "剩",
    },
    {
      english: "Fail",
      pinyin: "shībài",
      simplified: "失败",
      traditional: "失敗",
    },
    {
      english: "Disappointment",
      pinyin: "shīwàng",
      simplified: "失望",
      traditional: "失望",
    },
    {
      english: "Master worker",
      pinyin: "shīfu",
      simplified: "师傅",
      traditional: "師傅",
    },
    {
      english: "Moist",
      pinyin: "shīrùn",
      simplified: "湿润",
      traditional: "濕潤",
    },
    {
      english: "Lion",
      pinyin: "shīzi",
      simplified: "狮子",
      traditional: "獅子",
    },
    {
      english: "Very",
      pinyin: "shífēn",
      simplified: "十分",
      traditional: "十分",
    },
    {
      english: "Actual",
      pinyin: "shíjì",
      simplified: "实际",
      traditional: "實際",
    },
    {
      english: "Really",
      pinyin: "shízài",
      simplified: "实在",
      traditional: "實在",
    },
    {
      english: "Food",
      pinyin: "shípǐn",
      simplified: "食品",
      traditional: "食品",
    },
    {
      english: "Use",
      pinyin: "shǐyòng",
      simplified: "使用",
      traditional: "使用",
    },
    {
      english: "Try",
      pinyin: "shì",
      simplified: "试",
      traditional: "試",
    },
    {
      english: "Market",
      pinyin: "shìchǎng",
      simplified: "市场",
      traditional: "市場",
    },
    {
      english: "Fit",
      pinyin: "shìhé",
      simplified: "适合",
      traditional: "適合",
    },
    {
      english: "Adapt",
      pinyin: "shìyìng",
      simplified: "适应",
      traditional: "適應",
    },
    {
      english: "Century",
      pinyin: "shìjì",
      simplified: "世纪",
      traditional: "世紀",
    },
    {
      english: "Collect",
      pinyin: "shōu",
      simplified: "收",
      traditional: "收",
    },
    {
      english: "Income",
      pinyin: "shōurù",
      simplified: "收入",
      traditional: "收入",
    },
    {
      english: "Tidy",
      pinyin: "shōushi",
      simplified: "收拾",
      traditional: "收拾",
    },
    {
      english: "Capital",
      pinyin: "shǒudū",
      simplified: "首都",
      traditional: "首都",
    },
    {
      english: "First",
      pinyin: "shǒuxiān",
      simplified: "首先",
      traditional: "首先",
    },
    {
      english: "Cannot bear sth",
      pinyin: "shòubuliǎo",
      simplified: "受不了",
      traditional: "受不了",
    },
    {
      english: "Suffer",
      pinyin: "shòudào",
      simplified: "受到",
      traditional: "受到",
    },
    {
      english: "Salesperson",
      pinyin: "shòuhuòyuán",
      simplified: "售货员",
      traditional: "售貨員",
    },
    {
      english: "Lose, fail",
      pinyin: "shū",
      simplified: "输",
      traditional: "輸",
    },
    {
      english: "Be familiar with",
      pinyin: "shúxī",
      simplified: "熟悉",
      traditional: "熟悉",
    },
    {
      english: "Number, quantity, amount",
      pinyin: "shùliàng",
      simplified: "数量",
      traditional: "數量",
    },
    {
      english: "Number, figure, digit",
      pinyin: "shùzì",
      simplified: "数字",
      traditional: "數字",
    },
    {
      english: "Handsome",
      pinyin: "shuài",
      simplified: "帅",
      traditional: "帥",
    },
    {
      english: "Incidentally",
      pinyin: "shùnbiàn",
      simplified: "顺便",
      traditional: "順便",
    },
    {
      english: "Smoothly",
      pinyin: "shùnlì",
      simplified: "顺利",
      traditional: "順利",
    },
    {
      english: "Order",
      pinyin: "shùnxù",
      simplified: "顺序",
      traditional: "順序",
    },
    {
      english: "Explain",
      pinyin: "shuōmíng",
      simplified: "说明",
      traditional: "說明",
    },
    {
      english: "Master",
      pinyin: "shuòshì",
      simplified: "硕士",
      traditional: "碩士",
    },
    {
      english: "Die",
      pinyin: "sǐ",
      simplified: "死",
      traditional: "死",
    },
    {
      english: "Speed",
      pinyin: "sùdù",
      simplified: "速度",
      traditional: "速度",
    },
    {
      english: "Plastic bag",
      pinyin: "sùliàodài",
      simplified: "塑料袋",
      traditional: "塑料袋",
    },
    {
      english: "Acid",
      pinyin: "suān",
      simplified: "酸",
      traditional: "酸",
    },
    {
      english: "Count",
      pinyin: "suàn",
      simplified: "算",
      traditional: "算",
    },
    {
      english: "Casual",
      pinyin: "suíbiàn",
      simplified: "随便",
      traditional: "隨便",
    },
    {
      english: "Along with",
      pinyin: "suízhe",
      simplified: "随着",
      traditional: "隨著",
    },
    {
      english: "Grandson",
      pinyin: "sūnzi",
      simplified: "孙子",
      traditional: "孫子",
    },
    {
      english: "All",
      pinyin: "suǒyǒu",
      simplified: "所有",
      traditional: "所有",
    },
    {
      english: "Platform",
      pinyin: "tái",
      simplified: "台",
      traditional: "台",
    },
    {
      english: "Lift",
      pinyin: "tái",
      simplified: "抬",
      traditional: "抬",
    },
    {
      english: "Attitude",
      pinyin: "tàidu",
      simplified: "态度",
      traditional: "態度",
    },
    {
      english: "Life, anima",
      pinyin: "shēngmìng",
      simplified: "生命",
      traditional: "生命",
    },
    {
      english: "Talk",
      pinyin: "tán",
      simplified: "谈",
      traditional: "談",
    },
    {
      english: "Play the piano",
      pinyin: "tángāngqín",
      simplified: "弹钢琴",
      traditional: "彈鋼琴",
    },
    {
      english: "Soup",
      pinyin: "tāng",
      simplified: "汤",
      traditional: "湯",
    },
    {
      english: "Lie",
      pinyin: "tǎng",
      simplified: "躺",
      traditional: "躺",
    },
    {
      english: "Trip",
      pinyin: "tàng",
      simplified: "趟",
      traditional: "趟",
    },
    {
      english: "Discuss",
      pinyin: "tǎolùn",
      simplified: "讨论",
      traditional: "討論",
    },
    {
      english: "Hate",
      pinyin: "tǎoyàn",
      simplified: "讨厌",
      traditional: "討厭",
    },
    {
      english: "Characteristic",
      pinyin: "tèdiǎn",
      simplified: "特点",
      traditional: "特點",
    },
    {
      english: "Provide",
      pinyin: "tígōng",
      simplified: "提供",
      traditional: "提供",
    },
    {
      english: "In advance",
      pinyin: "tíqián",
      simplified: "提前",
      traditional: "提前",
    },
    {
      english: "Remind",
      pinyin: "tíxǐng",
      simplified: "提醒",
      traditional: "提醒",
    },
    {
      english: "Fill in the blanks",
      pinyin: "tiánkòng",
      simplified: "填空",
      traditional: "填空",
    },
    {
      english: "Condition",
      pinyin: "tiáojiàn",
      simplified: "条件",
      traditional: "條件",
    },
    {
      english: "Stop it",
      pinyin: "tíngzhǐ",
      simplified: "停止",
      traditional: "停止",
    },
    {
      english: "Quite",
      pinyin: "tǐng",
      simplified: "挺",
      traditional: "挺",
    },
    {
      english: "Through",
      pinyin: "tōngguò",
      simplified: "通过",
      traditional: "通過",
    },
    {
      english: "Notice",
      pinyin: "tōngzhī",
      simplified: "通知",
      traditional: "通知",
    },
    {
      english: "Sympathy",
      pinyin: "tóngqíng",
      simplified: "同情",
      traditional: "同情",
    },
    {
      english: "Push",
      pinyin: "tuī",
      simplified: "推",
      traditional: "推",
    },
    {
      english: "Delay",
      pinyin: "tuīchí",
      simplified: "推迟",
      traditional: "推遲",
    },
    {
      english: "Take off",
      pinyin: "tuō",
      simplified: "脱",
      traditional: "脫",
    },
    {
      english: "Socks",
      pinyin: "wàzi",
      simplified: "袜子",
      traditional: "襪子",
    },
    {
      english: "Completely",
      pinyin: "wánquán",
      simplified: "完全",
      traditional: "完全",
    },
    {
      english: "To, towards",
      pinyin: "wǎng",
      simplified: "往",
      traditional: "往",
    },
    {
      english: "Often",
      pinyin: "wǎngwǎng",
      simplified: "往往",
      traditional: "往往",
    },
    {
      english: "Tennis",
      pinyin: "wǎngqiú",
      simplified: "网球",
      traditional: "網球",
    },
    {
      english: "Website",
      pinyin: "wǎngzhàn",
      simplified: "网站",
      traditional: "網站",
    },
    {
      english: "Danger",
      pinyin: "wēixiǎn",
      simplified: "危险",
      traditional: "危險",
    },
    {
      english: "Taste",
      pinyin: "wèidào",
      simplified: "味道",
      traditional: "味道",
    },
    {
      english: "Temperature",
      pinyin: "wēndù",
      simplified: "温度",
      traditional: "溫度",
    },
    {
      english: "Article",
      pinyin: "wénzhāng",
      simplified: "文章",
      traditional: "文章",
    },
    {
      english: "Handshake",
      pinyin: "wòshǒu",
      simplified: "握手",
      traditional: "握手",
    },
    {
      english: "Contaminated",
      pinyin: "wūrǎn",
      simplified: "污染",
      traditional: "污染",
    },
    {
      english: "Nothing",
      pinyin: "wú",
      simplified: "无",
      traditional: "無",
    },
    {
      english: "Boring",
      pinyin: "wúliáo",
      simplified: "无聊",
      traditional: "無聊",
    },
    {
      english: "No matter what",
      pinyin: "wúlùn",
      simplified: "无论",
      traditional: "無論",
    },
    {
      english: "Misunderstanding",
      pinyin: "wùhuì",
      simplified: "误会",
      traditional: "誤會",
    },
    {
      english: "Tomato",
      pinyin: "xīhóngshì",
      simplified: "西红柿",
      traditional: "西紅柿",
    },
    {
      english: "Attract",
      pinyin: "xīyǐn",
      simplified: "吸引",
      traditional: "吸引",
    },
    {
      english: "Washing machine",
      pinyin: "xǐyījī",
      simplified: "洗衣机",
      traditional: "洗衣機",
    },
    {
      english: "Salty",
      pinyin: "xián",
      simplified: "咸",
      traditional: "咸",
    },
    {
      english: "Modern",
      pinyin: "xiàndài",
      simplified: "现代",
      traditional: "現代",
    },
    {
      english: "Envy",
      pinyin: "xiànmù",
      simplified: "羡慕",
      traditional: "羨慕",
    },
    {
      english: "Limit",
      pinyin: "xiànzhì",
      simplified: "限制",
      traditional: "限制",
    },
    {
      english: "Fragrant",
      pinyin: "xiāng",
      simplified: "香",
      traditional: "香",
    },
    {
      english: "Contrary",
      pinyin: "xiāngfǎn",
      simplified: "相反",
      traditional: "相反",
    },
    {
      english: "Detailed",
      pinyin: "xiángxì",
      simplified: "详细",
      traditional: "詳細",
    },
    {
      english: "Ring",
      pinyin: "xiǎng",
      simplified: "响",
      traditional: "響",
    },
    {
      english: "Message",
      pinyin: "xiāoxi",
      simplified: "消息",
      traditional: "消息",
    },
    {
      english: "Novel",
      pinyin: "xiǎoshuō",
      simplified: "小说",
      traditional: "小說",
    },
    {
      english: "Joke",
      pinyin: "xiàohua",
      simplified: "笑话",
      traditional: "笑話",
    },
    {
      english: "Effect",
      pinyin: "xiàoguǒ",
      simplified: "效果",
      traditional: "效果",
    },
    {
      english: "Hard",
      pinyin: "xīnkǔ",
      simplified: "辛苦",
      traditional: "辛苦",
    },
    {
      english: "Mood",
      pinyin: "xīnqíng",
      simplified: "心情",
      traditional: "心情",
    },
    {
      english: "Trust",
      pinyin: "xìnrèn",
      simplified: "信任",
      traditional: "信任",
    },
    {
      english: "Confidence",
      pinyin: "xìnxīn",
      simplified: "信心",
      traditional: "信心",
    },
    {
      english: "Credit card",
      pinyin: "xìnyòngkǎ",
      simplified: "信用卡",
      traditional: "信用卡",
    },
    {
      english: "Excitement",
      pinyin: "xīngfèn",
      simplified: "兴奋",
      traditional: "興奮",
    },
    {
      english: "That's ok",
      pinyin: "xíng",
      simplified: "行",
      traditional: "行",
    },
    {
      english: "Wake up",
      pinyin: "xǐng",
      simplified: "醒",
      traditional: "醒",
    },
    {
      english: "Gender",
      pinyin: "xìngbié",
      simplified: "性别",
      traditional: "性別",
    },
    {
      english: "Character",
      pinyin: "xìnggé",
      simplified: "性格",
      traditional: "性格",
    },
    {
      english: "Happiness",
      pinyin: "xìngfú",
      simplified: "幸福",
      traditional: "幸福",
    },
    {
      english: "Repair",
      pinyin: "xiū",
      simplified: "修",
      traditional: "修",
    },
    {
      english: "Many",
      pinyin: "xǔduō",
      simplified: "许多",
      traditional: "許多",
    },
    {
      english: "Blood",
      pinyin: "xuè",
      simplified: "血",
      traditional: "血",
    },
    {
      english: "Pressure",
      pinyin: "yālì",
      simplified: "压力",
      traditional: "壓力",
    },
    {
      english: "Toothpaste",
      pinyin: "yágāo",
      simplified: "牙膏",
      traditional: "牙膏",
    },
    {
      english: "Asia",
      pinyin: "yàzhōu",
      simplified: "亚洲",
      traditional: "亞洲",
    },
    {
      english: "Ah",
      pinyin: "ya",
      simplified: "呀",
      traditional: "呀",
    },
    {
      english: "Salt",
      pinyin: "yán",
      simplified: "盐",
      traditional: "鹽",
    },
    {
      english: "Strict",
      pinyin: "yángé",
      simplified: "严格",
      traditional: "嚴格",
    },
    {
      english: "Serious",
      pinyin: "yánzhòng",
      simplified: "严重",
      traditional: "嚴重",
    },
    {
      english: "Graduate student",
      pinyin: "yánjiūshēng",
      simplified: "研究生",
      traditional: "研究生",
    },
    {
      english: "Show",
      pinyin: "yǎnchū",
      simplified: "演出",
      traditional: "演出",
    },
    {
      english: "Performer, actor",
      pinyin: "yǎnyuán",
      simplified: "演员",
      traditional: "演員",
    },
    {
      english: "Sunshine",
      pinyin: "yángguāng",
      simplified: "阳光",
      traditional: "陽光",
    },
    {
      english: "Cultivate",
      pinyin: "yǎngchéng",
      simplified: "养成",
      traditional: "養成",
    },
    {
      english: "A look",
      pinyin: "yàngzi",
      simplified: "样子",
      traditional: "樣子",
    },
    {
      english: "Invitation",
      pinyin: "yāoqǐng",
      simplified: "邀请",
      traditional: "邀請",
    },
    {
      english: "Key",
      pinyin: "yàoshi",
      simplified: "钥匙",
      traditional: "鑰匙",
    },
    {
      english: "Perhaps",
      pinyin: "yěxǔ",
      simplified: "也许",
      traditional: "也許",
    },
    {
      english: "Page",
      pinyin: "yè",
      simplified: "页",
      traditional: "頁",
    },
    {
      english: "Leaf",
      pinyin: "yèzi",
      simplified: "叶子",
      traditional: "葉子",
    },
    {
      english: "Everything",
      pinyin: "yíqiè",
      simplified: "一切",
      traditional: "一切",
    },
    {
      english: "With",
      pinyin: "yǐ",
      simplified: "以",
      traditional: "以",
    },
    {
      english: "Billion",
      pinyin: "yì",
      simplified: "亿",
      traditional: "億",
    },
    {
      english: "Opinion",
      pinyin: "yìjiàn",
      simplified: "意见",
      traditional: "意見",
    },
    {
      english: "Art",
      pinyin: "yìshù",
      simplified: "艺术",
      traditional: "藝術",
    },
    {
      english: "Therefore",
      pinyin: "yīncǐ",
      simplified: "因此",
      traditional: "因此",
    },
    {
      english: "Seat, base, stand",
      pinyin: "zuò",
      simplified: "座",
      traditional: "座",
    },
    {
      english: "Drinks",
      pinyin: "yǐnliào",
      simplified: "饮料",
      traditional: "飲料",
    },
    {
      english: "Cause",
      pinyin: "yǐnqǐ",
      simplified: "引起",
      traditional: "引起",
    },
    {
      english: "Impression",
      pinyin: "yìnxiàng",
      simplified: "印象",
      traditional: "印象",
    },
    {
      english: "Win",
      pinyin: "yíng",
      simplified: "赢",
      traditional: "贏",
    },
    {
      english: "Hard",
      pinyin: "yìng",
      simplified: "硬",
      traditional: "硬",
    },
    {
      english: "Brave",
      pinyin: "yǒnggǎn",
      simplified: "勇敢",
      traditional: "勇敢",
    },
    {
      english: "Forever",
      pinyin: "yǒngyuǎn",
      simplified: "永远",
      traditional: "永遠",
    },
    {
      english: "Advantage",
      pinyin: "yōudiǎn",
      simplified: "优点",
      traditional: "優點",
    },
    {
      english: "Excellent",
      pinyin: "yōuxiù",
      simplified: "优秀",
      traditional: "優秀",
    },
    {
      english: "Humor",
      pinyin: "yōumò",
      simplified: "幽默",
      traditional: "幽默",
    },
    {
      english: "From",
      pinyin: "yóu",
      simplified: "由",
      traditional: "由",
    },
    {
      english: "Because",
      pinyin: "yóuyú",
      simplified: "由于",
      traditional: "由於",
    },
    {
      english: "Especially",
      pinyin: "yóuqí",
      simplified: "尤其",
      traditional: "尤其",
    },
    {
      english: "Interesting",
      pinyin: "yǒuqù",
      simplified: "有趣",
      traditional: "有趣",
    },
    {
      english: "Friendly",
      pinyin: "yǒuhǎo",
      simplified: "友好",
      traditional: "友好",
    },
    {
      english: "Friendship",
      pinyin: "yǒuyì",
      simplified: "友谊",
      traditional: "友誼",
    },
    {
      english: "Cheerful",
      pinyin: "yúkuài",
      simplified: "愉快",
      traditional: "愉快",
    },
    {
      english: "Therefore",
      pinyin: "yúshì",
      simplified: "于是",
      traditional: "於是",
    },
    {
      english: "And",
      pinyin: "yǔ",
      simplified: "与",
      traditional: "與",
    },
    {
      english: "Grammar",
      pinyin: "yǔfǎ",
      simplified: "语法",
      traditional: "語法",
    },
    {
      english: "Language",
      pinyin: "yǔyán",
      simplified: "语言",
      traditional: "語言",
    },
    {
      english: "Badminton",
      pinyin: "yǔmáoqiú",
      simplified: "羽毛球",
      traditional: "羽毛球",
    },
    {
      english: "Preview",
      pinyin: "yùxí",
      simplified: "预习",
      traditional: "預習",
    },
    {
      english: "Circle",
      pinyin: "yuán",
      simplified: "圆",
      traditional: "圓",
    },
    {
      english: "Original",
      pinyin: "yuánlái",
      simplified: "原来",
      traditional: "原來",
    },
    {
      english: "Forgive",
      pinyin: "yuánliàng",
      simplified: "原谅",
      traditional: "原諒",
    },
    {
      english: "Reason",
      pinyin: "yuányīn",
      simplified: "原因",
      traditional: "原因",
    },
    {
      english: "Date",
      pinyin: "yuēhuì",
      simplified: "约会",
      traditional: "約會",
    },
    {
      english: "Read",
      pinyin: "yuèdú",
      simplified: "阅读",
      traditional: "閱讀",
    },
    {
      english: "Allow",
      pinyin: "yǔnxǔ",
      simplified: "允许",
      traditional: "允許",
    },
    {
      english: "Magazine",
      pinyin: "zázhì",
      simplified: "杂志",
      traditional: "雜誌",
    },
    {
      english: "We",
      pinyin: "zánmen",
      simplified: "咱们",
      traditional: "咱們",
    },
    {
      english: "Temporary",
      pinyin: "zànshí",
      simplified: "暂时",
      traditional: "暫時",
    },
    {
      english: "Dirty",
      pinyin: "zāng",
      simplified: "脏",
      traditional: "臟",
    },
    {
      english: "Responsibility",
      pinyin: "zérèn",
      simplified: "责任",
      traditional: "責任",
    },
    {
      english: "Increase, addition",
      pinyin: "zēngjiā",
      simplified: "增加",
      traditional: "增加",
    },
    {
      english: "Narrow",
      pinyin: "zhǎi",
      simplified: "窄",
      traditional: "窄",
    },
    {
      english: "Recruit",
      pinyin: "zhāopìn",
      simplified: "招聘",
      traditional: "招聘",
    },
    {
      english: "In process of",
      pinyin: "zhe",
      simplified: "着",
      traditional: "著",
    },
    {
      english: "Real",
      pinyin: "zhēnzhèng",
      simplified: "真正",
      traditional: "真正",
    },
    {
      english: "Arrangement",
      pinyin: "zhěnglǐ",
      simplified: "整理",
      traditional: "整理",
    },
    {
      english: "Neat",
      pinyin: "zhěngqí",
      simplified: "整齐",
      traditional: "整齊",
    },
    {
      english: "Normal",
      pinyin: "zhèngcháng",
      simplified: "正常",
      traditional: "正常",
    },
    {
      english: "Just right",
      pinyin: "zhènghǎo",
      simplified: "正好",
      traditional: "正好",
    },
    {
      english: "Correct",
      pinyin: "zhèngquè",
      simplified: "正确",
      traditional: "正確",
    },
    {
      english: "Formal",
      pinyin: "zhèngshì",
      simplified: "正式",
      traditional: "正式",
    },
    {
      english: "Prove",
      pinyin: "zhèngmíng",
      simplified: "证明",
      traditional: "證明",
    },
    {
      english: "Of",
      pinyin: "zhī",
      simplified: "之",
      traditional: "之",
    },
    {
      english: "Support",
      pinyin: "zhīchí",
      simplified: "支持",
      traditional: "支持",
    },
    {
      english: "Knowledge",
      pinyin: "zhīshi",
      simplified: "知识",
      traditional: "知識",
    },
    {
      english: "Worth",
      pinyin: "zhídé",
      simplified: "值得",
      traditional: "值得",
    },
    {
      english: "Direct",
      pinyin: "zhíjiē",
      simplified: "直接",
      traditional: "直接",
    },
    {
      english: "Botany, plant",
      pinyin: "zhíwù",
      simplified: "植物",
      traditional: "植物",
    },
    {
      english: "Occupation",
      pinyin: "zhíyè",
      simplified: "职业",
      traditional: "職業",
    },
    {
      english: "Finger, to point",
      pinyin: "zhǐ",
      simplified: "指",
      traditional: "指",
    },
    {
      english: "Have to",
      pinyin: "zhǐhǎo",
      simplified: "只好",
      traditional: "只好",
    },
    {
      english: "As long as",
      pinyin: "zhǐyào",
      simplified: "只要",
      traditional: "只要",
    },
    {
      english: "Quality",
      pinyin: "zhìliàng",
      simplified: "质量",
      traditional: "質量",
    },
    {
      english: "At least",
      pinyin: "zhìshǎo",
      simplified: "至少",
      traditional: "至少",
    },
    {
      english: "Manufacture",
      pinyin: "zhìzào",
      simplified: "制造",
      traditional: "製造",
    },
    {
      english: "Chinese",
      pinyin: "zhōngwén",
      simplified: "中文",
      traditional: "中文",
    },
    {
      english: "A key",
      pinyin: "zhòngdiǎn",
      simplified: "重点",
      traditional: "重點",
    },
    {
      english: "Importance, attach importance to",
      pinyin: "zhòngshì",
      simplified: "重视",
      traditional: "重視",
    },
    {
      english: "Around",
      pinyin: "zhōuwéi",
      simplified: "周围",
      traditional: "周圍",
    },
    {
      english: "Pig",
      pinyin: "zhū",
      simplified: "猪",
      traditional: "豬",
    },
    {
      english: "Gradually",
      pinyin: "zhújiàn",
      simplified: "逐渐",
      traditional: "逐漸",
    },
    {
      english: "Active",
      pinyin: "zhǔdòng",
      simplified: "主动",
      traditional: "主動",
    },
    {
      english: "Idea",
      pinyin: "zhǔyi",
      simplified: "主意",
      traditional: "主意",
    },
    {
      english: "Congratulate",
      pinyin: "zhùhè",
      simplified: "祝贺",
      traditional: "祝賀",
    },
    {
      english: "Famous",
      pinyin: "zhùmíng",
      simplified: "著名",
      traditional: "著名",
    },
    {
      english: "Specialized",
      pinyin: "zhuānmén",
      simplified: "专门",
      traditional: "專門",
    },
    {
      english: "Major",
      pinyin: "zhuānyè",
      simplified: "专业",
      traditional: "專業",
    },
    {
      english: "Earn",
      pinyin: "zhuàn",
      simplified: "赚",
      traditional: "賺",
    },
    {
      english: "Hit",
      pinyin: "zhuàng",
      simplified: "撞",
      traditional: "撞",
    },
    {
      english: "Accuracy",
      pinyin: "zhǔnquè",
      simplified: "准确",
      traditional: "準確",
    },
    {
      english: "On time",
      pinyin: "zhǔnshí",
      simplified: "准时",
      traditional: "準時",
    },
    {
      english: "Careful",
      pinyin: "zǐxì",
      simplified: "仔细",
      traditional: "仔細",
    },
    {
      english: "Natural",
      pinyin: "zìrán",
      simplified: "自然",
      traditional: "自然",
    },
    {
      english: "Summary",
      pinyin: "zǒngjié",
      simplified: "总结",
      traditional: "總結",
    },
    {
      english: "Rent",
      pinyin: "zū",
      simplified: "租",
      traditional: "租",
    },
    {
      english: "Form",
      pinyin: "zǔchéng",
      simplified: "组成",
      traditional: "組成",
    },
    {
      english: "Organization",
      pinyin: "zǔzhī",
      simplified: "组织",
      traditional: "組織",
    },
    {
      english: "Mouth",
      pinyin: "zuǐ",
      simplified: "嘴",
      traditional: "嘴",
    },
    {
      english: "Best",
      pinyin: "zuìhǎo",
      simplified: "最好",
      traditional: "最好",
    },
    {
      english: "Last",
      pinyin: "zuìhòu",
      simplified: "最后",
      traditional: "最後",
    },
    {
      english: "Respect",
      pinyin: "zūnzhòng",
      simplified: "尊重",
      traditional: "尊重",
    },
    {
      english: "Do business",
      pinyin: "zuòshēngyi",
      simplified: "做生意",
      traditional: "做生意",
    },
    {
      english: "Seat, place, pew",
      pinyin: "zuòwèi",
      simplified: "座位",
      traditional: "座位",
    },
    {
      english: "Increase, grow",
      pinyin: "zēngzhǎng",
      simplified: "增长",
      traditional: "增長",
    },
    {
      english: "Author",
      pinyin: "zuòzhě",
      simplified: "作者",
      traditional: "作者",
    },
    {
      english: "Effect",
      pinyin: "zuòyòng",
      simplified: "作用",
      traditional: "作用",
    },
    {
      english: "Bystanders, gawkers",
      pinyin: "Chī guā qúnzhòng",
      simplified: "吃瓜群众",
      traditional: "吃瓜群眾",
    },
    {
      english: "Rich person, upstart",
      pinyin: "tǔháo",
      simplified: "土豪",
      traditional: "土豪",
    },
  ],
};

export default lesson4;
