import type HskList from "~/types/HskList";

const lesson2: HskList = {
  id: "hmcs97kF5",
  level: 2,
  words: [
    {
      english: "Newspaper",
      pinyin: "bàozhǐ",
      simplified: "报纸",
      traditional: "報紙",
    },
    {
      english: "Person",
      pinyin: "rén",
      simplified: "人",
      traditional: "人",
    },
    {
      english: "Name",
      pinyin: "míngzì",
      simplified: "名字",
      traditional: "名字",
    },
    {
      english: "Book",
      pinyin: "shū",
      simplified: "书",
      traditional: "書",
    },
    {
      english: "Chinese",
      pinyin: "hànyǔ",
      simplified: "汉语",
      traditional: "漢語",
    },
    {
      english: "Character",
      pinyin: "zì",
      simplified: "字",
      traditional: "字",
    },
    {
      english: "Desk",
      pinyin: "zhuōzi",
      simplified: "桌子",
      traditional: "桌子",
    },
    {
      english: "Chair",
      pinyin: "yǐzi",
      simplified: "椅子",
      traditional: "椅子",
    },
    {
      english: "Door",
      pinyin: "mén",
      simplified: "门",
      traditional: "門",
    },
    {
      english: "Topic",
      pinyin: "tí",
      simplified: "题",
      traditional: "題",
    },
    {
      english: "Lesson",
      pinyin: "kè",
      simplified: "课",
      traditional: "課",
    },
    {
      english: "Surname",
      pinyin: "xìng",
      simplified: "姓",
      traditional: "姓",
    },
    {
      english: "Question",
      pinyin: "wèntí",
      simplified: "问题",
      traditional: "問題",
    },
    {
      english: "Matter",
      pinyin: "shìqing",
      simplified: "事情",
      traditional: "事情",
    },
    {
      english: "Exam",
      pinyin: "kǎoshì",
      simplified: "考试",
      traditional: "考試",
    },
    {
      english: "Ticket",
      pinyin: "piào",
      simplified: "票",
      traditional: "票",
    },
    {
      english: "Meaning",
      pinyin: "yìsi",
      simplified: "意思",
      traditional: "意思",
    },
    {
      english: "Color",
      pinyin: "yánsè",
      simplified: "颜色",
      traditional: "顏色",
    },
    {
      english: "Thank",
      pinyin: "xièxie",
      simplified: "谢谢",
      traditional: "謝謝",
    },
    {
      english: "You are welcome",
      pinyin: "búkèqì",
      simplified: "不客气",
      traditional: "不客氣",
    },
    {
      english: "Good-bye",
      pinyin: "zàijiàn",
      simplified: "再见",
      traditional: "再見",
    },
    {
      english: "Please",
      pinyin: "qǐng",
      simplified: "请",
      traditional: "請",
    },
    {
      english: "Sorry",
      pinyin: "duìbùqǐ",
      simplified: "对不起",
      traditional: "對不起",
    },
    {
      english: "It doesn't matter",
      pinyin: "méiguānxi",
      simplified: "没关系",
      traditional: "沒關係",
    },
    {
      english: "Welcome",
      pinyin: "huānyíng",
      simplified: "欢迎",
      traditional: "歡迎",
    },
    {
      english: "Am, is, are",
      pinyin: "shì",
      simplified: "是",
      traditional: "是",
    },
    {
      english: "Have",
      pinyin: "yǒu",
      simplified: "有",
      traditional: "有",
    },
    {
      english: "Look",
      pinyin: "kàn",
      simplified: "看",
      traditional: "看",
    },
    {
      english: "Listen",
      pinyin: "tīng",
      simplified: "听",
      traditional: "聽",
    },
    {
      english: "Speak",
      pinyin: "shuōhuà",
      simplified: "说话",
      traditional: "說話",
    },
    {
      english: "Read",
      pinyin: "dú",
      simplified: "读",
      traditional: "讀",
    },
    {
      english: "Write",
      pinyin: "xiě",
      simplified: "写",
      traditional: "寫",
    },
    {
      english: "See",
      pinyin: "kànjiàn",
      simplified: "看见",
      traditional: "看見",
    },
    {
      english: "Call",
      pinyin: "jiào",
      simplified: "叫",
      traditional: "叫",
    },
    {
      english: "Come",
      pinyin: "lái",
      simplified: "来",
      traditional: "來",
    },
    {
      english: "Return",
      pinyin: "huí",
      simplified: "回",
      traditional: "時",
    },
    {
      english: "Go",
      pinyin: "qù",
      simplified: "去",
      traditional: "去",
    },
    {
      english: "Eat",
      pinyin: "chī",
      simplified: "吃",
      traditional: "吃",
    },
    {
      english: "Drink",
      pinyin: "hē",
      simplified: "喝",
      traditional: "喝",
    },
    {
      english: "Sleep",
      pinyin: "shuìjiào",
      simplified: "睡觉",
      traditional: "睡覺",
    },
    {
      english: "Know",
      pinyin: "rènshi",
      simplified: "认识",
      traditional: "認識",
    },
    {
      english: "Call up",
      pinyin: "dǎdiànhuà",
      simplified: "打电话",
      traditional: "打電話",
    },
    {
      english: "Do",
      pinyin: "zuò",
      simplified: "做",
      traditional: "做",
    },
    {
      english: "Happy",
      pinyin: "gāoxìng",
      simplified: "高兴",
      traditional: "高興",
    },
    {
      english: "Buy",
      pinyin: "mǎi",
      simplified: "买",
      traditional: "買",
    },
    {
      english: "Open",
      pinyin: "kāi",
      simplified: "开",
      traditional: "開",
    },
    {
      english: "Sit",
      pinyin: "zuò",
      simplified: "坐",
      traditional: "坐",
    },
    {
      english: "Live",
      pinyin: "zhù",
      simplified: "住",
      traditional: "住",
    },
    {
      english: "Study",
      pinyin: "xuéxí",
      simplified: "学习",
      traditional: "學習",
    },
    {
      english: "Work",
      pinyin: "gōngzuò",
      simplified: "工作",
      traditional: "工作",
    },
    {
      english: "Rain",
      pinyin: "xiàyǔ",
      simplified: "下雨",
      traditional: "下雨",
    },
    {
      english: "Ask",
      pinyin: "wèn",
      simplified: "问",
      traditional: "問",
    },
    {
      english: "Walk",
      pinyin: "zǒu",
      simplified: "走",
      traditional: "走",
    },
    {
      english: "Enter",
      pinyin: "jìn",
      simplified: "进",
      traditional: "進",
    },
    {
      english: "Come",
      pinyin: "chū",
      simplified: "出",
      traditional: "出",
    },
    {
      english: "Run",
      pinyin: "pǎobù",
      simplified: "跑步",
      traditional: "跑步",
    },
    {
      english: "Arrive",
      pinyin: "dào",
      simplified: "到",
      traditional: "到",
    },
    {
      english: "Wear",
      pinyin: "chuān",
      simplified: "穿",
      traditional: "穿",
    },
    {
      english: "Wash",
      pinyin: "xǐ",
      simplified: "洗",
      traditional: "洗",
    },
    {
      english: "Give",
      pinyin: "gěi",
      simplified: "给",
      traditional: "給",
    },
    {
      english: "Find",
      pinyin: "zhǎo",
      simplified: "找",
      traditional: "找",
    },
    {
      english: "Understand",
      pinyin: "dǒng",
      simplified: "懂",
      traditional: "懂",
    },
    {
      english: "Smile",
      pinyin: "xiào",
      simplified: "笑",
      traditional: "笑",
    },
    {
      english: "Answer",
      pinyin: "huídá",
      simplified: "回答",
      traditional: "回答",
    },
    {
      english: "Tell",
      pinyin: "gàosù",
      simplified: "告诉",
      traditional: "告訴",
    },
    {
      english: "Prepare",
      pinyin: "zhǔnbèi",
      simplified: "准备",
      traditional: "準備",
    },
    {
      english: "Begin",
      pinyin: "kāishǐ",
      simplified: "开始",
      traditional: "開始",
    },
    {
      english: "Introduce",
      pinyin: "jièshào",
      simplified: "介绍",
      traditional: "介紹",
    },
    {
      english: "Help",
      pinyin: "bāngzhù",
      simplified: "帮助",
      traditional: "幫助",
    },
    {
      english: "Play",
      pinyin: "wán",
      simplified: "玩",
      traditional: "玩",
    },
    {
      english: "Present",
      pinyin: "sòng",
      simplified: "送",
      traditional: "送",
    },
    {
      english: "Wait",
      pinyin: "děng",
      simplified: "等",
      traditional: "等",
    },
    {
      english: "Let",
      pinyin: "ràng",
      simplified: "让",
      traditional: "讓",
    },
    {
      english: "Get up",
      pinyin: "qǐchuáng",
      simplified: "起床",
      traditional: "起床",
    },
    {
      english: "Sing",
      pinyin: "chànggē",
      simplified: "唱歌",
      traditional: "唱歌",
    },
    {
      english: "Dance",
      pinyin: "tiàowǔ",
      simplified: "跳舞",
      traditional: "跳舞",
    },
    {
      english: "Travel",
      pinyin: "lǚyóu",
      simplified: "旅游",
      traditional: "旅遊",
    },
    {
      english: "Be on duty",
      pinyin: "shàngbān",
      simplified: "上班",
      traditional: "上班",
    },
    {
      english: "Fall ill",
      pinyin: "shēngbìng",
      simplified: "生病",
      traditional: "生病",
    },
    {
      english: "Rest",
      pinyin: "xiūxi",
      simplified: "休息",
      traditional: "休息",
    },
    {
      english: "Exercise",
      pinyin: "yùndòng",
      simplified: "运动",
      traditional: "運動",
    },
    {
      english: "Swim",
      pinyin: "yóuyǒng",
      simplified: "游泳",
      traditional: "游泳",
    },
    {
      english: "Play footbal",
      pinyin: "tīzúqiú",
      simplified: "踢足球",
      traditional: "踢足球",
    },
    {
      english: "Play basketball",
      pinyin: "dǎlánqiú",
      simplified: "打篮球",
      traditional: "打籃球",
    },
    {
      english: "Finish",
      pinyin: "wán",
      simplified: "完",
      traditional: "完",
    },
    {
      english: "Love",
      pinyin: "ài",
      simplified: "爱",
      traditional: "愛",
    },
    {
      english: "Love, like",
      pinyin: "xǐhuān",
      simplified: "喜欢",
      traditional: "喜歡",
    },
    {
      english: "Want",
      pinyin: "xiǎng",
      simplified: "想",
      traditional: "想",
    },
    {
      english: "Think",
      pinyin: "juédé",
      simplified: "觉得",
      traditional: "覺得",
    },
    {
      english: "Know",
      pinyin: "zhīdao",
      simplified: "知道",
      traditional: "知道",
    },
    {
      english: "Hope",
      pinyin: "xīwàng",
      simplified: "希望",
      traditional: "希望",
    },
    {
      english: "Can, be able to",
      pinyin: "néng",
      simplified: "能",
      traditional: "能",
    },
    {
      english: "Can",
      pinyin: "kěyǐ",
      simplified: "可以",
      traditional: "可以",
    },
    {
      english: "Ask for",
      pinyin: "yào",
      simplified: "要",
      traditional: "要",
    },
    {
      english: "May",
      pinyin: "kěnéng",
      simplified: "可能",
      traditional: "可能",
    },
    {
      english: "Good",
      pinyin: "hǎo",
      simplified: "好",
      traditional: "好",
    },
    {
      english: "Big",
      pinyin: "dà",
      simplified: "大",
      traditional: "大",
    },
    {
      english: "Small",
      pinyin: "xiǎo",
      simplified: "小",
      traditional: "小",
    },
    {
      english: "Many, much",
      pinyin: "duō",
      simplified: "多",
      traditional: "多",
    },
    {
      english: "Few, little",
      pinyin: "shǎo",
      simplified: "少",
      traditional: "少",
    },
    {
      english: "Cold",
      pinyin: "lěng",
      simplified: "冷",
      traditional: "冷",
    },
    {
      english: "Hot",
      pinyin: "rè",
      simplified: "热",
      traditional: "熱",
    },
    {
      english: "Beautiful",
      pinyin: "piàoliang",
      simplified: "漂亮",
      traditional: "漂亮",
    },
    {
      english: "Tall",
      pinyin: "gāo",
      simplified: "高",
      traditional: "高",
    },
    {
      english: "Red",
      pinyin: "hóng",
      simplified: "红",
      traditional: "紅",
    },
    {
      english: "White",
      pinyin: "bái",
      simplified: "白",
      traditional: "白",
    },
    {
      english: "Black",
      pinyin: "hēi",
      simplified: "黑",
      traditional: "黑",
    },
    {
      english: "Busy",
      pinyin: "máng",
      simplified: "忙",
      traditional: "忙",
    },
    {
      english: "Fast",
      pinyin: "kuài",
      simplified: "快",
      traditional: "快",
    },
    {
      english: "Slow",
      pinyin: "màn",
      simplified: "慢",
      traditional: "慢",
    },
    {
      english: "Far",
      pinyin: "yuǎn",
      simplified: "远",
      traditional: "遠",
    },
    {
      english: "Close",
      pinyin: "jìn",
      simplified: "近",
      traditional: "近",
    },
    {
      english: "Delicioous",
      pinyin: "hǎochī",
      simplified: "好吃",
      traditional: "好吃",
    },
    {
      english: "Tired",
      pinyin: "lèi",
      simplified: "累",
      traditional: "累",
    },
    {
      english: "Long",
      pinyin: "cháng",
      simplified: "长",
      traditional: "長",
    },
    {
      english: "New",
      pinyin: "xīn",
      simplified: "新",
      traditional: "新",
    },
    {
      english: "Expensive",
      pinyin: "guì",
      simplified: "贵",
      traditional: "貴",
    },
    {
      english: "Cheap",
      pinyin: "piányi",
      simplified: "便宜",
      traditional: "便宜",
    },
    {
      english: "Fine",
      pinyin: "qíng",
      simplified: "晴",
      traditional: "晴",
    },
    {
      english: "Cloudy",
      pinyin: "yīn",
      simplified: "阴",
      traditional: "陰",
    },
    {
      english: "Wrong",
      pinyin: "cuò",
      simplified: "错",
      traditional: "錯",
    },
    {
      english: "Happy",
      pinyin: "kuàilè",
      simplified: "快乐",
      traditional: "快樂",
    },
    {
      english: "Can",
      pinyin: "huì",
      simplified: "会",
      traditional: "會",
    },

    {
      english: "Become excited",
      pinyin: "dǎ jī xuè",
      simplified: "打鸡血",
      traditional: "打雞血",
    },
    {
      english: "Cute or adorable",
      pinyin: "méng méng dá",
      simplified: "萌萌哒",
      traditional: "萌萌噠",
    },
    {
      english: "Boss",
      pinyin: "lǎobǎn",
      simplified: "老板",
      traditional: "老闆",
    },
    {
      english: "Spicy eyes (an eyesore)",
      pinyin: "là yǎnjīng",
      simplified: "辣眼睛",
      traditional: "辣眼睛",
    },
    {
      english: "To panic",
      pinyin: "fāngle",
      simplified: "方了",
      traditional: "方了",
    },
    {
      english: "Down to Earth",
      pinyin: "Jiēdì qì",
      simplified: "接地气",
      traditional: "接地氣",
    },
    {
      english: "To feel completely lost",
      pinyin: "yī liǎn měng bī",
      simplified: "一脸懵逼",
      traditional: "一臉懵逼",
    },
  ],
};

export default lesson2;
